### PR TITLE
Blitz Auth Adapter

### LINKED ISSUE #7941: Incomplete list in package.json "exports" section
### Environment

  **System**:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.05 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  **Binaries**:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
  **Browsers**:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.198
    Chrome Canary: 117.0.5867.0
    Safari: 16.4.1

### Reproduction URL

https://blitzjs-next-auth-bug.vercel.app/

### Describe the issue

I'm running NextAuth with BlitzJS framework - https://blitzjs.com/docs/next-auth

However, when I try to call `/api/auth/[github,google,linkedin]/login`, I see the following error

```log
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './core/init' is not defined by "exports" in /var/task/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.29_blitz@2.0.0-beta.29_next-auth@4.22.1_next@13.3.0_secure-password@4.0.0/node_modules/next-auth/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:702:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at mod._resolveFilename (/var/task/node_modules/.pnpm/next@13.3.0_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

It seems that `package.json` in `next-auth` is missing the following in the `"exports"` section:

```
"exports": {
    ...
    "./core/init": "./core/init.js",
    "./core/lib/oauth/authorization-url": "./core/lib/oauth/authorization-url.js",
    "./core/lib/oauth/callback": "./core/lib/oauth/callback.js",
    ...
},
```

### How to reproduce

* Go to https://blitzjs-next-auth-bug.vercel.app/
* Click on "Sign in with Google" or "Sign in with Github"
  * You will see only HTTP 400, you will need to run this locally to see error log

### Expected behavior

**Expected:**
The sign in screen of Google or Github is shown

**Solution:**
=> After I add those lines to `package.json`, the workflow works normally!

### PR DESCRIPTION
**Pull request by siddhsuresh**
## ☕️ Reasoning

Hello @balazsorban44! I hope you're doing well. I wanted to reach out as one of the maintainers of blitz-js. In our efforts to enhance blitz, we have developed an adapter that works in conjunction with next-auth to provide users with the ability to utilize blitz-auth API seamlessly with next-auth's OAuth providers.

Throughout our development process, we encountered several obstacles while utilizing next-auth's Internal API directly (as expected). As a result, we have initiated a pull request (PR) to address these challenges. 

This PR will facilitate us to make the adapter more stable, rather than relying on runtime patching and allow other external libraries to be build on top of `@auth/core` and `next-auth`.

Thank you.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/7941 https://github.com/blitz-js/blitz/issues/4143 https://github.com/blitz-js/blitz/issues/4171

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks! I'm happy to help move this forward!

`next-auth` will remain Next.js specific, and we do not plan to expose internal APIs, so this PR in its current form won't be accepted. I'm happy to investigate though how we can make `@auth/core` more flexible, which is the intended package for library/framework authors to build on top of.

Note that #7443 is going to refactor the internals of `next-auth` significantly, so that is another reason these changes are not going to work in the long term.

**Comment by siddhsuresh** [comment]
> Thanks! I'm happy to help move this forward!
> 
> `next-auth` will remain Next.js specific, and we do not plan to expose internal APIs, so this PR in its current form won't be accepted. I'm happy to investigate though how we can make `@auth/core` more flexible, which is the intended package for library/framework authors to build on top of.
> 
> Note that #7443 is going to refactor the internals of `next-auth` significantly, so that is another reason these changes are not going to work in the long term.

Hey @balazsorban44! thank you for the quick response

Understood. I have reverted the changes regarding exposing internals of `next-auth`. 

I am yet to get a proper development environment here, so I cannot say for certain. But during my research process before building the current adapter, I found that I needed these 3 functions from `@auth/core`: `init`, `callback` and `authorization-url` to make it functional. Which I have now exposed in this PR.

This will allow us to pivot our adapter to work directly with `@auth/core`.

**Comment by balazsorban44** [comment]
Can you point me where these are invoked in blitz?

**Comment by siddhsuresh** [comment]
@balazsorban44 would you like me to re implement this with `@auth/core` and then would this request be accepted? Or are the other issues with exposing these functions?

**Pull request closed without merging**
