### PR TITLE
feat: test webauthn platform auth

### PR DESCRIPTION
**Pull request by ndom91**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](../Security.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Big time WIP

### Note:
- https://medium.com/webauthnworks/introduction-to-webauthn-api-5fd1fb46c285
- https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential#getting_an_existing_instance_of_publickeycredential
- https://simplewebauthn.dev/docs/packages/server

### Screenshot:
image

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by bradennapier** [comment]
in case you haven't seen it, this library made it fairly easy to implement into my app via Cloudflare sqlite and provides good conventions for some of the confusing aspects

https://simplewebauthn.dev/

**Comment by ndom91** [comment]
> in case you haven't seen it, this library made it fairly easy to implement into my app via Cloudflare sqlite and provides good conventions for some of the confusing aspects
> 
> [simplewebauthn.dev](https://simplewebauthn.dev/)

Yeah thanks for pointing that out! I did stumble upon that during my research, but wanted to give it a shot implementing it from scratch myself, because it seem(ed) to be just a few Web APIs.

Do you have any additional experience with webauthn/passkeys? Is this route looking correct at least? :sweat_smile:

**Comment by bradennapier** [comment]
I implemented it out of curiosity to see if it was as cool as it seemed using that package.  I haven't reviewed your code yet but I will take a look

**Comment by bradennapier** [comment]
Oh lord lol that demo on that site is AMAZING

**Comment by ndom91** [comment]
@bradennapier alright awesome, thanks a ton for all the info! I'll probably just end up pulling in that lib then 😅 

Since you do seem to have a good amt of experience with it, do you mind if I ping you for a review later when this is closer to being ready? 🙏

**Comment by bradennapier** [comment]
Ofc - I am eager to see the result!  I think pass keys will be insanely transformative !

**Comment by ndom91** [comment]
Closing in favor of the work done here: https://github.com/nextauthjs/next-auth/pull/8808

**Pull request closed without merging**
