### PR TITLE
docs: scope example

### PR DESCRIPTION
**Pull request by alexandredev3**
## Reasoning 💡
I added the scope in the [...nextauth].js getting started example because I took some time to figure out where to add this scope, and I think that will be helpful for developers who are using NextAuth for the first time and wanna add this scope.

### CODE REVIEW

**Comment by lluia** [comment]
Thanks 💚

While I agree the customisation options for the `authorization`, `token` and `userinfo` requests are not obvious, I think we should document this some other way. Maybe it deserves a whole new section on the **Getting Started** page. What do you think @balazsorban44 @ndom91 ?

**Comment by balazsorban44** [comment]
I think this should either be addressed/better documented under https://next-auth.js.org/configuration/providers/oauth#override-default-options

Or we should allow top-level scope again, as it seems to be a common point of confusion. :thinking: This would mean that we diverge from the path I wished though (enforcing stricter OAuth concepts by grouping `scope` under `authorization`)

**Comment by lluia** [comment]
I'll open a PR trying to explain this better ✍🏼

**Comment by balazsorban44** [comment]
I'm closing as I think this would be the wrong place to explain `scope`. We are thinking about restructuring our documentation anyway.

**Pull request closed without merging**
