### PR TITLE
Docs Site Update

### PR DESCRIPTION
**Pull request by ndom91**
Got rid of all the default docusaurus imagery, etc. 

Added tabbed function component / class component example to the client page.

Added admonition callouts to a few pages.

FYI, all the fancy Markdown things you can do in Docusaurus are detailed here: https://v2.docusaurus.io/docs/markdown-features/

### CODE REVIEW

**Comment by ndom91** [comment]
Man those branch deploy previews are so fast! Haha

**Comment by iaincollins** [comment]
Oh cool, was just about to take a look at options!

**Comment by ndom91** [comment]
Wait a sec, about to post one more commit haha

**Comment by ndom91** [comment]
Okay my last update to this branch tonight was just pushed :)

**Pull request merged**
