### PR TITLE
docs: Remove unnecessary promises

### LINKED ISSUE #731: Simplify code/examples
I have seen this many places, like [this example code](https://next-auth.js.org/configuration/callbacks#sign-in-callback):

```js
signIn: async (user, account, profile) => {
  const isAllowedToSignIn = true
  if (isAllowedToSignIn) {
    return Promise.resolve(true)
  } else {
    // Return false to display a default error message
    return Promise.resolve(false)
    // You can also Reject this callback with an Error or with a URL:
    // return Promise.reject(new Error('error message')) // Redirect to error page
    // return Promise.reject('/path/to/redirect')        // Redirect to a URL
  }
}
```

When defining an async function, the returned value is automatically resolved, meaning one could refactor the above code. (Notice that throwing an Error would probably also feel more natural):

```js
async signIn(user, account, profile) {
  const isAllowedToSignIn = true
  if (isAllowedToSignIn) {
    return true
  } else {
    // Return false to display a default error message
    return false
    // You can also Reject this callback with an Error or with a URL:
    // throw new Error('error message')) // Redirect to error page
    // return Promise.reject('/path/to/redirect')        // Redirect to a URL
  }
}
```

This may be only a personal preference, but I think it would also be easier to parse the code for newcomers. With the rise of "async/await", maybe there is lesser need of using `Promise`s all-together. Any special reason I am unaware for using `Promise.resolve()` everywhere?

### PR DESCRIPTION
**Pull request by balazsorban44**
There is an open discussion about this already in #731, but after looking at some of the issues and trying to help people, I came across MANY code examples from users using `Promise.resolve()` and `Promise.reject()` where it is not needed.

It is not strange, after all, we currently encourage this through the docs.

The following search yields 72 issues using `Promise.resolve`:
https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+Promise.resolve

I argue that using `Promise` and `async/await` together has a negative effect since new developers might not know the connection between the two and would think that they have to rely on it for things to work. The above issue query proves just that. Furthermore, if someone starts looking up how Promises are handled, they might go down a path where they come across a lot of code using `.then` that will result in callback hell.

Even though the intention was to "self-document", I am certain it had the opposite effect what the original author intended. (#897 got simply resolved by removing `Promise`)

Besides, I don't know of any other library using this "technique" to teach `async/await`.

closes #731

### CODE REVIEW

**Comment by balazsorban44** [comment]
@iaincollins please do reconsider your decision on this, to prevent further issues being raised deriving from this easily misunderstandable behavior in our examples.

**Review by iaincollins — APPROVED** [review]
Thanks for talking though this!

**Comment by foaadnami** [comment]
@balazsorban44 is on fire this new years eve!

Happy new year everyone

**Comment by balazsorban44** [comment]
Thanks! 🎇🥂

**Pull request merged**
