### PR TITLE
fix(sveltekit): adds the missing input field for `redirectTo`

### LINKED ISSUE #10135: sveltekit redirectTo component option not working
### Environment

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 97.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.2.1

### Reproduction URL

https://github.com/kinglouie/authjsrepro2/

### Describe the issue

After the user logs in I want to redirect to the original requested url, to achieve this I want to leverage the `options` prop of the `SignIn.svelte` component as seen [here](https://github.com/kinglouie/authjsrepro2/blob/d09f34a2bd7607f7df4a72248d9abd83b9701f39/src/routes/%2Bpage.svelte#L17) in the repro.

This feature is unfortunately broken at the moment. The `redirectTo` url is successfully transmitted by the hidden form input but the sveltekit specific `signIn` action is buggy in this snippet:
https://github.com/nextauthjs/next-auth/blob/fbb8af526b075b9161e0bf7642c9ee730c3212b0/packages/frameworks-sveltekit/src/lib/actions.ts#L22-L28
the `options` obj does not contain the key `redirectTo`, instead the redirect url is in the `callbackUrl` and also in the `redirect` key.
Options looks like this when logging it in my repro:
```
{
  callbackUrl: '/test',
  redirect: '/test',
  email: 'test@test.com',
  password: 'test'
}
```

### How to reproduce

Run the repro repository and click the sign in button on the index page, notice how it does not redirect to the `/test` url
This should be an easy fix by correctly reading the `callbackUrl` from the options, my testing fix looks like this:
```
const callbackUrl = options.callbackUrl?.toString() ?? headers.get("Referer") ?? "/";
```

### LINKED ISSUE #12274: `options.redirectTo` prop not working for SvelteKit `SignIn` component
### Environment

```
  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 5.50 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/nvm/current/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - ~/nvm/current/bin/npm
    pnpm: 9.11.0 - ~/nvm/current/bin/pnpm
  npmPackages:
    @auth/sveltekit: latest => 1.7.4 
    @sveltejs/kit: 2.5.7 => 2.5.7 
    svelte: 4.2.19 => 4.2.19 
```

### Reproduction URL

https://github.com/Stadly/reproduction/tree/authjs/signin-redirect

### Describe the issue

The user is not redirected to `/protected` after clicking the sign-in button and signing in.

### How to reproduce

```svelte
<script lang="ts">
  import { SignIn } from "@auth/sveltekit/components"
</script>
<SignIn options={{ redirectTo: "/protected" }}/>
```

If you try the reproduction URL, click the two sign-in buttons in the header and inspect the `authjs.callback-url` cookie. The button using the `SignIn` component does not set `/protected` in the cookie.

### Expected behavior

The user is redirected to `/protected` after signing in.

### PR DESCRIPTION
**Pull request by NazgoooAtanasov**
## ☕️ Reasoning
Allows sveltekit users to redirect to a certain page after succcessful signin.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: #12274 - solves this by adding the `redirectTo` option as a hidden input field in the sign in form;
Fixes: #10135 - solves this by adding the `redirectTo` option as a hidden input field in the sign in form.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by Simeon-Kirilov** [comment]
Wow, very nice!

**Comment by Stadly** [comment]
Seems to work! Thanks, @NazgoooAtanasov 🚀

**Comment by rawwerks** [comment]
can someone please review?

**Review by ndom91 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
