### PR TITLE
📝 Remove extra space in code

### PR DESCRIPTION
**Pull request by max-programming**
## ☕️ Reasoning

Just a little change in the documentation where there was an extra space in the code
image

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

None

### CODE REVIEW

**Comment by max-programming** [comment]
## Disclaimer

This PR is not spam PR for hacktoberfest. I thought I should make this change so I did. It's up to the maintainers to decide whether to merge it.

**Review by rhinodavid — APPROVED** [review]

**Review by balazsorban44 — APPROVED** [review]
Thanks! 😁

**Comment by balazsorban44** [comment]
I just opted us into hacktoberfest. 👍😌 I'm fine with it, we might get a few meaningful contributions 🙏

**Comment by max-programming** [comment]
> I just opted us into hacktoberfest. 👍😌 I'm fine with it, we might get a few meaningful contributions 🙏

Nice to see that! Thank you!

**Pull request merged**
