### PR TITLE
fix(ts): enable EndpointRequest type to return void type

### LINKED ISSUE #7312: When OAuth Provider userinfo create a noop function, unable to assign void type
### Question 💬

As introduced in [userinfo](https://next-auth.js.org/configuration/providers/oauth#userinfo-option), I tried the noop function, but I got a type error (Type 'void' is not assignable to type 'Awaitable<Profile>').

I'm updating and using it according to the code below.
Is there a best practice?

```typescript
// next-auth/providers/oauth.ts
// before update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R>;
```

```typescript
// next-auth/providers/oauth.ts
// after update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R> | void ;
```

### How to reproduce ☕️

[CodeSandbox](https://codesandbox.io/s/bold-murdock-6fz09w?file=/pages/api/auth/%5B...nextauth%5D.ts)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

### PR DESCRIPTION
**Pull request by blan19**
## Description

fix #7312 

In the rare case you don't care about what this endpoint returns, or your provider does not have one, you could create a noop function [userinfo](https://next-auth.js.org/configuration/providers/oauth#userinfo-option) reqeust

```javascript
userinfo: {
  request: () => {}
}
```

but I got a type error (Type 'void' is not assignable to type 'Awaitable').

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

I'm updating and using it according to the code below.

```typescript
// next-auth/providers/oauth.ts
// before update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R>;
```

```typescript
// next-auth/providers/oauth.ts
// after update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R> | void ;
```

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ThangHuuVu — APPROVED** [review]
Awesome, thanks for the PR @blan19 🙏

**Comment by ThangHuuVu** [comment]
sorry, could you make the change in core/src/providers/oauth instead?

**Comment by blan19** [comment]
> sorry, could you make the change in core/src/providers/oauth instead?

yes, i applied the change in core/src/providers/oauth about EndpointRequest type 😀😀

**Comment by ThangHuuVu** [comment]
sorry, there are unrelated changes in your branch (because of something from main) could you help clean the PR again?

**Comment by blan19** [comment]
> sorry, there are unrelated changes in your branch (because of something from main) could you help clean the PR again?

I don't know if I did a good clean PR, but I sent the PR again #8112 haha

**Pull request closed without merging**
