### PR TITLE
fix: expose `openid-client` client and jwks options

### PR DESCRIPTION
**Pull request by balazsorban44**
In #2411, we introduced `openid-client` as the new underlying OAuth library. It came with a lot of configuration options, which we unintentionally obscured as it seemed to be unnecessary. In the issues below it was proven wrong, so for advanced usecases, we want to let the user configure everything according to their likings.

There is still an option we don't allow to configure, which is https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-issuermetadata 

If a need arise, we can expose that as `issuer` as well. That property is already reserved for a url though, so similar to `authorization`, `token` and `userinfo` it will be able to take the form of either an url or an object.

Relevant issues: #2524, #2708

### CODE REVIEW

**Comment by javigonz** [comment]
@balazsorban44 That´s works really fine. Now we could pass more options to `client` and be more precise in their configuration:

```js
import NextAuth from 'next-auth';
import CognitoProvider from 'next-auth/providers/cognito';

export default NextAuth({
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      domain: process.env.COGNITO_DOMAIN,
      client: {
        token_endpoint_auth_method: 'none'
      },
      issuer: `https://${process.env.COGNITO_DOMAIN}/`
    })
  ],
  callbacks: {...}
});
```

Thanks so much **Balázs Orbán** for your fast and excellent work, this library is amazing.

**Comment by balazsorban44** [comment]
good to hear! I very much wanted to check this myself, but registering to AWS required my credit card, which I wasn't going to give them. 🤷‍♂️

Do you know if AWS have some kind of a solution for us to be able to register to Cognito without a credit card? we need the absolute bare minimum setup, just to be able to check the login flow.

**Comment by balazsorban44** [comment]
I think I found a way. 😄

Utilizing [our OpenCollective page] (https://opencollective.com/nextauth), I could request a virtual bank card:

https://blog.opencollective.com/virtual-card-support

I'll test this out later today.

**Comment by javigonz** [comment]
This looks great, let me know if you need some help from userPool or whatever.

**Comment by Fronix** [comment]
@balazsorban44 
I don't think there is a way to register to Cognito without a credit card. However, you could sign up for [revolut](https://www.revolut.com/) and create a virtual credit card with no money on it. That would ensure no money can be charged and you don't give them your real cc info.

**Comment by balazsorban44** [comment]
Cognito has been resolved, without this. :eyes: See #2829 If not necessary, then I don't want to expose additional options. I'll close this for now. Feel free to comment if there is an objection, but please check #2829 first.

**Comment by danieltott** [comment]
I had just landed on this PR as a solution that has taken me 2 days to figure out - using a custom OAuth Provider - the only way to get the token request through was to change the `Client` call in `node_modules/next-auth/server/lib/oauth/client.js`

```
  const client = new issuer.Client({
    client_id: provider.clientId,
    client_secret: provider.clientSecret,
    redirect_uris: [provider.callbackUrl],
    token_endpoint_auth_method: 'client_secret_post'
  });
```

I would love it if this PR got back in...

**Comment by balazsorban44** [comment]
@danieltott, no problem, if there is actual interest! :sweat_smile: Could you please check if `next-auth@0.0.0-pr.2717.06130bef` works for you? I did release it in experimental, but there was no feedback on it.

It exposes new options, see this PR for details.

**Comment by danieltott** [comment]
@balazsorban44 YES! Just tested it, worked perfectly 👍  🥳

**Comment by balazsorban44** [comment]
Let's get it in then! 😬 No ETA on new beta release yet, I want to do less of those then `next` releases.. you can use the above version until then. Thanks for checking it out!

**Pull request merged**
