### PR TITLE
Using Firebase Admin SDK

### PR DESCRIPTION
**Pull request by nhuethmayr**
New adapter that uses the Firebase Admin instead of the client-side SDK

## ☕️ Reasoning

The current implementation of firebase-adapter uses the client SDK. This has the severe drawback that the Firestore Rules need to be opened up. Instead of using the client-side SDK, we should be using the server-side one. That way we can keep the Firestore rules closed and still integrate nicely with FB

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

This PR solves an architectural problem with the firebase-adapter as descibed in discussion [5049](https://github.com/nextauthjs/next-auth/issues/5049)

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

## ❓ Questions 

- Do we want to release this code as an independent adapter? `firebase-admin-adapter`
- Do we want to replace the current implementation altogether?

### CODE REVIEW

**Comment by shriharip** [comment]
Thanks for the efforts on making use of the admin SDK, could we plz have this merged soon.

**Comment by ndom91** [comment]
Thanks for reopening!

**Review by RonAlmog — APPROVED** [review]

**Comment by NorbertHuethmayr** [comment]
@RonAlmog I still need to add in tests (hopefully today, maybe tomorrow) but what about the "Verify (javascript)" task that is pending?

**Comment by bcthakre** [comment]
Thanks @NorbertHuethmayr

**Comment by MalteBoehm** [comment]
Any news on this one?

**Review by MalteBoehm — APPROVED** [review]

**Comment by bcthakre** [comment]
Does it mean we can use FirestoreAdapter now?

**Comment by MalteBoehm** [comment]
> 

Nah, merge is blocked

**Comment by bcthakre** [comment]
Probably go with Clerk for now. Also, NextJS 13 has issues with NextAuth

**Comment by MalteBoehm** [comment]
> Probably go with Clerk for now. Also, NextJS 13 has issues with NextAuth

I don't care too much about Next13 since it's kind of interesting beta. It just would be nice to use the firebase adapter to save some time :)

**Comment by MalteBoehm** [comment]
@ndom91 hey there, for me it all works and looks as expected. Could you perhaps do a review on this too? :)

**Comment by vedantmgoyal2009** [comment]
@NorbertHuethmayr please resolve the conflicts!

**Comment by Chibionos** [comment]
@ndom91 @lluia @ThangHuuVu  
**Can we get a PR for this please ? The change is required for NextAuth Firebase to be used in any Enterprise scenario as we cannot use the current Firebase Adapter due to a huge security issue we talked about here.**

https://github.com/nextauthjs/next-auth/issues/5049

FYI @NorbertHuethmayr @shriharip @bcthakre

**Comment by shriharip** [comment]
Yes, I agree, would be best to have this in quickly. I have also now upvoted the PR. @NorbertHuethmayr @Chibionos

**Comment by Mike968** [comment]
I opened PR on @NorbertHuethmayr fork... contributer used the windows command prompt only `del` command. Instead, it should be the `rm` command considering the build is being run on a Linux build server.

Hopefully should at least fix the build from throwing that error

**Comment by NorbertHuethmayr** [comment]
> I opened PR on @NorbertHuethmayr fork... contributer used the windows command prompt only `del` command. Instead, it should be the `rm` command considering the build is being run on a Linux build server.
> 
> Hopefully should at least fix the build from throwing that error

Done 👍 - now I need to pull in changes from main to be up to date.

**Comment by bcthakre** [comment]
Seems like there is a new version of NextAuth. Has the firestore adaptateur improved in it. Best Regards, Bhupendrasinh ThakreOn Dec 13, 2022, at 1:48 PM, Norbert Hüthmayr ***@***.***> wrote:﻿

I opened PR on @NorbertHuethmayr fork... contributer used the windows command prompt only del command. Instead, it should be the rm command considering the build is being run on a Linux build server.
Hopefully should at least fix the build from throwing that error

Done 👍 - now I need to pull in changes from main to be up to date.

**Comment by BossBele** [comment]
@bcthakre The PR works on having the firebase adapter using **admin SDK** and not on updating the firebase web SDK module. In that case, the security concern leading to this proposed PR is still not addressed.

+1 for this PR

**Pull request closed without merging**
