### PR TITLE
chore(docs): add initialization section for prisma-adapter

### PR DESCRIPTION
**Pull request by halvaradop**
## ☕️ Reasoning
This pull request adds an initialization section and a detailed description for the environment variables section for the Prisma adapter. It includes a brief explanation of how to use the `DATABASE_URL` environment variable and provides a link to Prisma's official documentation. These updates aim to improve the guidance on connecting to a database using Prisma within the project.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — COMMENTED** [review]
I appreciate your interest, but I'm not sure it's our responsibility to help folks get their initial prisma setup working. That's what their own docs are for imo. 

Maybe just a sentence or two and a link to their docs?

**Comment by halvaradop** [comment]
You're right; it's not the responsibility of `auth.js` to help users set up Prisma initially. However, I only want to add content to assist users in connecting. I think it would be a good idea to include a description in the environment variables section, along with a link to the official documentation.

**Comment by halvaradop** [comment]
I have made the changes based on your suggestions. These changes include adding a general description for the environment variables and removing the initialization section.

**Review by ndom91 — APPROVED** [review]
Great, that looks more appropriate 👌

**Pull request merged**
