### PR TITLE
fix(adapters): comply to Node.js native ESM resolver

### LINKED ISSUE #6740: [FATAL] Firebase adapter is broken
### Adapter type

@next-auth/firebase-adapter

### Environment

```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 218.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.n/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - ~/.n/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
```

### Reproduction URL

https://github.com/maxprilutskiy/next-auth-bug

### Describe the issue

Firebase/Firestore Adapter is broken. Attempts to have even a minimal code that does imports from `@next-auth/firebase-adapter` result in errors:

```
Server Error
Error: Cannot find module '/Users/maxprilutskiy/Enprimal/asyncrun/node_modules/@next-auth/firebase-adapter/utils' imported from /Users/maxprilutskiy/Enprimal/asyncrun/node_modules/@next-auth/firebase-adapter/index.js

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
new NodeError
node:internal/errors (399:5)
finalizeResolution
node:internal/modules/esm/resolve (326:11)
moduleResolve
node:internal/modules/esm/resolve (945:10)
defaultResolve
node:internal/modules/esm/resolve (1153:11)
nextResolve
node:internal/modules/esm/loader (163:28)
ESMLoader.resolve
node:internal/modules/esm/loader (838:30)
ESMLoader.getModuleJob
node:internal/modules/esm/loader (424:18)
ModuleWrap.<anonymous>
node:internal/modules/esm/module_job (77:40)
link
node:internal/modules/esm/module_job (76:36)
```

### How to reproduce

In order to reproduce the issue, it's enough to just do the following:

1. `yarn create next-app test`
2. `yarn add next-auth @next-auth/firebase-adapter firebase-admin` - btw the docs page has a typo and says `@next-auth/firebase-admin-adapter` instead of `@next-auth/firebase-adapter`. The references are broken everywhere, so I couldn't find the corresponding GitHub source of truth to fix it, sorry;
3. import anything from `@next-auth/firebase-adapter`, for example - [https://github.com/maxprilutskiy/next-auth-bug/blob/master/src/pages/api/hello.ts](https://github.com/maxprilutskiy/next-auth-bug/blob/master/src/pages/api/hello.ts):
```typescript
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { FirestoreAdapter } from "@next-auth/firebase-adapter"

type Data = {
  name: string
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  console.log(FirestoreAdapter);
  res.status(200).json({ name: 'John Doe' })
}
```

### Expected behavior

I expect the documentation to work as described and not to throw errors.

### PR DESCRIPTION
**Pull request by ThangHuuVu**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Add import extension for Firebase adapter

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: #6740

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]

**Review by balazsorban44 — APPROVED** [review]

**Comment by NovaBG03** [comment]
Hey, how can I use the version with these changes applied?

**Comment by jokamjohn** [comment]
Hello, when is this going to be released?

**Comment by bcthakre** [comment]
Do we need to change the firebase-adapter version to use the improved adapter. Also, do we need to make any change in the firestorm security rules

**Comment by NovaBG03** [comment]
> Do we need to change the firebase-adapter version to use the improved adapter. Also, do we need to make any change in the firestorm security rules. Also, does this version requires to use the firebase-admin or firebase client version to use the adapter

I think that in version 2+ the firebase-adapter will use firebase-admin SDK and this will allow us to modify the stored data server-side regardless of your current security rules.

**Pull request merged**
