### PR TITLE
fix: add getSetCookie to session cookies if supported

### PR DESCRIPTION
**Pull request by edenstrom**
## ☕️ Reasoning

I saw that .getSetCookie were finally supported in the edge runtime when deployed to Vercel. This uses `getSetCookie` if supported, otherwise falls back to `.get('set-cookie)`

Deployed a version with this patch here:

Reproduction deployment: [next-auth-error-vercel.vercel.app](https://next-auth-error-vercel.vercel.app/)
Reproduction repo: [edenstrom/next-auth-error-vercel](https://github.com/edenstrom/next-auth-error-vercel)

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

This solves the long standing issue were chunked cookies didn't work when using the edge runtime deployed to Vercel.

https://github.com/nextauthjs/next-auth/pull/7443#issuecomment-1677261203

Related issues:
- https://github.com/vercel/edge-runtime/issues/536
- https://github.com/sidebase/nuxt-auth/issues/293

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by viktorlarsson — APPROVED** [review]

**Comment by edenstrom** [comment]
Closed due to not currently working.. Fixing.

**Comment by cipriancaba** [comment]
hey @edenstrom are you still working on a fix for this?

**Comment by edenstrom** [comment]
> hey @edenstrom are you still working on a fix for this?

Yes, reopened PR with fix. :)

Works here. https://next-auth-error-vercel.vercel.app/

**Comment by cipriancaba** [comment]
You're a lifesaver 🔥

**Comment by viktorlarsson** [comment]
Could we get this merged?

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
