### PR TITLE
feat(provider): add Salesforce provider

### PR DESCRIPTION
**Pull request by mmahalwy**
**What**:
Added Salesforce as a provider

**Why**:
Was missing

**How**:
Added additional file

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Hi there, and thanks for the PR! There are some unnecessary line changes (not related to the PR), could you revert those? Otherwise it looks good!

**Review by nyedidikeke — CHANGES_REQUESTED** [review]
@mmahalwy You may want to execute ```npm run lint:fix``` to address failing checks.

**Comment by balazsorban44** [comment]
I can also recommend using

https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs

if you use VSCode. Can fix lint issues while saving. :)

**Comment by mmahalwy** [comment]
@balazsorban44 addressed concerns! LMK

**Comment by balazsorban44** [comment]
Thanks! Could you also add it here: https://www.github.com/nextauthjs/next-auth/tree/canary/www%2Fproviders.json

**Pull request merged**
