### PR TITLE
(feat) Provider: Whop

### PR DESCRIPTION
**Pull request by denisulit**
## ☕️ Reasoning
Whop is an online platform where users can buy digital goods and services like Notion templates, Discord communities, web apps, and more - our goal is to make the process of buying digital products easier, faster, and more secure for everyone. By adding Whop's API to Auth.js, it will allow our users to integrate our API into their Next.js-based products in a seamless manner.

### CODE REVIEW

**Comment by JedPattersonn** [comment]
@ThangHuuVu @linyiru @ndom91 any update on this?

**Comment by stevo2105** [comment]
Thank you @JedPattersonn lets get this in!

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Please revert all unnecessary changes and fix merge conflicts.

This should be at most a 2-3 changed files PR.

**Comment by denisulit** [comment]
@balazsorban44 can you pull in main with rebase=false?

**Comment by stevo2105** [comment]
@denisulit this is a crazy PR that needs to be WAY slimmed down. Please close this and I will open another

**Pull request closed without merging**
