### PR TITLE
add: NextAuth.js with TypeScript tutorial

### PR DESCRIPTION
**Pull request by ixartz**
**What**:

Add a new tutorial for NextAuth.js with Typescript

**Why**:

There isn't a complete guide for NextAuth.js in TypeScript

**How**:

Add a new link in tutorial section of NextAuth.js website

**Checklist**:

- [x] Documentation
- [ ] Tests N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
Hi there, and thanks for the PR! We recently added a section to the documentation about TypeScript, you can check this out here: https://next-auth-git-canary.nextauthjs.vercel.app/getting-started/typescript

I had a look at the tutorial you linked, and unfortunately I don't think it brings more value then the provided documentation page. It doesn't feel like it concentrates very much on adding/supporting/using TS as it simply shows a case how to set NextAuth.js up.

If you have more ideas on how to help folks with TS, maybe you could try incorporating it into this page?:

**Comment by ixartz** [comment]
Hi @balazsorban44, thank you for your quick feedbacks and maintaining this project.

I feel the currently documentation isn't TypeScript friendly. I didn't know there is now TypeScript section in Canary branch and you are currently adding information in the documentation about TypeScript.

For your information, adding `@types/next-auth` in your dependencies isn't really enough. I've lost some time to convert the code provided by the documentation to TypeScript. You need to add the correct type to `[...nextauth].ts`, `index.tsx` and `_app.tsx`: add types for your Next and NextAuth props.

To find the right type, I've used Prisma GitHub code, Next JS and NextAuth documentation. The idea of the blog post was to put everything at the same place with a working and tested version in TypeScript.

**Comment by balazsorban44** [comment]
Thank you! 🙂

Apart from the added `InitOptions` in the `[...nextauth].ts` file, I see nothing next-auth TS related in the blog, but please prove me wrong.

If you feel that particular thing is important to you, feel free to open a PR adding it to the TS support page. Although you may be interested in the new way of initializing NextAuth in canary:

```js
export default NextAuth({
  providers: [
    Providers.GitHub({
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET
    })
  ]
})
```

it's simpler, and requires no adding types manually. Although I'm not aware that `@types/next-auth` has been updated yet to support this.

**Comment by ixartz** [comment]
Too bad for me, I've tried and needed NextAuth.js too early. It could save me time to see there is now a new initializing version for the documentation.
I confirm it should need less type and the canary version also fixes `() => signOut()`. Before, there was a typing error with signOut. There is another change but it's more related to Next JS, also a small change.

Yes, with the canary version, it resolves everything. I didn't expect there is a canary version. Too sad, this canary version wasn't released yet, it could save me time in searching and writing.

**Comment by balazsorban44** [comment]
The canary version is available already, you can download it with `npm i next-auth@canary` 😉

**Comment by ixartz** [comment]
Ok thank you for the advice.

When I say release I mean on https://next-auth.js.org website and on the stable version. Currently, https://next-auth.js.org is still using the old version, right?

Should I use the stable version or the canary version for production environment? Currently, when I do `npm install next-auth`, it still install 3.1.0 version.

**Comment by balazsorban44** [comment]
You can find a banner on the website on the top that sends you to this page for the canary documentation

https://next-auth-git-canary.nextauthjs.vercel.app/


Canary by definition can contain bugs, so you should use the stable version in production.

**Pull request closed without merging**
