### PR TITLE
fix: update protection to accept array with multiples options

### PR DESCRIPTION
**Pull request by viniciuscr**
**What**:
Add new protection value: "both", to use both handlers (state and pkce).

**Why**:
Some provider require the state param when using the pkce protection as reported on this issues:
https://github.com/nextauthjs/next-auth/issues/1530
https://github.com/nextauthjs/next-auth/issues/1367

**How**:
Just editing the handlers validations to handle in case of "both" is set on protection.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      
It's note ready, actually its more a suggestion than a PR.

Note: I called it both, but it could have other names, such as: pkce-state or pkce-with-state

### CODE REVIEW

**Comment by balazsorban44** [comment]
I have been thinking about this, and I am curious what do you think if we implement it such that protection could take an array as well? so `protection: ["pkce", "state"]` so it's room for the future.

In any way, have you tried/verified that this resolves your Okta problem?

**Comment by viniciuscr** [comment]
Any update here?
I see more people are getting stuck with the same problem and I kind of need it to use next-auth, otherwise I will have to jump to the okta sdk.

**Comment by balazsorban44** [comment]
Sorry if I haven't been explicit about it, but if you could change the implementation to be able to provide an array instead of `"both"` for `protection` to have more room for the future, I could proceed to merge this.

**Comment by viniciuscr** [comment]
> Sorry if I haven't been explicit about it, but if you could change the implementation to be able to provide an array instead of `"both"` for `protection` to have more room for the future, I could proceed to merge this.

No worries, it was an easy change.
Now it accepts an array but also keeps compatibility with string.

**Comment by LuisValgoi** [comment]
Looks good to me

**Review by LuisValgoi — APPROVED** [review]

**Comment by viniciuscr** [comment]
@iaincollins @balazsorban44 
any advance to merge this PR?

**Review by balazsorban44 — APPROVED** [review]
Thanks for your patience! I finally had the chance to check this out locally, and it seems to work nicely! Tested with Auth0.

**Pull request merged**
