### PR TITLE
Re-enable ability for the token request to be overriden completely

### PR DESCRIPTION
**Pull request by PaulWild**
## ☕️ Reasoning

When dealing with a custom oauth provider that has a non compliant token endpoint this functionality allows this library to be used. This functionality was present in v4 of the library. 

In v5 this has been removed. A conform endpoint has been added for internal use to manipulate the response from token endpoints. However this does help if the request does not conform exactly to the standard. 

As an example the company I work for requires some extra parameters to be sent in the token request (including the state parameter) Other than that the solution is oauth compliant. It would be a shame if we couldn't use v5 because of this restraint.

Another example I can see in the v5 branch is the tiktok provider which I assume is currently broken by its requirement to have a custom token request. 

This PR implements the existing type contract that was carried over from the v4 branch but not implemented.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

There are quite a few issues and comments about not being able to control the request endpoint

https://github.com/nextauthjs/next-auth/issues/10852
https://github.com/nextauthjs/next-auth/issues/10732
https://github.com/nextauthjs/next-auth/discussions/10829

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
We might re-introduce something here, but it won't be the old format, it's too loose. Rather than patching up non-spec providers, we want to push them for correct implementation as much as possible.

We already have a [`conform` API](https://github.com/nextauthjs/next-auth/blob/38c5ee47b70f81d792fdde567599c7ad039a8975/packages/core/src/lib/actions/callback/oauth/callback.ts#L128) to correct the code grant responses, I want to go with a similar API for other cases as well.

I want to keep the TS type `@internal` to avoid relying on patching non-spec implementations too much.

In my experience, if we make it too easy to opt-out of conformance, we will keep maintaining legacy/broken providers.

**Comment by PaulWild** [comment]
Thanks for the reply, I completely understand the rational and from the discussions being had in the issues linked it is not unexpected.

From a selfish perspective I think my works provider wont change any time soon so if there is room for some customization of the code grant request that would be fantastic.  I am more than happy to contribute towards a more acceptable solution if you have one in mind? Perhaps the ability to supply extra parameters to the request (with access to properties like state)?

**Comment by milo-** [comment]
@balazsorban44 We really need some way to override this token method. 

We work with multiple vendors who are not going to change their non token APIs so we can use the latest version of Auth.js. This was not an issue with v4, but we are unable to use v5 with them as as we cannot override the token requests.

**Comment by cmayoracurzio** [comment]
Adding to this discussion a use case that requires overriding the default `token.request`, and for which the provider is **within** the OAuth 2.0 specification:
- Wordpress OAuth requires sending the client credentials (`client_id` and `client_secret`) [in the request-body](https://developer.wordpress.com/docs/oauth2/#3-server-code-authentication).
- [RFC 6749, section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) mentions that this is allowed (even if not recommended).
- However, the default `token.request` behavior only uses the Basic Authorization header scheme.

Note: The V5 `next-auth` WordpressProvider would anyways ignore a custom `token.request` because the merging approach for default and custom options is still in-progress. Although this is a different issue, I mention it here in case someone decides to test Wordpress OAuth using this built-in provider (use a custom one instead).

**Comment by philwolstenholme** [comment]
I'm in the same boat, we have a provider managed by a separate team at work and the way things are set up there means we need to modify the token request. The separate team manage a whole hunch of different things and so are busy and unlikely to prioritise changing the provider just because of us. 

We'd like to use the latest NextAuth but can't without having this extra bit of control.

**Comment by dpashk-figma** [comment]
+1. A number of big providers don't comply with the spec, and there's not much you can do to make them comply. Breaking compatibility with them only hurts developers using your library.

**Comment by DewinU** [comment]
There's ways to use the new conform function for the providers that do not comply with the spec, like tiktok for example, but it requires to make another  or more requests after  NextAuth tries its owns, here is a code reference
```ts
let tkCode: string | undefined;
let tkCallback: string | undefined;
export const { handlers, auth, signIn, signOut } = NextAuth(req =>{
  if (req?.method === 'GET' && req?.headers.get('referer')?.includes('tiktok')) {
    const url = new URL(req?.url);
    tkCode = url.searchParams.get('code') as string;
    tkCallback = url.pathname
  }
  return {
    theme: { logo: "https://authjs.dev/img/logo-sm.png" },
    adapter: UnstorageAdapter(storage),
    providers: [
      GitHub,
      TikTok({
        clientId: process.env.AUTH_TIKTOK_KEY,
        clientSecret: process.env.AUTH_TIKTOK_SECRET,
        token: {
          async conform(response: Response) {
            const res = await fetch(response.url, {
              method: 'POST',
              headers: {
                'Cache-Control': 'no-cache',
                'Content-Type': 'application/x-www-form-urlencoded',
              },
              body: new URLSearchParams({
                client_key: process.env.AUTH_TIKTOK_KEY!,
                client_secret: process.env.AUTH_TIKTOK_SECRET!,
                code: tkCode!,
                grant_type: 'authorization_code',
                redirect_uri: process.env.AUTH_URL! + tkCallback ,
              }),
            });
            return res;
          },
        }
      })
    ],
    basePath: "/auth",
    callbacks: {
      authorized({ request, auth }) {
        const { pathname } = request.nextUrl
        if (pathname === "/middleware-example") return !!auth
        return true
      },
      jwt({ token, trigger, session, account }) {
        if (trigger === "update") token.name = session.user.name
        if (account?.provider === "keycloak") {
          return { ...token, accessToken: account.access_token }
        }
        return token
      },
      async session({ session, token }) {
        if (token?.accessToken) {
          session.accessToken = token.accessToken
        }
        return session
      },
    },
    experimental: {
      enableWebAuthn: true,
    },
    debug: process.env.NODE_ENV !== "production" ? true : false,
  } satisfies NextAuthConfig
})
```

**Comment by PaulWild** [comment]
I closed this as the response was that this wasn't the approach that would be taken for this issue, which is totally understandable. 

However there is enough discussion going on that I am going to reopen it, so it gets a bit more visibility to encourage said discussion .

**Comment by emulienfou** [comment]
Released a temporary package to add back this feature with latest release of package `@auth/core:0.35.1`:

https://www.npmjs.com/package/@emulienfou/auth-core

> Thanks to @PaulWild

**Comment by DewinU** [comment]
Seems we have a solution, haven't tested it out yet tho

#11978

**Comment by balazsorban44** [comment]
Superseded by https://github.com/nextauthjs/next-auth/pull/11975

This adds the ability to override any of the requests now. Use it sparingly!

Example usage, to conform the Microsoft Entra ID provider that returns the wrong `issuer`: https://github.com/nextauthjs/next-auth/pull/11980

**Pull request closed without merging**
