### PR TITLE
docs(provider): added example for logging out of cognito

### PR DESCRIPTION
**Pull request by phuwin**
## ☕️ Reasoning

Added a tip for logging out in Cognito

When only signOut is used, cognito isn't logged out completely. Meaning the user will still logged in after hitting signin in again without being able to input another username and password.

## 🧢 Checklist

- [x] Documentation
- [x] Ready to be merged

## 🎫 Affected issues

related to #836 and #946

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
This is called federated logout, and I think we should have a dedicated page explaining how it works, instead of having this example only for a single provider.

See also https://github.com/nextauthjs/next-auth/issues/836

**Comment by ndom91** [comment]
Thanks for your interest in the project! We've made some major changes to the organisation of the docs subdirectory in the last days. Can you update your change to be made against the following file now? (`docs/docs/reference/04-oauth-providers/cognito.md`)

Then I can get it merged! Thanks :pray:

**Review by half2me — APPROVED** [review]
Thanks so much for this. I've been having this exact problem!

**Comment by ThangHuuVu** [comment]
Closing for inactivity.

**Pull request closed without merging**
