### PR TITLE
chore(docs): add carbon ads to docs sidebar

### PR DESCRIPTION
**Pull request by ndom91**
## Reasoning 💡

Adding [CarbonAds](https://www.carbonads.net/) to the docs page. 

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ndom91** [comment]
Alright so the initial setup is complete. 

**(A)** The default setup looks like this:

image

What do yall think?

**(B)** I'm thinking about bumping it down a bit with a `margin-top`, something like this maybe:

image

**(C)** Orrrr with flex-box pin the ad to the bottom of the screen :thinking: 

image

I'm open to whichever, let me know what yall think (A, B, C).

@balazsorban44 @ThangHuuVu @lluia

**Comment by ThangHuuVu** [comment]
I dig the (A) and (B) options 👍 would it be a problem if the ads are not visible by default in the mobile view since they're in the sidebar?

**Comment by lluia** [comment]
**(B)** version looks the more clean to me 💅🏽 ; similar question as @ThangHuuVu about ads being in the sidebar.

**Comment by ndom91** [comment]
Thanks for the quick responses guys! So according to them, they only need to `The ad should be visible above-the-fold (upper 800 pixels) for desktop browser.` So on mobile, being in the sidebar should be fine. In fact i'll test that and potentially hide it completely on mobile if it breaks the slide out navbar in docusaurus. 

I like **B** as well, lets go with that then!

**Comment by ndom91** [comment]
I had to deactivate so much ad-blocking extensions and config and whitelist domains on my pihole for this PR :joy: :joy:

**Pull request merged**
