### PR TITLE
feat(provider): Add option to generate email verification token

### PR DESCRIPTION
**Pull request by firede**
see #537

### CODE REVIEW

**Comment by firede** [comment]
@iaincollins 
I added `generateVerificationToken`, and used it in my project via `patch-package`. It runs as expected!

## Details

`./patches/next-auth+3.1.0.patch`

<details>

```js
diff --git a/node_modules/next-auth/dist/providers/email.js b/node_modules/next-auth/dist/providers/email.js
index a8344b3..3b603a9 100644
--- a/node_modules/next-auth/dist/providers/email.js
+++ b/node_modules/next-auth/dist/providers/email.js
@@ -5,6 +5,8 @@ Object.defineProperty(exports, "__esModule", {
 });
 exports.default = void 0;
 
+var _crypto = require("crypto");
+
 var _nodemailer = _interopRequireDefault(require("nodemailer"));
 
 var _logger = _interopRequireDefault(require("../lib/logger"));
@@ -32,12 +34,15 @@ var _default = options => {
     },
     from: 'NextAuth <no-reply@example.com>',
     maxAge: 24 * 60 * 60,
+    generateVerificationToken,
     sendVerificationRequest
   }, options);
 };
 
 exports.default = _default;
 
+var generateVerificationToken = () => (0, _crypto.randomBytes)(32).toString('hex');
+
 var sendVerificationRequest = (_ref) => {
   var {
     identifier: email,
diff --git a/node_modules/next-auth/dist/server/lib/signin/email.js b/node_modules/next-auth/dist/server/lib/signin/email.js
index 6441be0..ded8493 100644
--- a/node_modules/next-auth/dist/server/lib/signin/email.js
+++ b/node_modules/next-auth/dist/server/lib/signin/email.js
@@ -5,8 +5,6 @@ Object.defineProperty(exports, "__esModule", {
 });
 exports.default = void 0;
 
-var _crypto = require("crypto");
-
 function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }
 
 function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }
@@ -23,7 +21,7 @@ var _default = function () {
         createVerificationRequest
       } = yield adapter.getAdapter(options);
       var secret = provider.secret || options.secret;
-      var token = (0, _crypto.randomBytes)(32).toString('hex');
+      var token = provider.generateVerificationToken();
       var url = "".concat(baseUrl).concat(basePath, "/callback/").concat(encodeURIComponent(provider.id), "?email=").concat(encodeURIComponent(email), "&token=").concat(encodeURIComponent(token));
       yield createVerificationRequest(email, url, token, secret, provider, options);
       return Promise.resolve();
```

</details>

`./api/auth/[...nextauth].js`

```js
import gpw from "node-gpw"

const generateVerificationToken = () => `${gpw(8)}-${gpw(8)}`

const options = {
  providers: [
    Providers.Email({
      generateVerificationToken,
      // ...
    }),
  ],
}
```
Email:



## Issue

I found some issues about interaction. Still take Notion as an example:



I hope to adopt a similar verification process in my project, but the current **Client API** cannot be easily implemented.

IMO, we can:
1. add parameters to `signIn()`/`signOut()`, handle CSRF Tokens and return the status(json), without redirect to callback url.
2. add `verification-token` API to return whether the verification token is right.

**Comment by iaincollins** [comment]
Just updated to put on hold for a little bit (along with other pull requests) while we get the automated testing and release process updated, but this pull requests looks great and looking forward to getting it rolled out!

Happy to help take it further with the built-in pages to add support for this to them, and to add methods to the client API to make it easy to verify tokens (as suggested).

**Comment by josh-padnick** [comment]
+1 to this excellent feature. It gives you a password-like login experience without actually using passwords.

**Comment by gamedevsam** [comment]
We're 2 months in, any updates with the automated testing?

**Comment by abusaidm** [comment]
With automated tests and deployment done, is there anything this PR needs to be merged?

**Review by abusaidm — APPROVED** [review]

**Comment by balazsorban44** [comment]
Hi there @firede could you please resolve the merge conflicts and update your branch to be based on the latest `canary` please? 🙂

**Pull request merged**
