### PR TITLE
Store user ID in sub claim of default JWT

### PR DESCRIPTION
**Pull request by lukel97**
This allows us to check if the user is signed in when using JWTs
Part of #625, not sure if this is enough to close that entire issue though

### CODE REVIEW

**Comment by iaincollins** [comment]
Thanks @bubba!

I think this is a good direction and want to take the time to test it out with different options (and maybe write some tests for it).

**Comment by sughodke** [comment]
> Thanks @bubba!
> 
> I think this is a good direction and want to take the time to test it out with different options (and maybe write some tests for it).

@iaincollins would you be averse to creating a "bleeding-edge" branch while these tests are being written? This way useful PRs like this one get merged and tested out without affecting "stable."

**Comment by bubba** [comment]
@sughodke I've uploaded a fork of this package that contains this change here on GitHub packages: https://github.com/nuvest/next-auth/packages/510172 
You'll need to add the GitHub package registry to npm but other than that it should be public

**Comment by balazsorban44** [comment]
@iaincollins as we now have a "bleeding-edge" branch (canary), could this be merged? I'm not entirely sure if the changes are breaking or not.

**Comment by iaincollins** [comment]
> @iaincollins as we now have a "bleeding-edge" branch (canary), could this be merged? I'm not entirely sure if the changes are breaking or not.

I think this is good to go :D

**Pull request merged**
