### PR TITLE
chore(firebase-adapter): update `firebase-admin` peer-dep to 12.0.0+

### PR DESCRIPTION
**Pull request by tomas-mikula**
## ☕️ Reasoning

There is a dependency resolution issue when trying to use `@auth/firebase-adapter` alongside `firebase-admin`.
Specifically `"@auth/firebase-adapter": "^2.4.1"` doesn't seem to support firebase-admin version 12 such as `"firebase-admin": "^12.2.0"`

Issue:
Screenshot 2024-06-30 at 22 18 45

`firebase-adapter` peerDependencies and devDependancies of `firebase-admin` were update to v12. 

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues
None

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by tomas-mikula** [comment]
@ndom91 @balazsorban44 any chance you had time to take a look?

**Comment by ndom91** [comment]
@thomas-desmond can change this peer dependency limit to something like `>= 12`, in order to allow any `12.x` version? 

Also you don't have to manually bump the version of the `@auth/firebase-adapter` package, that'll happen automatically in the CI release job :pray:

**Comment by jacekplocharczyk** [comment]
Hey folks, any updates on this? I had hard time playing with the example repo and firebase adapter (tldr; it doesn't work) and fixing this would be really helpful
Thanks!

**Comment by tomas-mikula** [comment]
@ndom91 is it now considered ready? Or do we wait for someone specific?

**Review by ndom91 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
