### PR TITLE
Do not stop on nonfatal xwwwauthenticate headers

### PR DESCRIPTION
**Pull request by feynmanliang**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

The presence of XWWWAuthenticate headers are harmless; we should just log a warning instead of failing.

This unblocks OIDC with FusionAuth.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ThangHuuVu — COMMENTED** [review]
Thanks for sending the PR! Although I don't think we should just log the warning here. The presence of the `WWW-Authenticate` header indicates that the client needs to perform additional authentication specified in the scheme to get the resource since the response of the Authorization server will be 401 if I understand correctly.

What issue are you running into, what's the response you're getting that contain the `WWW-Authenticate` header? Could you open an issue and link it here first?

**Comment by ThangHuuVu** [comment]
Closing for inactivity. For anyone who is still interested, [lease open an issue first with proper reproduction so that we can discuss it before reopening the PR 🙏

**Comment by rakanus** [comment]
CleanShot 2023-09-04 at 21 08 47

Do you have any idea when this issue will be resolved?

 I'm having trouble getting FusionAuth to work with OAuth or OIDC.

**Comment by rakanus** [comment]
I think it would be great if we could reopen this PR, or at least keep working on the TODO for handling www-authenticate challenges.

**Comment by feynmanliang** [comment]
@rakanus this is the same thing I encountered; this PR resolves it on the surface but I do not have the bandwidth to handle it properly

**Pull request closed without merging**
