### PR TITLE
bring duende-identitysever6 docs into docs v4

### PR DESCRIPTION
**Pull request by dbfr3qs**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](../Security.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

It looks like the Duende IdentityServer6 documentation was added to v3 of the docs in [this PR](https://github.com/nextauthjs/next-auth/pull/4850) but doesn't look to have been included in v4 of the docs. This simply adds the file back into the main doc directory so it's included in the build.

image

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
Nice catch! Can you add it also to the `versioned_docs/version-beta/oauth-providers/` directory? We plan on merging those beta docs as main docs soon.

Thanks :pray:

**Comment by dbfr3qs** [comment]
> Nice catch! Can you add it also to the `versioned_docs/version-beta/oauth-providers/` directory? We plan on merging those beta docs as main docs soon.
> 
> Thanks 🙏

No worries - that is done 👍

**Comment by ndom91** [comment]
Alright so to ask for antoher switcheroo haha, but the previous `version-beta` docs have been moved to the main docs now, meaning there are no more `versioned_docs/**` directories/files anymore.

Only the change to the main `/docs/docs/` page is required now. Could you update it one more time and we'll get it merged? :pray:

**Comment by dbfr3qs** [comment]
> Alright so, I'm sorry to ask for antoher switcheroo haha, but the previous `version-beta` docs have been moved to the main docs now, meaning there are no more `versioned_docs/**` directories/files anymore.
> 
> Only the change to the main `/docs/docs/` page is required now. Could you update it one more time and we'll get it merged? 🙏

No worries - all done 👍

**Comment by dbfr3qs** [comment]
@ndom91 is this still required? Just wondering if I should resync with the base branch...

**Comment by ThangHuuVu** [comment]
hi @dbfr3qs , this shouldn't be necessary anymore, checkout our latest doc at https://authjs.dev/reference/core/providers_duende-identity-server6

Thanks for the PR though! 🙏

**Pull request closed without merging**
