### PR TITLE
feat(providers): add Mailgun email provider

### PR DESCRIPTION
**Pull request by Aylur**
## ☕️ Reasoning

We use [Mailgun.com](https://www.mailgun.com/) at our company and I wanted to contribute upstream.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
@Aylur thanks for the interest! This is looking pretty good already, but we'd also love it if you could add Mailgun to the https://authjs.dev/getting-started/authentication/email page. 

The file `docs/pages/getting-started/authentication/email.mdx` just needs an additional `Mailgun Setup` section / tab to select. You can just copy one of the existing ones to get started

**Review by ndom91 — APPROVED** [review]
Awesome, thanks for the quick turnaround!

**Comment by ndom91** [comment]
One last thing, looks like there's some formatting issues in these [three files](https://github.com/nextauthjs/next-auth/actions/runs/10743527403/job/29798446906?pr=11723):

- `docs/pages/getting-started/providers/mailgun.mdx`
- `docs/pages/getting-started/session-management/get-session.mdx`
- `packages/core/src/providers/mailgun.ts`

**Comment by lukjaki** [comment]
I've found mailgun in documentation but I can't find code for it. What is the actual status of mailgun integration?

**Comment by ndom91** [comment]
> I've found mailgun in documentation but I can't find code for it. What is the actual status of mailgun integration?

Can you not import the mailgun provider like in the docs? For example 


``` 
import Mailgun from 'next-auth/providers/mailgun' 
```

**Pull request merged**
