### PR TITLE
fix(docs): update type import in typescript.md

### PR DESCRIPTION
**Pull request by FrankTrog**
While attempting to utilize this page in a local version of Auth.js the recommended code failed to augment the module properly. It seems the reference to @auth/core module doesn't properly augment it.

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by nolykhemin** [comment]
this works, thanks

**Comment by mr-josh** [comment]
Is this related to #9377? I notice the change reverts the deceleration to "next-auth" but I think @Huijiro found the correct module (`@auth/core/types`).

**Comment by ndom91** [comment]
Closing this PR, the correct import is from `@auth/core/types`👍

**Comment by mr-josh** [comment]
@ndom91 is there a PR to correct the docs from `@auth/core` to `@auth/core/types`? I can spin up a fork real quick and patch if not.

Also Merry Christmas to all that celebrate!

**Comment by Huijiro** [comment]
> @ndom91 is there a PR to correct the docs from `@auth/core` to `@auth/core/types`? I can spin up a fork real quick and patch if not.
> 
> Also Merry Christmas to all that celebrate!

I was about to try to do it as soon as i arrive home to say i did something in open source for once.

**Comment by Huijiro** [comment]
@mr-josh Done in #9462.

**Pull request closed without merging**
