### PR TITLE
Export cookie server lib

### PR DESCRIPTION
**Pull request by olragon**
## Reasoning 💡

Export server/lib/cookie so app can use next-auth's default cookies & set cookie

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## Affected issues 🎟

None

### CODE REVIEW

**Comment by balazsorban44** [comment]
Could you please elaborate where and how you would use this?

**Comment by olragon** [comment]
> Could you please elaborate where and how you would use this?

My app (web, react-native) using Auth's API exposed by [trpc.io](https://trpc.io/), these API include `signup`, `signin` with credentials, `resetPassword` ...
Auth's API executed successfully should include the` next-auth.session-token` cookie.  Without `next-auth/dist/server/lib/cookie` exposed, the code must be duplicated, updated & tested with every new next-auth's version.

**Comment by balazsorban44** [comment]
You should not test our library though, you could simply mock it out. These are internal settings and are not meant to be exposed. I don't feel that your use case justifies this change. If you disagree, please open a feature request issue with a detailed explanation, and let's see if others are interested.

**Comment by olragon** [comment]
@balazsorban44 I do not test next-auth library, I am using next-auth's cookie as a part of my code.

Let's imagine that I have an API at `/api/custom-auth/signin`:

- client post email & password to `/api/custom-auth/signin`
- server check for email & password valid
  - if email & password valid, server responds with
    - header: Cookie: next-auth.session-token=[JWT]
    - body: { publicUser: { id: 1, email: "1@gmail.com" } }

image

**Comment by balazsorban44** [comment]
You should in any case **NOT** modify our cookie from your codebase. This is something I'm pretty sure we don't want people to do.

**Comment by balazsorban44** [comment]
If I understand the publicUser function anyway, I thin kyou want to check out the jwt and session callbacks:

https://next-auth.js.org/configuration/callbacks

**Pull request closed without merging**
