### PR TITLE
WIP: Docs - Provider Vercel-style Marquee Section

### PR DESCRIPTION
**Pull request by ndom91**
Added a Vercel style provider marquee on the homepage. Wasn't sure if it looked best in its own section, or maybe floating behind another section, but I think this doesn't look too bad.

### CODE REVIEW

**Comment by ndom91** [comment]
Damn, I'm not sure why its failing to build at vercel, but it works locally and looks like this:

image

With the individual nodes bumping around and floating across the page like vercel has with the country flags on their homepage.

**Comment by ndom91** [comment]
Okay finally, working on vercel as well :)

**Comment by iaincollins** [comment]
Thank you, I really like the style of this!

Sorry about not being able to share access to logs on Vercel, we would need a team on there for that :-(

Have checked out the branch and just faffing about with a bit of padding if you don't mind! Going to see if I can address an issue with it clipping some of the bubbles (have an idea about that...)

**Comment by ndom91** [comment]
Yeah no problem, go for it! Im glad you like it too. 

Regarding the Vercel team, maybe they can give us team access since we're an opensource project that is designed for their framework anyway ;)

**Comment by Fumler** [comment]
Noticed the auth0 icon isn't centered, and should possibly have a white icon for Github and Apple when using dark theme.

image

**Comment by iaincollins** [comment]
@Fumler Thanks for feedback!

@ndom91 I had some cosmetic issues I couldn't resolve, but seems best to merge it in to the v3 branch with the other open PR's before it goes stale! I figure worse case we can always comment them out if we can't get it working, but it would great to get the icons in now and seeing if we can wrangle it. Hope this is okay!

**Comment by ndom91** [comment]
Yeah for sure! I'll take another look at it as well and see if I can get the icons looking just right.

**Comment by ndom91** [comment]
Fixed the Apple / Github Icons being black in dark mode as well as the Auth0 misaligned icon :+1:

**Pull request merged**
