### PR TITLE
Fixing missing comma and typescript proper support

### PR DESCRIPTION
**Pull request by falleco**
Hello!

I am using this library for a while now, never had any problems with it, but recently I started to migrate my codebase to typescript and realized that the typings that were added here doesn't provide enough info to be used in a typescript project.

This PR changes:
- I fixed a missing comma at index.js...
- Rewrote the index.d.ts and client.d.ts so that the already existing types would be used outside the project, also there were some missing information/invalid types there
- Provided an example in typescript, that also worked as a test to the changes. Basically, it is the example repository in ts

Since I am no a typescript pro, I did only enough to compile/execute my project (and the example) with correct typing. If you see any problem with the PR I would be glad to make the necessary changes and resubmit.

### CODE REVIEW

**Comment by NickBolles** [comment]
@falleco awesome! I can look at this. The question is when. I'm hoping this weekend. I also have some enhancements that I've made to my local types. So might suggest some enhancements too.

**Comment by falleco** [comment]
Answered in #26 ... Are you talking about the CSRF config, right, @kret13 ?

Hey, @NickBolles Could you take a look at the code?

**Comment by lukrai** [comment]
When is it going to be merged? Current types do not work properly in the project, this would really improve the development with typescript.

**Comment by lukrai** [comment]
@NickBolles @iaincollins up

**Comment by dmitriyK1** [comment]
@iaincollins up

**Comment by NickBolles** [comment]
This looks fine to me. I haven't tested it, but it looks fine. I can't merge it though so will need to wait for @iaincollins

**Comment by iaincollins** [comment]
This is really appreciated thank you.

I'm sorry I left this for so long, I feel really bad about that.

I sort of let things go stale a bit while I waited for serverless in Next.js 8 and Next.js 9 to shake out and settle down (and for new features to drop that will make things easier so I don't have to refactor twice).

I just merged in a couple of very simple small PRs and will get to this one soon.

**Comment by iaincollins** [comment]
Hey folks,

Because it's taken me so long to get round to [version 2.0](#99), which is dropping soon (and us a re-write for serverless) it doesn't make sense to a straight merge any more BUT I am going to keep this PR open as a reminder to try and re-integrate the relevant parts for 2.x.

Some of this will be useful for sure!

I could actually do with help with improving TypeScript support for the new version.

If anyone is up for that please tag yourself below! :-)

**Comment by lluia** [comment]
@iaincollins I'm happy to help with this or even pick it up. I'm trying to set-up [a small Next App in TS](https://github.com/lluia/hip-hub) using **Next Auth** that reads from the [Github API](https://developer.github.com/v4/). 

I have not much experience writing large declaration files but I have been working in TS for a while and happy to give it a try 👍🏻

**Comment by LoriKarikari** [comment]
> @iaincollins I'm happy to help with this or even pick it up. I'm trying to set-up [a small Next App in TS](https://github.com/lluia/hip-hub) using **Next Auth** that reads from the [Github API](https://developer.github.com/v4/).
> 
> I have not much experience writing large declaration files but I have been working in TS for a while and happy to give it a try 👍🏻

TypeScript support would be awesome. Maybe you can create a new issue for it so it's easier to keep track of what's being worked on.

**Comment by lluia** [comment]
@LoriKarikari probably we can use #47 to keep track given it's already open 👌🏼

**Comment by LoriKarikari** [comment]
@lluia oh yeah my bad. I missed that issue somehow.

**Comment by TwoAbove** [comment]
Hi! 

Any chance you can add types to the package? It's super helpful!

**Comment by lluia** [comment]
@TwoAbove yup, I'll try either today or tomorrow 🤙🏼

**Comment by iaincollins** [comment]
I'm going to close this as #220 is the new spiritual successor to this PR.

Thanks again to @falleco for raising it. As version 2 is a total rewrite (and version 1 is unsupported) we can't merge it in, but I'm going to still be referencing it.

**Pull request closed without merging**
