### PR TITLE
feat(provider): option to disable client-side redirects (credentials)

### LINKED ISSUE #989: Is it possible to avoid page reloading when using custom credentials?
**Your question**
Is it possible to avoid page reloading when using custom credentials? (like an SPA behaviour)

**What are you trying to do**
I'm using custom credentials because I'm using a customer's database which has its own api, and I've designed my own login page. When I hit login after entering credentials, I handle the authentication with my cusotmer's api inside the [...nextauth].js file. When authentication happens, the page goes to whichever page I've specified in the callback.

However, I would prefer to show a "loading" component and wait until authentication happens, listening the session inside a useEffect, for example. Once the session variable has data, I would then handle the logic without seing a reload on the page.

**Reproduction**
Implement the custom login page in the documentation and watch the redirect after hitting Sign In:
import React from 'react';
import { csrfToken } from 'next-auth/client';

export default function SignIn({ csrfToken }) {
  return (
    <form method='post' action='/api/auth/callback/credentials'>
      <input name='csrfToken' type='hidden' defaultValue={csrfToken} />
      <label>
        Username
        <input name='username' type='text' />
      </label>
      <label>
        Password
        <input name='password' type='text' />
      </label>
      <button type='submit'>Sign in</button>
    </form>
  );
}

SignIn.getInitialProps = async (context) => {
  return {
    csrfToken: await csrfToken(context),
  };
};

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

### PR DESCRIPTION
**Pull request by balazsorban44**
**What**:

In case the user is using the [Credentials](https://next-auth.js.org/providers/credentials) provider, make it possible to disable the redirection after the response from the server.

It also utilizes `URLSearchParams` to encode the body of `POST` requests, as Next.js will polyfill it for us.

Certain status codes were added to errors on the server-side to provide the user with more information about the error.

**Why**:
Example: In case the sign-in flow breaks because the user has given the wrong credentials, it may be desirable to handle it without a page reload.

**How**:

A new option has been added to the `signIn` and `signOut` client-side functions.

**Sign in**
> NOTE: The `redirect` option will do nothing unless you set the provider to `"credentials"`.

To preserve backward compatibility, the default will be to always redirect, so in theory, setting `{redirect: true}` statically won't be necessary.
```ts
interface SignInResponse {
  /** The reason for why the login process has stopped */
  error: string | null
  /** @see https://developer.mozilla.org/en-US/docs/Web/API/Response/status */
  status: number
  /** @see https://developer.mozilla.org/en-US/docs/Web/API/Response/ok */
  ok: boolean
}

const response: SignInResponse = await signIn("credentials", { redirect: false })
```
**Signout**
Provider agnostic setting. This is less likely to be used by users, only added to match the `signIn` behavior.
```ts
interface SignOutResponse {
  /** The URL the user should have been redirected to. (Same page by default) */
  url: string
}
const response: SignOutResponse = await signOut({ redirect: false })
```
**Checklist**:

- [ ] Documentation
- [x] Tests (Tested it locally so far, through the developer application, looking good there)
- [ ] Ready to be merged
      

This has been requested several times:

Resolves #989
Also related:
- Issues/PRs: #1180,#517, #1192, 
- Discussions: #944, #754, #878

### CODE REVIEW

**Comment by cgerikj** [comment]
Thank you, this is perfect! :)

**Comment by StefanSelfTaught** [comment]
This would work for email signin too so it won't redirect you to another page just to tell you 'go check you email' or for errors. @balazsorban44

**Comment by balazsorban44** [comment]
thanks, I'll check that out as well!

**Comment by yelnyaface** [comment]
hi, has the documentation for this been added?

**Comment by balazsorban44** [comment]
See:

https://next-auth.js.org/getting-started/client#using-the-redirect-false-option
https://next-auth.js.org/getting-started/client#using-the-redirect-false-option-1

**Comment by shozib13** [comment]
In the top of the example code const `response: SignInResponse = await signIn("credentials", { redirect: false })` response type  is SignInResponse  but typescript showing me error as `Object is possibly 'undefined'.ts(2532)`

image

**Pull request merged**
