### PR TITLE
chore(docs): fix drizzle docs imports and syntax

### PR DESCRIPTION
**Pull request by mohit4bug**
## ☕️ Reasoning

I've updated the Drizzle adapter guides to fix some import statements and added missing brackets in the content to ensure the code examples are correct and complete.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

No specific issues were addressed by this PR.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

This looks good to go! Once the review is complete, we can proceed with merging the changes. If there are any further adjustments or feedback, feel free to let me know!

### CODE REVIEW

**Comment by ndom91** [comment]
I'm going to hold off on this PR for the time being, as there is some active work being done to fix up some things in regard to the recent Drizzle adapter rewrite, see the comments at the bottom of [that PR](https://github.com/nextauthjs/next-auth/pull/10479). Also there's some discussion about it in the discord if yuo wanna check it out:

- Invite: [discord.authjs.dev](https://discord.authjs.dev/)
- Drizzle Adapter Thread: [discord.com/channels/1200116961590399008/1231534836859146241](https://discord.com/channels/1200116961590399008/1231534836859146241)

**Comment by mohit4bug** [comment]
> I'm going to hold off on this PR for the time being, as there is some active work being done to fix up some things in regard to the recent Drizzle adapter rewrite, see the comments at the bottom of [that PR](https://github.com/nextauthjs/next-auth/pull/10479). Also there's some discussion about it in the discord if yuo wanna check it out:
> 
> - Invite: [discord.authjs.dev](https://discord.authjs.dev/)
> - Drizzle Adapter Thread: [discord.com/channels/1200116961590399008/1231534836859146241](https://discord.com/channels/1200116961590399008/1231534836859146241)
> 

Thank you for letting me know!

**Comment by ndom91** [comment]
Hey we've updated the Drizzle adapter (and docs) a good bit the last few days. Can you check out the merge conflict and see if these changes are still necessary?

Thanks!

**Comment by mohit4bug** [comment]
> Hey we've updated the Drizzle adapter (and docs) a good bit the last few days. Can you check out the merge conflict and see if these changes are still necessary?
> 
> Thanks!

Sure!

**Comment by ndom91** [comment]
Okay great, I'll close this PR then 🙏

**Pull request closed without merging**
