### PR TITLE
Add Concept2 provider.

### PR DESCRIPTION
**Pull request by angrytongan**
## ☕️ Reasoning

Adding [Concept2](https://log.concept2.com/developers/documentation/) as a provider.

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [X] Ready to be merged

### CODE REVIEW

**Comment by angrytongan** [comment]
Just realised that the documentation has moved; will get around to fixing this up and resubmitting the PR.

**Comment by remisture** [comment]
What's the status here, @angrytongan? I'm looking for a concept2 implementation I can use :)

**Comment by angrytongan** [comment]
> What's the status here, @angrytongan? I'm looking for a concept2 implementation I can use :)

I don't think this was looked at before all the doc changes. Don't have much time for this at the moment, feel free to pick this up. From memory I think it was pretty straight forward.

**Comment by falcowinkler** [comment]
Closed in favor of https://github.com/nextauthjs/next-auth/pull/11817

**Pull request closed without merging**
