### PR TITLE
feat(adapter): add `postgres.js` adapter

### PR DESCRIPTION
**Pull request by CodyBontecou**
## ☕️ Reasoning

Adding a [postgres.js](https://github.com/porsager/postgres) database adapter.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
What's the difference between this as the [pg](https://npm.im/pg)-based adapter (`@auth/pg-adapter`)?

**Comment by CodyBontecou** [comment]
This uses [postgres.js](https://github.com/porsager/postgres) instead of node-postgres.

**Comment by ndom91** [comment]
> This uses [postgres.js](https://github.com/porsager/postgres) instead of node-postgres.

Right, but what's the advantage of one over the other?

**Comment by ndom91** [comment]
There's another PR adding an adapter which uses postgres.js (see: https://github.com/nextauthjs/next-auth/pull/11200), we'd love it if you two could sync and just put up 1 high(er) quality PR :pray:

**Comment by CodyBontecou** [comment]
My PR was a pretty quick hack with plenty of TS-related errors. It's probably best to go with their PR.

**Pull request closed without merging**
