### PR TITLE
Change `redirectTo` to `callbackUrl`

### PR DESCRIPTION
**Pull request by SuecoMarcus**
## ☕️ Reasoning

The `redirectTo` property does not exist. The docs should mention `callbackUrl`.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by k-taro56** [comment]
The property probably exists. Please check again.

https://github.com/nextauthjs/next-auth/blob/5dc7ed4ba58ba943d47c8c5c9090be6540575dea/packages/next-auth/src/index.ts#L298-L299

**Comment by balazsorban44** [comment]
As mentioned above, the current code is correct. See: https://github.com/nextauthjs/next-auth/blob/5dc7ed4ba58ba943d47c8c5c9090be6540575dea/packages/next-auth/src/index.ts#L299

**Comment by SuecoMarcus** [comment]
Thanks @k-taro56 and @balazsorban44!

This is odd. I'm using `"next-auth": "^5.0.0-beta.18"`.

Please take a look at the following screenshots.

`import { signIn } from "next-auth/react";`

Screenshot 2024-06-07 at 12 11 44

Screenshot 2024-06-07 at 12 12 00

As you may see, the `redirectTo` property is not suggested by Intellisense.

https://github.com/nextauthjs/next-auth/blob/5dc7ed4ba58ba943d47c8c5c9090be6540575dea/packages/next-auth/src/lib/client.ts#L56
https://github.com/nextauthjs/next-auth/blob/5dc7ed4ba58ba943d47c8c5c9090be6540575dea/packages/next-auth/src/lib/client.ts#L58

And this is how it looks in the documentation:

Screenshot 2024-06-07 at 12 18 35

**Comment by SuecoMarcus** [comment]
Hi @balazsorban44 

Could you see my last message?

Thank in advance!

**Pull request closed without merging**
