### PR TITLE
Update envinfo command to one line

### PR DESCRIPTION
**Pull request by TouqeerH**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes and improves: https://github.com/nextauthjs/next-auth/issues/8644

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ThangHuuVu** [comment]
this won't work, it will print: "no matches found: @auth/*". please see the linked issue for more details

**Comment by TouqeerH** [comment]
@ThangHuuVu 
I have tested it with ` npx envinfo --system --binaries --browsers --npmPackages "{next,react,next-auth,@auth/*}"`command on `sh` and `cmd`. 

Output: 
```sh


  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
    Memory: 23.38 GB / 29.93 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - D:\developments\next-boilerplate\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.58)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @auth/solid-start: ^0.1.3 => 0.1.3
    @auth/sveltekit: ^0.3.12 => 0.3.12
    next: latest => 13.5.3
    next-auth: ^4.23.1 => 4.23.1
    react: latest => 18.2.0

```

**Comment by ThangHuuVu** [comment]
@TouqeerH sorry I overlooked it! Could you open a new PR then? I can't reopen this one.

**Comment by ThangHuuVu** [comment]
Reopen

**Comment by TouqeerH** [comment]
@ThangHuuVu No worries. Here is the fresh PR: https://github.com/nextauthjs/next-auth/pull/9187. Please suggest if any futrthur improvement is needed.

**Pull request closed without merging**
