### PR TITLE
Update reddit.md

### PR DESCRIPTION
**Pull request by DJ-Meyers**
Spent all day troubleshooting this and finally found a fix.  There's no good documentation anywhere so this seems like the best place to add a solution.

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Update Documentation

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

None open: https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+reddit

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by DJ-Meyers** [comment]
Here is proof of the reddit auth actually working

https://user-images.githubusercontent.com/16687296/218244049-75818858-7bd7-46d0-b477-ea60152a5d8c.mp4

**Review by ThangHuuVu — COMMENTED** [review]
It seems to me that we can just add `checks: ['state']` to `reddit.js` and this would be solved. 🤔 Could you try to do that?

**Comment by DJ-Meyers** [comment]
Not super familiar with the codebase, but I think this is what you meant:
```
function Reddit(options) {
  return {
    id: "reddit",
    name: "Reddit",
    type: "oauth",
    authorization: "https://www.reddit.com/api/v1/authorize?scope=identity",
    token: " https://www.reddit.com/api/v1/access_token",
    userinfo: "https://oauth.reddit.com/api/v1/me",
    checks: ['state'],

    profile(profile) {
      return {
        id: profile.id,
        name: profile.name,
        email: null,
        image: null
      };
    },

    options
  };
}
```

This gave me the same error as before.  In my testing I realized you can't just have 'state' in the url it needs an actual value.  I tried changing it again to:
```
checks: ['state=some_string']
```
But it still didn't work.

**Comment by zimonitrome** [comment]
I still can't OAuth to work with Reddit.

I'm using SolidStart auth.js example where I have provided the following providers:

```
export const authOptions: SolidAuthConfig = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
    DiscordProvider({
      clientId: process.env.DISCORD_CLIENT_ID as string,
      clientSecret: process.env.DISCORD_CLIENT_SECRET as string,
    }),
    RedditProvider({
      clientId: process.env.REDDIT_CLIENT_ID as string,
      clientSecret: process.env.REDDIT_CLIENT_SECRET as string,
    }),
    GithubProvider({
      clientId: process.env.GITHUB_CLIENT_ID as string,
      clientSecret: process.env.GITHUB_CLIENT_SECRET as string,
    }),
  ] as Array<Provider<any>>,
...
```

All of which work except Reddit.

My login button simply looks like this:
```<button onClick={() => signIn()}>Sign In</button>```

I have tried to add the suggested `{ state: 'reddit_needs_this_to_work' }` to both the login button:

```
<button onClick={() => signIn(undefined, undefined, { state: 'reddit_needs_this_to_work' })}>Sign In</button>
```

and the RedditProvider:

```
    RedditProvider({
      clientId: process.env.REDDIT_CLIENT_ID as string,
      clientSecret: process.env.REDDIT_CLIENT_SECRET as string,
      authorization: {
        state: 'reddit_needs_this_to_work'
      },
    }),
```

But whatever I do I still get this page:

image

This is the URL that is called:
```
https://www.reddit.com/api/v1/authorize?scope=identity&response_type=code&client_id=<my_client_id>&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2Fapi%2Fauth%2Fcallback%2Freddit&code_challenge=8joWpRyg0Az3Ep5XUj6OwTNhyNpcRvQeSwBcdtwR6oE&code_challenge_method=S256
```

Can you see that I'm doing something wrong @DJ-Meyers?

Maybe someone on the member team could check that Reddit login works @ThangHuuVu?

**Comment by ndom91** [comment]
Could you share the rest of your Auth config? Not just the providers? 

What initially jumps out at me, is that your `signin` call is missing the provider, so it should be something like: 

``` 
...onClick={() => signIn('reddit', undefined, { state: 'abc123' })}
``` 

Notice the `"reddit"` string as the first argument to signin.

**Comment by zimonitrome** [comment]
@ndom91 this actually worked fine!

I am using the [Solid Start AuthJS template](https://github.com/solidjs/solid-start/tree/main/examples/with-authjs) with the providers extended as above. When the `SignIn()` is called, I'm directed to a page where I can choose providers:
image

It's odd that the Reddit one is missing the logo.

I'm pretty new to both packages so I'm unsure if this is on AuthJS side or Solid Start.

But I would prefer so only have a single button with the `signIn()` button and still have this working. An empty `signIn()` works for the other providers (Google, Discord, Github) but not Reddit.

**Pull request closed without merging**
