### PR TITLE
fix(adapters): allow already initialized firebase app 🐛 

### PR DESCRIPTION
**Pull request by jsellam**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning
Firebase adapter can't be used with an already initialized firebase app. 

Before initializing a new app, we search if an app with the same name has been initialized

## 🧢 Checklist

- [ ] Documentation
- [X] Tests
- [X] Ready to be merged

## 🎫 Affected issues

[[Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.]

https://github.com/nextauthjs/next-auth/issues/5029
https://github.com/nextauthjs/next-auth/issues/4927

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
LGTM, thanks 🥳 

Can we merge this? @ThangHuuVu @balazsorban44

**Comment by jsellam** [comment]
> Someone is attempting to deploy a commit to the **authjs** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=authjs&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%225fbd794e339b214293854ed0ebe2aa5515bf7995%22%7D%2C%22id%22%3A%22QmRLhay81HrP1tRCBaL87zVRyG1BSUak4XmxLVbJ6w7Pju%22%2C%22org%22%3A%22nextauthjs%22%2C%22prId%22%3A6230%2C%22repo%22%3A%22next-auth%22%7D).

Does I need to do something ?

**Review by ThangHuuVu — APPROVED** [review]
LGTM!

**Comment by balazsorban44** [comment]
Heads up, this will be superseded by #6225 (incorporating this change too!)

**Pull request merged**
