### PR TITLE
fixed the resend logo for dark mode

### LINKED ISSUE #11116: bug: Resend logo is not visible in dark mode
### What is the improvement or update you wish to see?

The Resend logo should be visible in the dark mode. 

Light Mode: 
Screenshot 2024-06-09 at 1 58 28 PM

Dark Mode:
Screenshot 2024-06-09 at 1 58 42 PM

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/email

### PR DESCRIPTION
**Pull request by dhairyathedev**
## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: #11116 
Before:
Screenshot 2024-06-09 at 2 00 40 PM

After:
Screenshot 2024-06-09 at 2 00 20 PM

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Nice thanks!

**Comment by ndom91** [comment]
Sorry, approved a little quick.. 

How about we try not adding a new resend svg. And set the original resend svg to fill with `currentColor` and then in the resend logo on the page we can do `dark:text-white` and `text-black` or something like that. Could you give that a shot?

**Comment by dhairyathedev** [comment]
Changes are done @ndom91
Please review it.

**Comment by ndom91** [comment]
> Changes are done @ndom91
> Please review it.

Hmm looks like doesn't work atm. 





Youll need to change the preexisting `resend.svg` `fill` from whatever hex color it is to `currentColor`. 

currentColor means it'll inherit whichever color the text is on it / it's parent

**Comment by dhairyathedev** [comment]
Hey @ndom91,

I set the SVG background to `currentColor` in dark mode, which resolves the issue. Additionally, we don't need to explicitly set any text color.
Screenshot 2024-06-14 at 12 00 44 AM


https://github.com/nextauthjs/next-auth/assets/65452005/9a0cdb2e-d01d-4ade-b4c8-6883c164828b

**Pull request merged**
