### PR TITLE
feat(provider): Add Azure Active Directory B2C

### PR DESCRIPTION
**Pull request by vladimir-e**
Adds a provider for authenticating with Azure OAuth 2.0 API.

Screen Shot 2020-12-06 at 3 18 10 PM

Update: 
[How to Configure Azure AD B2C Authentication with Next.js](https://benjaminwfox.com/blog/tech/how-to-configure-azure-b2c-with-nextjs)

Original PR: #809

### CODE REVIEW

**Comment by vladimir-e** [comment]
> RE: https://github.com/nextauthjs/next-auth/pull/809#issuecomment-739560749

@balazsorban44 , thanks for the update on the new release strategy. I rebased my fork off `canary`. This PR is ready.

**Comment by kostenickj** [comment]
any idea when this will be released in the main package on npm?

**Comment by balazsorban44** [comment]
@kostenickj We aim to have this released in an unstable `canary` release on NPM sometime this month. To get it released in a stable release, we need to improve our testing strategy, and check that our documentation is up to date.

**Comment by kostenickj** [comment]
@balazsorban44 any update on publishing canary packages?

I have been cloning and building the canary branch locally, but it isn't realistic for my whole team to do it.

Thanks.

**Comment by balazsorban44** [comment]
I still hope this month is realistic, though we are in the beginning of the holiday season. Some of us probably focus more on family right now. I am waiting for a token I could use for publishing and some credentials for unpublishing just in case something should go wrong. I think you can subscribe to releases on the repo to be notified. 😉

**Pull request merged**
