### PR TITLE
Improvements to Apple provider

### PR DESCRIPTION
**Pull request by iaincollins**
When using a provider that uses Token ID option (like Apple) a user hitting cancel with no longer cause the app to crash.

Users who do this will now be taken back to the sign in page.

This was already working for other providers that didn't use this option but wasn't supported for providers that did use it.

This addresses one issue raised in #346

### CODE REVIEW

**Review by geraldnolan — COMMENTED** [review]
@iaincollins The error is happening before this section..

I was about to push code either today or tomorrow since I am getting github 500 related errors today.

The body of the request from apple actually tells you the user cancelled.

I was a little bit unfamiliar on how to send the callback. 

```jsx
if (provider.version && provider.version.startsWith('2.')) {
    if (req.method === 'POST') {

      // Get the CODE from Body
      const body = JSON.parse(JSON.stringify(req.body))

      // @TODO Handle error
      if (body.error) {
        logger.error('OAUTH_CALLBACK_HANDLER_ERROR', body.error, req.body, provider.id, code)
        callback(body.error, null, null, null)
      }
```

**Comment by geraldnolan** [comment]
Also, there is an issue with using apple without a database since the only time you get the user's name is on the first login in. :/

Not sure if you can view the form but here is a link on more information
https://developer.apple.com/forums/thread/119826?page=2

**Comment by iaincollins** [comment]
> Also, there is an issue with using apple without a database since the only time you get the user's name is on the first sign in. :/ 

No worries! I was thinking about adding a boiler plate notice to this for OAuth providers that should be used with a database.

Google actually falls into this category too, as it only issues OAuth Refresh Tokens on first login, unless you force an additional consent screen on every sign in (which is really intended for mobile or desktop apps). 

We can just list that for providers that have that limitation.

**Comment by iaincollins** [comment]
> @iaincollins The error is happening before this section..
> 
> I was about to push code either today or tomorrow since I am getting github 500 related errors today.
> 
> The body of the request from apple actually tells you the user cancelled.

Thanks for looking at this! Oh! I accessed the callback route now it does not crash, and I am returned to the sign up page, as that works for other providers. I guess we need to return sooner?

I've been hoping to avoid provider specific approaches to checking if a flow is cancelled (and just going with checking if there is a valid response or not a proxy method for doing that) to avoid provider specific code in general, as they are all different and there doesn't seem to be a standard for it. :-( Maybe that is not possible in this case.

If we do get an error, returning an empty callback `callback()` is fine and will let the page know to do that. Maybe we should just do that on error, as the user will be redirected to the sign up page (and we can still log the error in the console).

This is not ideal obviously but I am inclined to think we kick refactoring down the road a bit until we have tests and also address an issue I've raised in core chat today.

(BTW not sure if you got the email invite! There should be an invitation to https://github.com/orgs/nextauthjs/teams/core waiting for you in your inbox somewhere :-)

**Comment by geraldnolan** [comment]
@iaincollins Did you get my email from Google Doc?

**Comment by iaincollins** [comment]
> @iaincollins Did you get my email from Google Doc?

Yes, thank you! Sorry I have been crazy busy the last few days (we were having some plumbing / gas work done at home). Will reply later today!

**Comment by iaincollins** [comment]
@geraldnolan Merging this into the v3 branch with pull requests from from @Fumler (Prisma adapter) and myself (CSRF, etc) so we can do integration testing on the changes and push it out as a beta, with a fix forward approach, before any of the branches go stale! Will link back to this PR with the one we raise for v3 branch when we have one.

**Comment by iaincollins** [comment]
Update for wider audience: I've tested this and thanks to the work @geraldnolan did changes seem to work great, but we will do some more testing on it and should be able to add the Apple provider to the live demo soon.

**Pull request merged**
