### PR TITLE
fix(adapter-dynamodb): update and delete session use correct partition/sort keys

### PR DESCRIPTION
**Pull request by davidwinter**
If you have defined custom options for the Dynamo adapter, such as:

```ts
  adapter: DynamoDBAdapter(client, {
    tableName: "mytable",
    partitionKey: "partitionKey",
    sortKey: "sortKey",
    indexName: "indexOnePartitionKey-indexOneSortKey-index",
    indexPartitionKey: "indexOnePartitionKey",
    indexSortKey: "indexOneSortKey",
  }),
```

The overridden values of `partitionKey` and `sortKey` are not used in `deleteSession` or `updateSession`. An error is thrown:

> ValidationException: The provided key element does not match the schema

This commit will correctly use either the default or overridden values so that these actions can be completed correctly.

### CODE REVIEW

**Comment by davidwinter** [comment]
@balazsorban44 at the moment, we're having to maintain a fork of this in order to use the documented customisations. Is there any feedback or further help I can provide to help get this merged in and released?

**Comment by ndom91** [comment]
@davidwinter I had some trouble running the tests in this adapter. Looks like its having issues with jest and the shelf/dynamodb package due to the main package.json having `"type": "module"`..

I updated the `@shelf/dynamodb` pkg to `latest` and renamed `jest-dynamodb-config.js` to `.cjs` and some other small fixes to get it all to run/pass again. 

Unfortunately I don't have rights to push to `davidwinter/patch-2`, so here's the `git diff`:

```diff
diff --git packages/adapter-dynamodb/jest-dynamodb-config.js packages/adapter-dynamodb/jest-dynamodb-config.cjs
similarity index 100%
rename from packages/adapter-dynamodb/jest-dynamodb-config.js
rename to packages/adapter-dynamodb/jest-dynamodb-config.cjs
diff --git packages/adapter-dynamodb/jest.config.js packages/adapter-dynamodb/jest.config.js
index d7d182e8..7a7c6d32 100644
--- packages/adapter-dynamodb/jest.config.js
+++ packages/adapter-dynamodb/jest.config.js
@@ -1,9 +1,14 @@
+import config from "utils/adapter/jest-preset.js"
+import path from 'node:path'
+
+process.env.JEST_DYNAMODB_CONFIG = path.resolve('./jest-dynamodb-config.cjs');
+
 /*
  * For a detailed explanation regarding each configuration property and type check, visit:
  * https://jestjs.io/docs/en/configuration.html
  */
-module.exports = {
-  ...require("@next-auth/adapter-test/jest/jest-preset"),
+export default {
+  ...config,
   // // Indicates whether the coverage information should be collected while executing the test
   // collectCoverage: true,
   // // Indicates which provider should be used to instrument code for coverage
diff --git packages/adapter-dynamodb/package.json packages/adapter-dynamodb/package.json
index 3cfe9bcc..ba1c2a78 100644
--- packages/adapter-dynamodb/package.json
+++ packages/adapter-dynamodb/package.json
@@ -49,7 +49,7 @@
   "devDependencies": {
     "@aws-sdk/client-dynamodb": "^3.36.1",
     "@aws-sdk/lib-dynamodb": "^3.36.1",
-    "@shelf/jest-dynamodb": "^2.1.0"
+    "@shelf/jest-dynamodb": "^3.4.2"
   },
   "dependencies": {
     "@auth/core": "workspace:*"
diff --git packages/adapter-dynamodb/src/index.ts packages/adapter-dynamodb/src/index.ts
index a6f08e29..daa42cf1 100644
--- packages/adapter-dynamodb/src/index.ts
+++ packages/adapter-dynamodb/src/index.ts
@@ -26,6 +26,7 @@ import type {
   AdapterUser,
   VerificationToken,
 } from "@auth/core/adapters"
+import { randomUUID } from "node:crypto"
 
 export interface DynamoDBAdapterOptions {
   tableName?: string
@@ -186,7 +187,7 @@ export function DynamoDBAdapter(
     async createUser(data) {
       const user: AdapterUser = {
         ...(data as any),
-        id: crypto.randomUUID(),
+        id: randomUUID(),
       }
 
       await client.put({
@@ -310,7 +311,7 @@ export function DynamoDBAdapter(
     async linkAccount(data) {
       const item = {
         ...data,
-        id: crypto.randomUUID(),
+        id: randomUUID(),
         [pk]: `USER#${data.userId}`,
         [sk]: `ACCOUNT#${data.provider}#${data.providerAccountId}`,
         [GSI1PK]: `ACCOUNT#${data.provider}`,
@@ -374,7 +375,7 @@ export function DynamoDBAdapter(
     },
     async createSession(data) {
       const session = {
-        id: crypto.randomUUID(),
+        id: randomUUID(),
         ...data,
       }
       await client.put({
@@ -406,7 +407,7 @@ export function DynamoDBAdapter(
         },
       })
       if (!data.Items?.length) return null
-      const { pk, sk } = data.Items[0] as any
+      const sessionRecord = data.Items[0] as any
       const {
         UpdateExpression,
         ExpressionAttributeNames,
@@ -414,7 +415,10 @@ export function DynamoDBAdapter(
       } = generateUpdateExpression(session)
       const res = await client.update({
         TableName,
-        Key: { pk, sk },
+        Key: {
+          [pk]: sessionRecord[pk],
+          [sk]: sessionRecord[sk],
+        },
         UpdateExpression,
         ExpressionAttributeNames,
         ExpressionAttributeValues,
@@ -438,11 +442,14 @@ export function DynamoDBAdapter(
       })
       if (!data?.Items?.length) return null
 
-      const { pk, sk } = data.Items[0]
+      const sessionRecord = data.Items[0]
 
       const res = await client.delete({
         TableName,
-        Key: { pk, sk },
+        Key: {
+          [pk]: sessionRecord[pk],
+          [sk]: sessionRecord[sk],
+        },
         ReturnValues: "ALL_OLD",
       })
       return format.from<AdapterSession>(res.Attributes)
diff --git pnpm-lock.yaml pnpm-lock.yaml
index 0f134872..db95ec5e 100644
--- pnpm-lock.yaml
+++ pnpm-lock.yaml
@@ -355,8 +355,8 @@ importers:
         specifier: ^3.36.1
         version: 3.113.0(@aws-sdk/client-dynamodb@3.113.0)(@aws-sdk/smithy-client@3.374.0)(@aws-sdk/types@3.468.0)
       '@shelf/jest-dynamodb':
-        specifier: ^2.1.0
-        version: 2.2.4(@aws-sdk/client-dynamodb@3.113.0)(@aws-sdk/lib-dynamodb@3.113.0)(@aws-sdk/util-dynamodb@3.470.0)
+        specifier: ^3.4.2
+        version: 3.4.2
 
   packages/adapter-edgedb:
     dependencies:
```

You might need to just run `pnpm install` again briefly to get an updated `pnpm-lock.yaml`, not sure if it got every small update in there ^^ :thinking:

**Comment by davidwinter** [comment]
Thanks @ndom91 - tests are now passing for me locally and I've pushed the changes. Not all status checks are passing on here though, so I'm not sure if that is expected or not?

**Comment by ndom91** [comment]
> Thanks @ndom91 - tests are now passing for me locally and I've pushed the changes. Not all status checks are passing on here though, so I'm not sure if that is expected or not?

These two docs build failures are okay for now, not related to you / this PR at least :+1:

**Comment by davidwinter** [comment]
Thanks @ndom91 - please let me know if you need anything else from me on this 👍 Happy to help.

**Comment by ndom91** [comment]
Yeah thanks for the quick response, i think this is more or less good to go. Just gonna give everything one last look over 👍

**Pull request merged**
