### PR TITLE
chore(docs): broken docs link

### PR DESCRIPTION
**Pull request by okinawaa**
naver.js => naver.ts

## ☕️ Reasoning

There is broken link

image

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Nice catch

**Comment by ndom91** [comment]
Can you also update this in the `versioned_docd/version-bets` directory? 🙏

**Comment by ChanhyukPark-Tech** [comment]
> Can you also update this in the versioned_docs/version-beta directory? 🙏

Sure why not?!

I made it! in this commit [fix: naver.js => naver.ts](https://github.com/nextauthjs/next-auth/pull/6027/commits/efd5305173333bd4f742d8d8a8138ee5be22306d)

**Comment by ndom91** [comment]
Hey we're moving a lot of things around in the docs right now, so I just applied these updates in the working PR we have going. Thanks for catching it!

See: https://github.com/nextauthjs/next-auth/pull/6024/commits/1a981e2394681b784a573523cbbc289fee29adee

**Pull request closed without merging**
