### PR TITLE
Version 2.0 Release

### PR DESCRIPTION
**Pull request by iaincollins**
I'm raising this as somewhere for contributors to review and discuss plans for release of 2.0 if anyone wants to.

This is the current state of the 2.0 milestone:
https://github.com/iaincollins/next-auth/milestone/1

It has been shrinking and growing, I've been guilty of scope creep - we've had a few features I thought would not drop till later sneak in:

* JWT Tokens
* Database Optional
* Signin Callback (allow/deny access)
* Email address now optional

I want to stop the scope creep but one feature has lead to another and it's easier to do some things right first time than to fix them later - particularly around database schemas / models - as some mistakes we end up getting stuck with (and others are easier to fix post launch). I also would rather make major breaking changes to the API now than after launch.

These are the things we are working on:

* #221 - New OAuth providers (optional)
* #245 - ~Update and document models, schemas and database structure~ DONE
* #247 - ~New Callback / Events system~ DONE

I can do #247 pretty easily, it's not as pressing but it's fairly straight forward I think. I would love help with that actually if anyone fancies picking any of it up! I'm not sure if the intent is clear to other people though.

Doing #245 is harder as involves much more testing, but I think needs to be done, as I don't think the current models are good enough to launch with and I don't really want to have to take on extra work right after launch to support database schema migration; that's a pain for users and for me to write. I'd rather put that off as much as possible and keep schema changes within major versions as limited as they can be.

PS: I appreciate code changes are hard and it's not well documented how to contribute. It took me about 2-3 hours to set up `next-auth` properly for local development the first time when I wrote the damn thing (grr React) and it keeps catching me out when I forget to re-link to the test project I am using (and back to React), so I get the developer experience is really annoying and needs work too.

Related: 

* Discussion of 2.1 roadmap #227

### CODE REVIEW

**Comment by LoriKarikari** [comment]
The OAuth providers I'm adding aren't really necessary for the 2.0 launch. We already cover the major ones so that's good. These new providers will be added all the time by other people's PRS or requests so it's an ungoing thing not really bound to a release. I can finish the ones I'm working on and add them. Was planning to add a bunch of new ones but have some stuff going on this week(end) so not really a lot of time.

**Comment by iaincollins** [comment]
> The OAuth providers I'm adding aren't really necessary for the 2.0 launch. We already cover the major ones so that's good. These new providers will be added all the time by other people's PRs or requests so it's an ungoing thing not really bound to a release. I can finish the ones I'm working on and add them. Was planning to add a bunch of new ones but have some stuff going on this week(end) so not really a lot of time.

Totally see this the same way! Appreciate everything you have done. I think it's gonna take me a few days to find time to finish the work I'm doing too as have bitten off a fair bit now. Oops. My justification is that solves a lot of problems I have across multiple projects.

The work you and @ndom91 have done has been really transformative and the project is so much better for it and I'm so grateful for your time, including doing things like responding to folks with issues!

**Comment by ndom91** [comment]
Saw there was another issue open on the roadmap regarding the default pages on mobile. I can definitely take a look at that later on this evening. Also possibly add an example to nextjs. They have a huge folder of examples already we could just make a PR to ([source](https://github.com/vercel/next.js/tree/canary/examples)). What did you picture here? Something similar to your `next-auth-example` repo?

**Comment by iaincollins** [comment]
> Saw there was another issue open on the roadmap regarding the default pages on mobile. I can definitely take a look at that later on this evening. Also possibly add an example to nextjs. They have a huge folder of examples already we could just make a PR to ([source](https://github.com/vercel/next.js/tree/canary/examples)). What did you picture here? Something similar to your `next-auth-example` repo?

Thank you! I think adding an example to the Next.js repo was actually @LoriKarikari's idea!

I think we should probably wait until release of 2.0 before raising a PR against the Next.js repo (but could fork and get it ready in advance?).

Probably something like the example project would be good, but maybe even simpler? (e.g. no components or styles, just a page or two, with as little code as possible - maybe the `_app.js` though as that is relevant).

I haven't looked at the other auth examples in a while, but I guess something like them.

**Comment by iaincollins** [comment]
Okay, I think um I am done? 🙀 With the new improved database models, new events and callback system I think I'm ready to cut 2.0 for release (pending any bug reports that come in!)

I'll let the release sit for a bit, but am content to push the button any time.

Let me know if you spot any issues or feel otherwise!

**Comment by ndom91** [comment]
Okay great, I'll whip up a next.js example PR so that that can be released around the release of v2 as well.

**Comment by iaincollins** [comment]
I've been busy recently, but I'm going to hoover up some small issues this morning:

* #242 - Add Box provider
* #286 - Add GitLab provider
* #275 - Add Yandex provider (can then close this issue as is actually resolved)
* #280 - Small feature to add input fields for credentials provider to sign up page
* #208 - Small to add callbackURL option to client (I also want to make a couple of small tweaks to the client)

As a reminder to myself when compiling release notes, we also now have [Open ID Identity Server](https://next-auth.js.org/providers/identity-server4) in the next release.

Once these are in, I'll push out a new beta and do a pass of the documentation and general review of behaviour against all supported databases (and maybe some speculative testing against a few other SQL databases).

If that's all good, then I anticipate releasing 2.0 Sunday or Monday.

**Comment by iaincollins** [comment]
Am drafting release notes to do a release now. If you see this and want to hold off, give me a shout, otherwise I'm going to cut the release and push it out shortly. :-)

PS: It might be a little while before we get round to automating releases with GitHub Actions + NPM (and having `main` auto-deploy to `@beta`/`@canary` or whatever we decided to do) but for now I'm totally happy to keep doing manual releases for new OAuth providers, etc whenever a PR is merged.

**Comment by iaincollins** [comment]
@ndom91 @LoriKarikari @geraldnolan 🙀👯 🎉🥳

**Pull request merged**
