### PR TITLE
feat(cookies): make pkce and state maxAge configurable on the cookies…

### LINKED ISSUE #4660: Allow the maxAge/expires applied to the cookies to be configurable
### Description 📓

Currently the maxAge on the jwt and the expires on the cookie options are being set to a hard coded 15 minutes.

## pkce
defined here

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/pkce-handler.ts#L7

set as expires here

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/pkce-handler.ts#L30

overwrites the jwt maxAge option here 

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/pkce-handler.ts#L35

## state
defined here

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/state-handler.ts#L6
 
set as expires here

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/state-handler.ts#L30

overwrites the jwt maxAge option here 

https://github.com/nextauthjs/next-auth/blob/e4ee520b4aba55fbc123801291bcba404f578d3f/packages/next-auth/src/core/lib/oauth/state-handler.ts#L23

## proposal
Add a new option for stateMaxAge and pkceMaxAge on the jwt options.
If these are not set the 15 minute default mentioned above would be used. 

stateMaxAge
expiresStateMaxAge

Similar changes in pkce-handler.js

## reason
We are using fusionAuth with 2fa that emails a code.
We have a client that is using an smtp that is taking 15 minutes to deliver the email with the code.
This delay prevents the client from being able to submit the 2fa code to finish the log in process because the hard coded max age and expires of 15 minutes has already been reached.
We need to be able to extend that time so that the client has enough time to receive and submit the 2fa code.

### How to reproduce ☕️

To reproduce bring up the log in page for any application using next-auth and let the page sit for over 15 minutes and then log in.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

### PR DESCRIPTION
**Pull request by jason-brady-mythical**
… (#4660)

## ☕️ Reasoning

Currently the maxAge and the expires on the cookie options are being set to a hard coded 15 minutes.
These changes allow the consumer to configure the maxAge for the pkce and state cookies options.
If the cookie options are not set they are defaulted to the 15 minutes.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: [4660](https://github.com/nextauthjs/next-auth/issues/4660)

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by jason-brady-mythical** [comment]
@balazsorban44 Any chance of getting this PR looked at some time soon?  Thanks.

**Comment by ThangHuuVu** [comment]
Thanks for the clean PR!
Would you be interested in adding some tests to `createPKCE` and `createState` as well?
We're trying to increase test coverage in this project, so it would be really nice if you could add them to the PR too 💚

**Comment by jason-brady-mythical** [comment]
@ThangHuuVu updated this pr with tests around createPKCE and createState.

Screen Shot 2022-09-13 at 1 43 38 PM

**Comment by jason-brady-mythical** [comment]
@ThangHuuVu @balazsorban44 Anything else needed to try and get this merged?

**Comment by twhitson** [comment]
This is a blocker for me as well. Do we know how long until this will be merged and released?

**Review by ThangHuuVu — APPROVED** [review]
Change makes sense to me, let's ship it 🚀

**Comment by jason-brady-mythical** [comment]
@ndom91 @ThangHuuVu I am not able to merge as this needs a maintainer to approve running workflows.  Is there something else I need to do?

**Comment by ThangHuuVu** [comment]
@jason-brady-mythical I approved the workflow, could you update the branch one more time?

**Comment by jason-brady-mythical** [comment]
@ThangHuuVu Updated, not sure what else is needed.

**Comment by C3mkal** [comment]
#5664

**Pull request merged**
