### PR TITLE
fix(docs): update reddit.md

### PR DESCRIPTION
**Pull request by GGonryun**
## ☕️ Reasoning

Adding a small note calling out that Reddit doesn't share the email with third parties.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Useful difference to other providers user info endpoints, thanks

**Comment by ndom91** [comment]
Ah sorry, could you redo this PR against `main` instead of `v4`? Thanks 🙏

**Comment by GGonryun** [comment]
> Ah sorry, could you redo this PR against `main` instead of `v4`? Thanks 🙏

I don't see a corresponding file in the main branch, it looks like the providers folder exists but the individual provider documentation only exists under the v4 branch. am i missing something here?

**Comment by ndom91** [comment]
Yeah so the provider documentation there is part of the typedoc (typescript files) of the providers themselves, check out [here](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/reddit.ts) for example for the code and [here](https://authjs.dev/reference/core/providers/reddit) for the reddit docs page :+1:

**Pull request closed without merging**
