### PR TITLE
feat(providers): Add Vipps provider

### PR DESCRIPTION
**Pull request by endrekrohn**
Added Vipps provider.

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

This pull request adds the OAuth-provider [Vipps](https://en.wikipedia.org/wiki/Vipps). Vipps is the largest payment application in Norway. Vipps also provides a "Log-In"-product, which this pull request adds support for.

## 🧢 Checklist

- [X] Documentation
- [X] Tests
- [X] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: N/A.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks, could you move the code under: https://github.com/nextauthjs/next-auth/tree/main/packages/core/src/providers

And the docs do not need to be written manually anymore, just make sure to add proper JSDoc comments, example: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/auth0.ts

**Comment by itschip** [comment]
Would it be possible to add `nin` as well @endrekrohn ?

**Comment by balazsorban44** [comment]
@itschip we would like if all providers have the same default but you can access all values via the jwt callback's profile parameter, or in case you use a database, the profile callback of the provider can be overridden to save `nin` on your user

**Comment by itschip** [comment]
> @itschip we would like if all providers have the same default but you can access all values via the jwt callback's profile parameter, or in case you use a database, the profile callback of the provider can be overridden to save `nin` on your user

Gotcha, I might continue on OPs PR if we don't see any update in the near future :)

**Comment by endrekrohn** [comment]
> > @itschip we would like if all providers have the same default but you can access all values via the jwt callback's profile parameter, or in case you use a database, the profile callback of the provider can be overridden to save `nin` on your user
> 
> Gotcha, I might continue on OPs PR if we don't see any update in the near future :)

Please do so! I am quite busy at the moment 🙏

**Pull request closed without merging**
