### PR TITLE
update(docs): postgres.md so the instructions are fit for Spotify as a provider.

### PR DESCRIPTION
**Pull request by MatthewJamesBoyle**
A typical Spotify avatar URL is as follow:
```
https://scontent-ams4-1.xx.fbcdn.net/v/t1.0-1/c124.0.320.320a/p320x320/44594471_10217288278180083_8889099770203734016_o.jpg?_nc_cat=103&ccb=2&_nc_sid=0c64ff&_nc_ohc=wHUMWDX3V20AX-k8dIO&_nc_ht=scontent-ams4-1.xx&tp=27&oh=c91bd3a69375dfcc6811a75dcb5c3234&oe=5FD3FCAA
```

This is 264 characters long and so this db schema does not work and you get an error. Upping the character count for image URL solves the problem.

### CODE REVIEW

**Comment by ndom91** [comment]
@MatthewJamesBoyle did you also modify this in your db locally? 

Do you mind modifying the documention for the schema for mysql and mssql as well?

Also if you changed it on your side, maybe add the `length: 300` option to the actual model definition here as well: https://github.com/nextauthjs/next-auth/blob/canary/src/adapters/typeorm/models/user.js

Thanks!

P.S. we changed the structure a bit so before we can merge this, can you update your PR to point at the `canary` branch?

**Comment by balazsorban44** [comment]
Fixed through #777

**Comment by nonnuocvietip** [comment]
Cản ơn

**Comment by nonnuocvietip** [comment]
Cảm ơn

**Pull request closed without merging**
