### PR TITLE
Patch node modules next headers not found #10302

### PR DESCRIPTION
**Pull request by OpenTextASOWSM**
## ☕️ Reasoning

This is the fix described in -
https://github.com/nextauthjs/next-auth/issues/10302

seems a reasonable number of people are hitting this issue.

https://github.com/nextauthjs/next-auth/discussions/9385

## 🧢 Checklist

- [ ] Documentation - no change to documentation, patch of some import statements
- [ ] Tests - use existing tests
- [ ] Ready to be merged

## 🎫 Affected issues

 
[Cannot find module node_modules\next\headers - 10302](https://github.com/nextauthjs/next-auth/issues/10302)

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)
- 
https://github.com/nextauthjs/next-auth/discussions/9385

### CODE REVIEW

**Review by BjornHMS — APPROVED** [review]
approved

**Comment by OpenTextASOWSM** [comment]
Hi, anyone can review/approve?

Seems to be effecting others.

https://github.com/nextauthjs/next-auth/discussions/9385#discussioncomment-8888900

**Comment by HazimAlper** [comment]
Can someone review this pr? It solved my problem in locally.

**Comment by willemmulder** [comment]
I was just hitting this issue. From what I see, everyone that uses /pages in Next.js that use auth() function within getServerSideProps() is affected. Thanks for the PR! :-) Can this be merged?

**Comment by OpenTextASOWSM** [comment]
@ThangHuuVu  can you review?


as a work around until merged might work.... worked for others 


' this was fixed by transpiling next-auth in next.config.js

{
  transpilePackages: ['next-auth'],
}

'

**Comment by ndom91** [comment]
While this may work, I have a feeling this is not the best way to go about this, changing the `next` imports to append the extension. There's gotta be a tsconfig option or something that fixes this, no? @balazsorban44

**Comment by ndom91** [comment]
@OpenTextASOWSM thanks for the quick response. 

Yeah so we were using this for internal imports already, for sure. But using it for external, i.e. 3rd party, packages is what feels wrong to me / the team. 

Unfortunately it does seem to be necessary atm for `next`-related imports as well. 

I cleaned up that other PR a bit so there are no more merge conflicts and theoretically it should be good to go :pray: 

Woudl still appreciate some feedback from anyone else if they ran into this issue and coudl test that other PR to see if it fixes it for them without introducing any other issues

**Comment by balazsorban44** [comment]
This is not the correct solution. third-party imports should not need an import specifier. The issue here is that Next.js currently does not have an `exports` field. There is some ongoing work here: https://github.com/vercel/next.js/pull/64529

**Pull request closed without merging**
