### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by varkadov**
**What**:

Added Typescript support. Now it's possible to write code in TS.

**Why**:

`@types/next-auth` is outdated now, and local `d.ts` are outdated.

**How**:

- Added `@babel/preset-typescript` package and updated Babel configuration
- Rewrited parse-url.js in TypeScript as an example.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x ] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
Right now, our main priority is not built-in TypeScript support (although there are internal minor improvements sporadically, utilizing JSDoc and .d.ts files). If you are not satisfied with the type definitions provided from `@types/next-auth`, I suggest you open PRs against https://github.com/DefinitelyTyped/DefinitelyTyped instead.

Currently, it is just too much overhead for the maintainers to also take care of TS.

**Comment by varkadov** [comment]
@balazsorban44 I made this PR based on this [comment](https://github.com/nextauthjs/next-auth/discussions/977#discussioncomment-237908), and I thought you are looking into it because there is a lot of stuff relative to TypeScript in the repository, but you don't have time for it.

I'm ready to support a transition to TS step by step, not rewrite all repository at once.

What do you think about it?

**Comment by balazsorban44** [comment]
My idea is not to convert any .js files, just provide .d.ts files next to them, and use JSDoc (maybe in combination with a `//@ts-check` on the top of the file, if you use VSCode). Currently, I don't want to introduce any TS compilation to the build step, and neither I want to expose half-finished TS types. (This is why the current .d.ts files are not exposed from this package). We may want to dedicate proper time for improving the user experience through types, but we have many things to improve, which could have a much higher impact (like better OIDC compliance, token rotation, etc.). I just don't have the mental capacity right now to even review TS related stuff, as `next-auth` is my hobby, not my work. I can see the value in improved DX (hence the currently added .d.ts and JSDoc stuff), but since the community can easily support TS through DefinitelyTypes, I like that I don't have to worry about that as well for now. When we get the main features we are planning in place, and we have proper testing, I think then we can start looking at TS again.

**Comment by varkadov** [comment]
I've already passed this path – when you want static typing but scare to rewrite the current codebase and start inventing a bicycle. As a result, everything came to TypeScript but with little pain. 🤗

DefinitelyTypes is awesome, but unfortunately, it's disconnected from reality and sometimes could be outdated, and it could be painful(

If we talk about testing, then TS is good tooling for type matching and cut off part of tests.

This method has proven itself:
- setup current project and let .js and .ts live side by side;
- write a new feature in TS;
- rewrite the current codebase from the children to the parents step by step.

In this PR, I rewrote `parse-url.js` in TS as an example – as you can see, we can use all the charms of static typing pointwise without rewriting the entire repository.

Sweet!? 😎

If you change your mind, I could help you with TS migration and maybe close some issues 😀

**Comment by Cryptoking74** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> **What**:
> 
> 
> 
> Added Typescript support. Now it's possible to write code in TS.
> 
> 
> 
> 
> 
> 
> 
> **Why**:
> 
> 
> 
> `@types/next-auth` is outdated now, and local `d.ts` are outdated.
> 
> 
> 
> 
> 
> 
> 
> **How**:
> 
> 
> 
> - Added `@babel/preset-typescript` package and updated Babel configuration
> 
> - Rewrited parse-url.js in TypeScript as an example.
> -you guys won't get away with this
> 
> 
> 
> 
> 
> 
> **Checklist**:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> - [ ] Documentation N/A
> 
> - [ ] Tests N/A
> 
> - [x ] Ready to be merged
> 
>       
> 
> 
> 
> 
> 
>

**Pull request closed without merging**
