### PR TITLE
Add password into 'user' of the database and change the default adapter

### PR DESCRIPTION
**Pull request by li3939108**
This change can enable signup with email and password. 
The signin with email and password can also be easier 
No need to use another database to store the password.
The updateUser() can also update password if provided current password matched

The password is hashed with bcrypt using a randomly generated salt.

This issue is related https://github.com/nextauthjs/next-auth/issues/361

### CODE REVIEW

**Comment by darshkpatel** [comment]
On a side note do you have an implementation example for this?

**Comment by li3939108** [comment]
I just expose the Adapter in/api/auth/[...nextauth].js (and
 then you can directly pass in the adapter not the DB url ) and call the adapter.createUser() and adapter.updateUser() in the provider.authorize function

**Comment by gamedevsam** [comment]
The prisma schema should also be updated so this functionality can be used with Prisma.

**Comment by gamedevsam** [comment]
I think providing a fully featured credential provider with forget / reset password functionality is a valuable addition to NextAuth. We can still encourage users to use email auth, but this might be a great option during development, or for users who prefer to go this route.

**Comment by darshkpatel** [comment]
> I think providing a fully featured credential provider with forget / reset password functionality is a valuable addition to NextAuth. We can still encourage users to use email auth, but this might be a great option during development, or for users who prefer to go this route.

Completely agree on that one, I have to manually implement auth using ironsession if I have a requirement of email password based auth. Next-Auth providing that feature means it'd the one-stop authentication solution.

**Comment by balazsorban44** [comment]
So I am going to close this, as we don't pursue any addition of an email+password combination as it is harder to maintain, and there are alternatives that are much more secure than this. @iaincollins has explained it very well, but I cannot seem to find his comment at the moment. I will try to remember posting it here when I see it again.

**Comment by jsgv** [comment]
> So I am going to close this, as we don't pursue any addition of an email+password combination as it is harder to maintain, and there are alternatives that are much more secure than this. @iaincollins has explained it very well, but I cannot seem to find his comment at the moment. I will try to remember posting it here when I see it again.

Could you share some of the secure alternatives you mentioned?

**Pull request closed without merging**
