### PR TITLE
fix: `@auth/solid-start` build output

### LINKED ISSUE #9427: Importing @auth/solid-start anywhere in an application causes an error
### Environment

OS: OSX Ventura 13.3.1 (a)
Node: v20.3.1
@auth/solid-start: 0.1.8
Browser: Chrome 120.0.6099.71 (Official Build) (arm64)

### Reproduction URL

https://github.com/BeanSoftwareGroup/auth-solid-start-bug

### Describe the issue

Simply importing the `@auth/solid-start` library breaks the build.

```
[vite] Error when evaluating SSR module ~start/entry-server: failed to import "@auth/solid-start"
|- Error: Cannot find module '/Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/chunk-HXRSFH6L.js' imported from /Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)

An unhandled error occured: Error: Cannot find module '/Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/chunk-HXRSFH6L.js' imported from /Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

I have tried the usual workarounds of including the library in the `ssr.external` array in vite.config.ts to no effect.

### How to reproduce

Run the dev server.

```
pnpm run dev
```

### Expected behavior

The build should not break when importing `@auth/solid-start`

**[Edit: Updated issue title and description to be indicative of the nature of the error. Not just limited to SSR builds]**

### PR DESCRIPTION
**Pull request by XantreDev**
Fixes: #9427

Tsup creates chunk file (adapters types also was missed), but is not added to `files` in package.json
```
    Directory: D:\Projects\open-source\next-auth\packages\frameworks-solid-start

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          09.02.2024    22:09                .turbo
d----          09.02.2024    22:10                dist
d----          09.02.2024    22:09                node_modules
d----          09.02.2024    22:07                scripts
d----          09.02.2024    22:07                src
d----          09.02.2024    22:07                test
-a---          09.02.2024    22:07             77 .gitignore
-a---          09.02.2024    22:10             37 adapters.d.ts
-a---          09.02.2024    22:10              0 adapters.js
-a---          09.02.2024    22:10            151 chunk-HXRSFH6L.js
-a---          09.02.2024    22:10           2040 client.d.ts
-a---          09.02.2024    22:10           1982 client.js
-a---          09.02.2024    22:10           5747 index.d.ts
-a---          09.02.2024    22:10           1666 index.js
-a---          09.02.2024    22:14           1289 package.json
-a---          09.02.2024    22:07           1698 README.MD
-a---          09.02.2024    22:07            229 tsconfig.json
-a---          09.02.2024    22:07            369 tsup.config.js
```

https://www.npmjs.com/package/@auth/solid-start/v/0.5.3?activeTab=code

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
We should drop `tsup` and just to what we do for other packages for building and use `tsc`. Check out the files field here as well.


https://github.com/nextauthjs/next-auth/blob/main/packages/core/package.json

**Comment by XantreGodlike** [comment]
Removed tsup. This is result of `npm publish --dry-run` command after build:
```
npm notice 📦  @auth/solid-start@0.5.3
npm notice === Tarball Contents ===
npm notice 1.7kB README.MD        
npm notice 80B   adapters.d.ts
npm notice 130B  adapters.d.ts.map
npm notice 11B   adapters.js
npm notice 2.1kB client.d.ts
npm notice 992B  client.d.ts.map
npm notice 3.0kB client.js
npm notice 5.7kB index.d.ts
npm notice 683B  index.d.ts.map
npm notice 6.9kB index.js
npm notice 1.2kB package.json
npm notice 41B   src/adapters.ts
npm notice 4.1kB src/client.ts
npm notice 7.1kB src/index.ts
npm notice === Tarball Details ===
npm notice name:          @auth/solid-start
npm notice version:       0.5.3
npm notice filename:      auth-solid-start-0.5.3.tgz
npm notice package size:  6.5 kB
npm notice unpacked size: 33.6 kB
npm notice shasum:        c625917ae28a017cdc40c472cee7335f446d2923
npm notice integrity:     sha512-lLN37TndHX2wi[...]JjlOsj5fW0r5w==
npm notice total files:   14
npm notice
npm WARN This command requires you to be logged in to https://registry.npmjs.org/ (dry-run)
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access (dry-run)
+ @auth/solid-start@0.5.3
```

**Comment by ndom91** [comment]
Hope you don't mind, I added the `pnpm-lock` updates that came from removing `tsup` as well as updates the `clean` npm script.

Anyway, LGTM now!

**Comment by ndom91** [comment]
@XantreGodlike should be fixed in `0.6.1` :pray: 

https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fsolid-start%400.6.1

**Pull request merged**
