### PR TITLE
fix: ensure Images are produced for discord

### PR DESCRIPTION
**Pull request by daggy1234**
0 Current Discord does not provide images if the avatar is the default one. This ensures a default avatar is generated.
Also ensures based on profile premium gifs are generated.

### CODE REVIEW

**Review by nyedidikeke — CHANGES_REQUESTED** [review]
Great work @Daggy1234 
Please consider following;
- Removal of redundant console.log() instances.
- `const = format` may be a single line.
- Replacing discordapp.com with discord.com based on #590.

Is `defaultAvatarNum` meant to represent default _Avatar Number_, _Avatar Name_ or something else?

**Comment by Daggy1234** [comment]
okay so I have a few comments to that 

- `console.log` will be removed 

- Single line is good

However the cdn is still `discordapp.com` and not `discord.com` therefore it does not make sense to change that

Also defaultAvatarNum is the Number! Not avatar Name.

**Review by nyedidikeke — CHANGES_REQUESTED** [review]
Thanks @Daggy1234 

> Also defaultAvatarNum is the Number! Not avatar Name.

`defaultAvatarNumber` is more readable and preferred.

**Comment by Daggy1234** [comment]
Will Change 👍🏽

**Comment by Daggy1234** [comment]
lmk if there is any update!

**Review by nyedidikeke — APPROVED** [review]

**Pull request merged**
