### PR TITLE
Update @auth/solid-start package

### PR DESCRIPTION
**Pull request by birkskyum**
Sync `auth/solid-start` with [solid-mediakit/auth](https://github.com/solidjs-community/mediakit/tree/main/packages/auth) to make it work with latest version of solid-start.

cc @OrJDev

### CODE REVIEW

**Comment by OrJDev** [comment]
From what i see here you deleted the docs comments so they need to be added but overall awesome great work.

**Comment by birkskyum** [comment]
I've added back these comments

**Comment by OrJDev** [comment]
@birkskyum updated mediakit auth to use latest version of Auth/core, this requires some major changes.

**Comment by birkskyum** [comment]
@OrJDev okay, nice. I seems like it would be a lot easier if you made a PR here, instead of me trailing behind your changes trying to keep things in up-to-date/ in-sync.

**Pull request closed without merging**
