### PR TITLE
fix(express): copy providers over from core during build

### PR DESCRIPTION
**Pull request by ndom91**
## ☕️ Reasoning

- Avoid installing `@auth/core` with the express client
- Copy providers over to `@auth/express` on build

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
`exports` and `files` need to be updated to include the providers:

https://github.com/nextauthjs/next-auth/blob/a9b9742a2b2d8dc54c3ec082b9a85376a55aabec/packages/frameworks-express/package.json#L6-L18

See: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/package.json

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
https://github.com/nextauthjs/next-auth/blob/main/turbo.json and ignore files should be verified too (gitignore, prettier, eslint)

**Comment by ndom91** [comment]
> `exports` and `files` need to be updated to include the providers:
> 
> https://github.com/nextauthjs/next-auth/blob/a9b9742a2b2d8dc54c3ec082b9a85376a55aabec/packages/frameworks-express/package.json#L6-L18
> 
> See: [`main`/packages/next-auth/package.json](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/package.json?rgh-link-date=2024-01-04T18%3A29%3A04Z)

Good catch! Updated

**Comment by ndom91** [comment]
> [`main`/turbo.json](https://github.com/nextauthjs/next-auth/blob/main/turbo.json?rgh-link-date=2024-01-04T18%3A30%3A31Z) and ignore files should be verified too (gitignore, prettier, eslint)

Will do this in another PR :+1:

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
