### PR TITLE
chore: update openid-client to latest version

### LINKED ISSUE #5639: Node.js 18 Support
### Question 💬

Node.js 18 LTS is starting, but this repository restricts the use of Node.18 in the engine in package.json.
Bugs for Node.js 18 seem to be all closed, is there anything blocking support?

I opened a discussion before, but now that LTS has started, I'll post it here as well.
https://github.com/nextauthjs/next-auth/discussions/5329

### How to reproduce ☕️

----

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

### PR DESCRIPTION
**Pull request by rafaelderolez**
## ☕️ Reasoning

I've upgraded `openid-client` to the latest version to make sure that it supports Node 18 as discussed in this issue: https://github.com/nextauthjs/next-auth/issues/5639. The PR (https://github.com/nextauthjs/next-auth/pull/5656) that closed the issue only removed the engine restrictions on `next-auth`'s end, but didn't upgrade the `openid-client` version.

The node versions for `openid-client` were updated in this commit: https://github.com/panva/node-openid-client/commit/9aefba30dcf0e312051e6844b35b06bc457488d5 as part of release [5.1.10](https://github.com/panva/node-openid-client/blob/main/CHANGELOG.md#5110-2022-09-28)

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/5639 (but for real this time)

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- (👆 FYI: None of these links work.)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by piersolenski** [comment]
+1

**Comment by panva** [comment]
`^5.1.0` (current openid-client dependency range) does not preclude from getting the latest openid-client version. Just run `npm upgrade` (or whatever package manager alternative) to update your dependency tree.

**Comment by rafaelderolez** [comment]
@panva My mistake then. Thanks for the quick reply & happy holidays!

**Comment by mschipperheyn** [comment]
This is not a good solution. By default using yarn install will fail with 
```
error openid-client@5.1.8: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.12.1"
error Found incompatible module
```

A workaround is to use "resolutions" to use the correct version. But it should not be necessary

**Pull request closed without merging**
