### PR TITLE
Add Notion Provider

### PR DESCRIPTION
**Pull request by harrison-broadbent**
## ☕️ Reasoning

Add a Notion Oauth provider to next-auth. 
This PR adds minor adjustments to #5761 

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [X] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE
Addresses: #5761 

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by harrison-broadbent** [comment]
@ndom91 hey this PR addresses #5761 
I had to make a new PR because I couldn't figure out how to commit to the old one. 
Is this OK?

**Comment by ndom91** [comment]
> @ndom91 hey this PR addresses #5761 
> I had to make a new PR because I couldn't figure out how to commit to the old one. 
> Is this OK?  

Yeah that's totally fine. I closed the original one, is that okay?

**Comment by harrison-broadbent** [comment]
> 

Yep no worries. Can you help me get this reviewed and merged?

**Comment by ndom91** [comment]
Yeah, sure thing. 

So I setup a test integration and that all worked well enough. One note here - I initially kept it set to "Internal Integration" in the notion integrations portal, as I thought I'd just use it for testing and it gives you a "Secret" value as well. But, this isn't possible. You *need* to select "Public Integration" to get an `oauth_id` and `oauth_secret`. Maybe note that in the docs as well :+1: 

In terms of functionality, the initial login process seemed to work just fine, I was forwarded to the notion "allow access" screen where I had to confirm that it wanted access to X pages. After accepting, I successfully got the user profile info printed in the console, but then I got a `JWEDecryptionFailed` error and the next-auth dev app said I still wasn't signed in.

See: 
image

**Comment by ndom91** [comment]
Hmm so after a second attempt, just refreshing the page and selecting "Login" -> "Login with Notion" one more time, it seemed to work perfectly :+1: :thinking:

**Comment by harrison-broadbent** [comment]
> Hmm so after a few more attempts it seemed to work perfectly every time 👍
> 
> image
> 
> (profile picture URL is fine in the `img` element in dev tools. Google just doesn't allow those requests from my browser sometimes)
> 
> @balazsorban44 @ThangHuuVu - I've added the test Notion provider keys to our 1P 👍 Not sure if yall want to wait and merge this in with other stuff that can be released together in the next minor release, ill leave it as is for now but code-wise seems good to go to me.
> 
> The Notion icon/theme is the same for light/dark since its just black/white brand colors.

Thanks for getting back to me @ndom91 . I've adjusted the doc to mention needing a public integration, and I'm going to test things out locally to try and replicate your JWE issue.

**Comment by harrison-broadbent** [comment]
Just added this to the doc: 

> Note: You need to select "Public Integration" on the configuration page to get an `oauth_id` and `oauth_secret`. Private integrations do not provide these details. 

I was able to get the example up and running without any issues. @ndom91 I wasn't able to replicate your problem. 
Re: when to merge, I would really like to start using this asap, is there any way we can merge this in quickly? (depending on the timeline for your next minor release bump). Would love to use this by today/tomorrow in another app. 

Cheers and thanks for being so responsive.

**Comment by ndom91** [comment]
> Just added this to the doc: 
> 
> > Note: You need to select "Public Integration" on the configuration page to get an `oauth_id` and `oauth_secret`. Private integrations do not provide these details. 
> 
> I was able to get the example up and running without any issues. @ndom91 I wasn't able to replicate your problem. 
> Re: when to merge, I would really like to start using this asap, is there any way we can merge this in quickly? (depending on the timeline for your next minor release bump). Would love to use this by today/tomorrow in another app. 
> 
> Cheers and thanks for being so responsive. 

Yeah I think the JWE issue might have been something with an existing old cookie or something on that local dev domain. All good, seemed to work just fine after that. 

In regard to release, I'll have to defer to @ThangHuuVu. But it shouldn't be too long 👍

**Comment by harrison-broadbent** [comment]
No worries cheers @ndom91 . @ThangHuuVu woild love your input

**Comment by harrison-broadbent** [comment]
Hey @ThangHuuVu @lluia just following up. @ndom91 seems pretty happy with this and i'd love to get it merged in quickly. any feedback or things you need from me before that happens? thanks

**Comment by ndom91** [comment]
@harrison-broadbent we're super busy with a larger thing at the moment, but can most likely get to this later this week or early next week at the latest :+1:

**Comment by TomYeoman** [comment]
Just went to open a PR for this myself, looks like we've already got one, wish I had looked at open PR's last night 😅.

A question; do you not need to pass a redirect URL to the auth URL as a query parameter? how does notion know to call development, or production?

I think it would be good for you to copy my notes in README regarding next-auth database integration "gotcha's", I will dump my full implementation, and README below 

```
import type { OAuthConfig, OAuthUserConfig } from "next-auth/providers";

export interface Person extends Record<string, any> {
  email: string;
}

// https://developers.notion.com/reference/user
export interface User extends Record<string, any> {
  object: "user" | "bot";
  id: string;
  type: string;
  name: string;
  avatar_url: null | string;
  person: Person;
  owner?: {
    type: "workspace" | "user";
    workspace: string;
  };
  workspace_name?: string | null;
}

export type Owner = {
  type: string;
  user: User;
};

// https://developers.notion.com/docs/authorization#step-4-notion-responds-with-an-access_token-and-some-additional-information
export interface NotionProfile extends Record<string, any> {
  access_token: string;
  bot_id: string;
  duplicated_template_id: string;
  owner?: Owner;
  workspace_icon: string;
  workspace_id: number;
  workspace_name: string;
}

const NOTION_HOST = "https://api.notion.com";
const NOTION_API_VERSION = "2022-06-28";

// Any config required that isn't part of the `OAuthUserConfig` spec should belong here
// For example, we must pass a `redirectUri` to the Notion API when requesting tokens, therefore we add it here
interface AdditionalConfig {
  redirectUri: string;
}

export default function NotionProvider<P extends NotionProfile>(
  options: OAuthUserConfig<P> & AdditionalConfig
): OAuthConfig<P> {
  return {
    id: "notion",
    name: "Notion",
    type: "oauth",
    token: {
      params: {
        grant_type: "authorization_code",
        clientId: options.clientId,
        clientSecret: options.clientSecret,
      },
      url: `${NOTION_HOST}/v1/oauth/token`,
    },
    userinfo: {
      url: `${NOTION_HOST}/v1/users`,
      // The result of this method will be the input to the `profile` callback. Custom request handler used (https://next-auth.js.org/configuration/providers/oauth)
      // As we need to do things such as pass the "Notion-Version" header, and the user ID to the user endpoint
      async request(context) {
        const profile = await fetch(`${NOTION_HOST}/v1/users/me`, {
          headers: {
            Authorization: `Bearer ${context.tokens.access_token}`,
            "Notion-Version": NOTION_API_VERSION,
          },
        });

        const {
          bot: {
            owner: { user },
          },
        } = await profile.json();

        return user;
      },
    },
    authorization: {
      params: {
        client_id: options.clientId,
        response_type: "code",
        owner: "user",
        redirect_uri: options.redirectUri,
      },
      url: `${NOTION_HOST}/v1/oauth/authorize`,
    },
    // `https://api.notion.com/v1/oauth/authorize?client_id=${options.clientId}&response_type=code&owner=user&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fnotion`
    async profile(profile, tokens) {
      return {
        id: profile.id,
        name: profile.name,
        email: profile.person.email,
        image: profile.avatar_url,
      };
    },
    style: {
      logo: "https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/notion.svg",
      logoDark:
        "https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/notion.svg",
      bg: "#fff",
      text: "#000",
      bgDark: "#fff",
      textDark: "#000",
    },
    options,
  };
}
```

README

``` 
---
id: notion
title: Notion
---

## Documentation

https://developers.notion.com/docs

## Configuration

https://www.notion.so/my-integrations

## Options

The **Notion Provider** comes with a set of default options:

- [Notion Provider options](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/notion.ts)

You can override any of the options to suit your own use case.

You must provide a `clientId` and `clientSecret` to use this provider, as-well as a redirect URI (due to this being required by Notion endpoint to fetch tokens, this is documented in the [notion provovider](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/notion.ts)).

## Example

```js
import NotionProvider from "next-auth/providers/notion";
...
providers: [
  NotionProvider({
    clientId: env.NOTION_CLIENT_ID,
    clientSecret: env.NOTION_CLIENT_SECRET,
    redirectUri: "http://localhost:3000/api/auth/callback/notion",
  }),
],
...
```

## Additional notes

If you're using the next auth database integration (in this case, we'll be using prisma + sqlite), there are some additional steps to follow.

1. Make sure your `Account` definition contains the extra fields that are returned by the access token endpoint, at time of writing this includes;

```
model Account {
  id                     String  @id @default(cuid())
  userId                 String
  type                   String
  provider               String
  providerAccountId      String
  bot_id                 String? // @db.Text
  workspace_name         String? // @db.Text
  workspace_icon         String? // @db.Text
  workspace_id           String? // @db.Text
  duplicated_template_id String? // @db.Text
  refresh_token          String? // @db.Text
  access_token           String? // @db.Text
  expires_at             Int?
  token_type             String?
  scope                  String?
  id_token               String? // @db.Text
  session_state          String?
  user                   User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
```

2. If you're using SQLITE, you will find the "owner" returned in the call to fetch access token is JSON, and is not supported for example by SQLITE,
   It reccomended you either remove it (as this code does), or you could stringify and store as text if you want https://github.com/nextauthjs/next-auth/issues/3818

```js
const adapter = {
  ...PrismaAdapter(prisma),
  linkAccount: ({ owner, ...data }: any) => {
    debugger
    return prisma.account.create({ data })
  },
}

export const authOptions: NextAuthOptions = {
  adapter,
  providers: [
    NotionProvider({
      clientId: env.NOTION_CLIENT_ID,
      clientSecret: env.NOTION_CLIENT_SECRET,
      redirectUri: "http://localhost:3000/api/auth/callback/notion",
    }),
  ],
}

export default NextAuth(authOptions)
```
```

**Comment by ThangHuuVu** [comment]
Sounds good, can you add the suggestion from @TomYeoman @harrison-broadbent 🙌?
Another thing: please update the list of provider in `.github/ISSUE_TEMPLATE/2_bug_provider.yml` as well

**Comment by harrison-broadbent** [comment]
@ThangHuuVu yep I can do that. Sorry I missed this! Just got back from holidays. I'll try to get this done over the weekend

**Comment by harrison-broadbent** [comment]
@ThangHuuVu just pushed those changes from @TomYeoman . 
Let me know what you think, thanks!

**Comment by ThangHuuVu** [comment]
Thank you @harrison-broadbent, I've resolved the conflicts and create a new PR #6567 to move these changes to under `@auth/core` since we're only accepting new providers there. Let's continue there, when merging that PR you will be added as a co-author 🙏

**Comment by shamoons** [comment]
When will this be available in next-auth?

**Pull request closed without merging**
