### PR TITLE
Add server-side call option

### LINKED ISSUE #1121: Allow server-side calls to use a different URL other than NEXTAUTH_URL
**Summary of proposed feature**

Allow server-side calls to use a different URL other than `NEXTAUTH_URL`.

**Purpose of proposed feature**

We'd like to use NextAuth in an environment where Pods running Next.js apps don't have access to call into `NEXTAUTH_URL`.

**Detail about proposed feature**

I am not sure - however, if you can give me a few pointers, I'd be happy to take a stab at this.

**Potential problems**

Not sure

**Describe any alternatives you've considered**

I cannot think of any

### PR DESCRIPTION
**Pull request by gergelyke**
**What**:

Closes https://github.com/nextauthjs/next-auth/issues/1121

**Checklist**:

- [x] Documentation
- [ ] Tests: N/A - couldn't find relevant test files, please let me know if I missed it!
- [x] Ready to be merged

### CODE REVIEW

**Comment by gergelyke** [comment]
if anyone wants to play around with it till it lands, it's published as `@gergelyke/next-auth@1.0.0`

**Comment by gergelyke-dd** [comment]
@iaincollins @balazsorban44 any thoughts folks?

**Comment by balazsorban44** [comment]
Please be patient 😌. We have seen it, no need to tag constantly. I think Iain has some thoughts on this matter. We will be back with an answer when we come to this. 😉 I'll have a discussion with Iain next week Friday. Have a great day!

**Comment by iaincollins** [comment]
FYI we have discussed this and I think this is broadly a great idea!

We have been taking our time as it may intersect with a few other issues, such as:

* #600
* #969
* #1121
* #1168

I don't think we have to solve all problems at once, but it's worth considering them so we can try and do it once, and avoid messing folks around with a breaking change in the API in the next release. :-)

I'd also like to create some space to bikeshed about the name `NEXTAUTH_URL_SERVER` in case anyone has any better ideas as it will be an API surface (I don't though!).

**Comment by gergelyke** [comment]
> FYI we have discussed this and I think this is broadly a great idea!
> 
> We have been taking our time as it may intersect with a few other issues, such as:
> 
> * #600
> * #947
> * #969
> * #1121
> * #1168
> 
> I don't think we have to solve all problems at once, but it's worth considering them so we can try and do it once, and avoid messing folks around with a breaking change in the API in the next release. :-)
> 
> I'd also like to create some space to bikeshed about the name `NEXTAUTH_URL_SERVER` in case anyone has any better ideas as it will be an API surface (I don't though!).

Awesome, thank you! Let me know if there is anything else you need from me - it's a super helpful project, so I'd be helpful to contribute more :)

**Comment by gergelyke** [comment]
Also, we've been using this fork for a week weeks now without any issues, so I can attest it works as expected

**Comment by gergelyke** [comment]
@iaincollins any thoughts on the next steps here?

**Comment by sethhoward-dd** [comment]
I've also forked this and am using it with this change in. Any issues that are blocking this from getting merged?

**Comment by balazsorban44** [comment]
Nothing particularly blocks this PR, we just want to make sure that user-facing APIs are meaningful changes and not thrown around carelessly. We haven't had the proper time yet to discuss this in a detailed manner, so it is therefore not merged yet. Iain and I soon will have a discussion about the currently open PRs and will probably look into this one as well and will try to come back with feedback. Until we decide feel free to use any fork providing this functionality 🙂

@gergelyke We currently changed our release flow (again 😬), so if you want to keep this PR alive, it would make the review process quicker if you could make the base `main`. That would probably result in a LOT of conflicts (this is totally my bad, sorry. Messed around with git when figuring out the new release flow), so the best option would actually be to close this PR, and reopen a new one against `main`. Again, sorry for the inconvenience! (PS: You may just want to wait for our decision anyway, so if we don't proceed/accept this PR you don't need to do unnecessary work.)

**Comment by gergelyke** [comment]
ok, I am sorry, I don't have the time to keep pushing for this - we'll keep using the fork for the time being

**Comment by balazsorban44** [comment]
I respect that! We will probably keep this in mind and you'll see when/if we implement anything to solve this :slightly_smiling_face:

**Comment by balazsorban44** [comment]
So we had to chat about it, and we decided that this was the least bad option, and we got on board with it. 😄 Hope it solves your problems @gergelyke! (And possibly others using Kubernetes etc.)

**Pull request closed without merging**
