### PR TITLE
Feature: Send information from the request to `sendVerificationRequest`

### PR DESCRIPTION
**Pull request by acoreyj**
## ☕️ Reasoning

Send more info to the `sendVerificationRequest` function that could be relevant to sending the email verification request.

In my case I wanted the user agent to have a message like "This login was requested using using Firefox on Windows" which can help a user verify that they are the one making the request.

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [X] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by balazsorban44** [comment]
I think we should send a standard `Request` instance like here instead:

https://github.com/nextauthjs/next-auth/blob/d72296220623ba9ff17eaff4792a5bd880c9cd9a/packages/core/src/lib/routes/callback.ts#L276

**Comment by acoreyj** [comment]
> I think we should send a standard `Request` instance like here instead:
> 
> https://github.com/nextauthjs/next-auth/blob/d72296220623ba9ff17eaff4792a5bd880c9cd9a/packages/core/src/lib/routes/callback.ts#L276

Good idea, I made the change

**Review by ThangHuuVu — APPROVED** [review]
LGTM 🙏

**Comment by ThangHuuVu** [comment]
closed via  #8071

**Pull request closed without merging**
