### PR TITLE
feat: allow to disable client-side redirect for email provider

### PR DESCRIPTION
**Pull request by yannicktian**
**What**:

In case the user is using the Email provider, make it possible to disable the redirection after the response from the server.

**Why**:

Example: To make a user signin or signup flow more fluid, it may be desirable to handle email signin without a page reload.

**How**:

The Email Provider has been added to the list of the providers that allow disabled redirection
`canRedirectBeDisabled = isCredentials || isEmail`

**Checklist**:

- [ ] Documentation
- [x] Tests (Tested it locally so far, through the developer application, looking good there)
- [ ] Ready to be merged

Also related:

- Issues/PRs: #1192 #989 #1219
- Discussions: https://github.com/nextauthjs/next-auth/discussions/754

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks! Will check the functionality locally myself, until then, there is a little request. Could you update the docs at https://github.com/nextauthjs/next-auth/blob/main/www/docs/getting-started/client.md#using-the-redirect-false-option

to mention that redirect can also be disabled for the email provider from now on?

**Comment by huynhminhcanh** [comment]
Cảnh huynh

**Comment by huynhminhcanh** [comment]
> Cảnh huynh

Paypal

**Review by lucalves — APPROVED** [review]

**Comment by yannicktian** [comment]
@balazsorban44 I've updated the docs
image

Here is a screenshot of the email page
image

**Review by HisWife2287 — APPROVED** [review]

**Comment by balazsorban44** [comment]
Sorry for the late discovery, but this should have been opened against the `main` branch, not `canary`! I'll close this PR as opening PRs against `canary` and change base to `main` introduces way too much merge conflicts and crashes with our release flow. SO SORRY FOR THIS! 🙏 could you please create a new PR with these changes against `main`?

**Comment by yannicktian** [comment]
@balazsorban44 Here you go: https://github.com/nextauthjs/next-auth/pull/1416
Sorry I saw somewhere that PR should be opened against the `canary` branch..

**Pull request closed without merging**
