### PR TITLE
chore(docs): update adapters import in drizzle schemas

### PR DESCRIPTION
**Pull request by kholisrag**
## ☕️ Reasoning

Update drizzle schemas to correct module

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Nice catch, thanks!

**Comment by ndom91** [comment]
Ah wait sorry, I misread the file in which this was changed. 

This is actually correct. As a user you should never have to install `@auth/core`. You should be able to import these types from the client based on your framework of choice, i.e. from `next-auth/adapters` or `@auth/sveltekit/adapters`, etc.

**Comment by kholisrag** [comment]
whats the correct way? I use the adapter seem not working

**Comment by ndom91** [comment]
> @ndom91 
> 
> whats the correct way? I use the adapter seem not working
> 
> ```
> Cannot find module '@auth/sveltekit/adapters' or its corresponding type declarations.ts(2307)
> ```

Whoops sorry, try `@auth/sveltekit/adapter`

**Pull request closed without merging**
