### PR TITLE
Made `ctxOrReq` optional in `getCsrfToken()`

### LINKED ISSUE #1847: `getCsrfToken()` requires an empty object when called on `client` side
**Summary of proposed feature**
When calling `getCsrfToken()` or `getSession()` on client side, TS complains to provide at-least 1 argument, which is an empty object `{}`. Although documentation doesn't say any such thing.
Can we remove passing an empty object in those function?

**Purpose of proposed feature**
Just to make it less confusing when using nextauthjs with Typescript

**Additional content**
image
image
image

PS: `"next-auth": "^3.15.9"`
Notify if fixed in newer versions. Thanks!

### PR DESCRIPTION
**Pull request by typedashutosh**
**What**: Made `ctxOrReq` optional in `getCsrfToken()`

**Why**: Because in `client` it was unnecessary, but when used with typescript, TS makes unnecessary complaints.

**How**: Just adding a `?` at param of the function. `getCsrfToken(ctxOrReq?: ctxOrReq)`

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      

fixes #1847

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]
Thank you! 🙂

**Comment by typedashutosh** [comment]
The same problem occurs with `getSession()` asking for empty object. Should I do it too?
😀

**Comment by balazsorban44** [comment]
please do! 🙏😄

**Comment by typedashutosh** [comment]
Done. #1851

**Pull request merged**
