### PR TITLE
feat(adapters): support multi-project schema

### PR DESCRIPTION
**Pull request by juliusmarminge**
## ☕️ Reasoning

This PR adds support for [multi-project schemas](https://orm.drizzle.team/docs/goodies#multi-project-schema) to the drizzle adapter. Without this change, if users were using a custom table function, the adapter wouldn't find the tables which would lead to errors like this:

CleanShot 2023-08-08 at 23 59 12@2x

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by juliusmarminge** [comment]
@balazsorban44  I'm unsure how to add tests for this, should I just duplicate the existing test suites and add one that uses table prefixes for each dialect?

Also couldn't decide on good position in docs, maybe just a `<Callout>` saying like: "If you're using multi-project schemas, you can pass your table function as a second argument" ?

**Comment by balazsorban44** [comment]
Thanks for looking into this! 

Yeah, just duplicating the tests should be fine. :+1:

`<Callout>` in Docusaurus looks like this:

```
:::info
If you're using multi-project schemas, you can pass your table function as a second argument
:::
```

This sounds good to me.

**Comment by juliusmarminge** [comment]
Not sure how your doc generation works, but I can't see the callout on here:

https://auth-docs-m00920uou-authjs.vercel.app/reference/adapter/drizzle#parameters

Should be good to go otherwise, tests are in as well

**Comment by balazsorban44** [comment]
I think it was because of some Turbo caching. Hopefully addressed via https://github.com/nextauthjs/next-auth/commit/28d8d4894d227ae990f56b51d8055a7f0ba98ad3

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
It's released now! https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fdrizzle-adapter%400.2.0

**Comment by juliusmarminge** [comment]
> It's released now! [@auth/drizzle-adapter@0.2.0](https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fdrizzle-adapter%400.2.0)

Awesome! Thanks for the quick expedition :)

**Pull request merged**
