### PR TITLE
fix: github stars on wrong navbar item

### PR DESCRIPTION
**Pull request by Just-Moh-it**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Just a change

Before:

image

After:

image

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: [Changes made in this pr broke the github star tag](https://github.com/nextauthjs/next-auth//commit/1954258a0a5ef214eadf8a12180349cc043c57e3)

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
So I can confirm that the issue does appear when visiting the docs via `authjs.dev`. However they do not under `next-auth.js.org`.

However, when visiting your preview URL link from Vercel, I only see the following:

> image

It doesn't show the star count at all :thinking:

**Comment by Just-Moh-it** [comment]
@ndom91 My bad, had used the wrong selector function. Should be working now!

**Review by ThangHuuVu — CHANGES_REQUESTED** [review]
Great attempt, could you help revert the unecessary changes @Just-Moh-it? 🫶

**Comment by ndom91** [comment]
@Just-Moh-it would you like to merge this still? If so, please clean up the unnecessary changes or maybe opening a new PR would be easier at this point :blush:

**Pull request closed without merging**
