### PR TITLE
Adds Sandpack integration

### PR DESCRIPTION
**Pull request by danilowoz**
Screenshot 2022-02-08 at 10 12 19

Hey @ndom91, here's a PR integrating Sandpack into the documentation, hope it works well.
Any questions, please hesitate to ask 😄

### CODE REVIEW

**Comment by ndom91** [comment]
So first off thanks a ton for this PR! 

This is almost exactly what I had though, other than the css file, so no idea what I was doing wrong. Maybe it was just my machine or that particular page I was trying to add it to :sweat_smile:

Either way, thanks again :heart:

@balazsorban44 here's the preview link to that page - https://next-auth-gngu2qkce-nextauthjs.vercel.app/sandpack

**Comment by danilowoz** [comment]
Great! 🎉

BTW, it's in our roadmap to support an official plugin to Docusarus, so if you have any feedback, feature requests and/or suggestions, please ping in this [issue](https://github.com/codesandbox/sandpack/issues/322). We still don't have a proper scope for this task, so we're looking for more details to come up with the requirements.

**Comment by ndom91** [comment]
@balazsorban44 I say lets merge this as is for now. The new page is kind of hidden, in the sense that its not in any of the sidebars. 

I also tried to literally copy each file out of here, install the same (newer) version of Sandpack in my branch and it still errored out with that message haha. Upon cloning dani's fork though, it worked on my machine :sweat_smile: 

So if we merge this, I can continue on with sandpack from there. Getting some nice interactive demos of our custom themes / custom signin pages up and running :+1:

**Review by 0ubbe — APPROVED** [review]
Looks good from my side 👍🏽

**Review by 0ubbe — CHANGES_REQUESTED** [review]
There's a [conflict currently](https://github.com/nextauthjs/next-auth/runs/5229023381?check_suite_focus=true) on `yarn.lock` that needs to be resolved 💭 ; re-generating the lock file should solve it:
```
$ rm -f yarn.lock
$ yarn
```

**Comment by danilowoz** [comment]
Sorry @lluia, I might have missed the notification from this PR. Just fixed the conflict

**Review by 0ubbe — APPROVED** [review]

**Review by 0ubbe — CHANGES_REQUESTED** [review]
The build in **Vercel** is still breaking, can you re-generate the lock file?

**Comment by ndom91** [comment]
Everything seems to be passing now :tada: 

Thanks again @danilowoz. I will merge this now and continue using sandpack to give users an opportunity to play with our custom signin/signout pages right in the docs. I'll post back here if I get something nice together, maybe it can act as a good Docusaurus + Sandpack example.

**Comment by ndom91** [comment]
@danilowoz do you possibly have a Next.js sandpack example of someone elses? I can't seem to get a basic Next.js app loaded with custom files / custom dependencies and such.

WIP PR here in case you're curious: https://github.com/nextauthjs/next-auth/pull/4169

**Pull request merged**
