### PR TITLE
chore(docs): Describe how to avoid Next.js route handler auth type conflict with explicit type casting

### PR DESCRIPTION
**Pull request by SongDerrick**
## ☕️ Reasoning

No description to avoid next.js type check build failure when explicit type casting is omitted.

## 🧢 Checklist

- [x] Documentation
- [] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ThangHuuVu** [comment]
What error are you running to?

**Comment by SongDerrick** [comment]
```typescript
Type error: Route "app/api/protected/route.ts" has an invalid export:
  "unknown" is not a valid POST return type:
    Expected "void | Response | Promise<void | Response>", got "unknown".Type error: Route "app/api/protected/route.ts" has an invalid export:
  "unknown" is not a valid POST return type:
    Expected "void | Response | Promise<void | Response>", got "unknown".
```

**Comment by SongDerrick** [comment]
It runs into next build type errors

**Comment by balazsorban44** [comment]
This rather sounds like a bug. We don't want to recommend `as any`. Please open a bug report instead.

**Pull request closed without merging**
