### PR TITLE
feat(ts): Export types related to email and credential providers

### PR DESCRIPTION
**Pull request by jgeurts**
**What**: Export types for Email and Credential providers

**Why**: Simplify custom adapter code

**How**: Added `export` keyword before types/interfaces in providers.d.ts

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      

Related: #1649

### CODE REVIEW

**Review by 0ubbe — COMMENTED** [review]
Thanks for the PR @jgeurts 💚 . To have a bit more context, could you explain what are the problems you're trying to address when exporting these types ( _as maybe there's no need_ )?

Bear in mind that the actual types still live at [**DefinitivelyTyped**](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-auth) and the types here are part of a [migration that is WIP](https://github.com/nextauthjs/next-auth/issues/1649) (_so even if we merge these updates, you won't be able to benefit from them just yet_ 😌)

**Comment by jgeurts** [comment]
I have a [custom adapter](https://github.com/minarets/website/blob/main/minarets-api/auth/index.ts) that defines functions for verification requests. Currently, I duplicate the type definitions, but it would be handy to import them from next-auth. I’ll add a PR to DefinitelyTyped in the coming week, but figured I’d start here in case this goes through before I make the other pr.  Hope that helps!

**Review by 0ubbe — APPROVED** [review]
Sounds good 😊 , I think we can merge here and no need to raise the PR on **DefinitivelyTyped**.

**Comment by balazsorban44** [comment]
Would wait to merge until we reviewed #1690

**Comment by balazsorban44** [comment]
As far as I can tell, all these will be redundant/are addressed in #1690, so closing. Tell me if something is missing still!

**Pull request closed without merging**
