### PR TITLE
fix(docs): drizzle setup docs

### LINKED ISSUE #8406: Drizzle Adapter - wrong import file.
### What is the improvement or update you wish to see?

[DrizzleAdapter()](https://authjs.dev/reference/adapter/drizzle#drizzleadapter) 
In file `pages/api/auth/[...nextauth].ts` on line: 4, the  `{ db }` is imported from the wrong file `"./schema"`, because the `function db` doesn't exsist in that file. 

### Is there any context that might help us understand?

Normally in a nextjs folder structure:
It should import from `src/db/index.js` file, instead of `src/db/schema.js`.  
where the contents of `src/db/index.js` are mostly: 

```
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'

const connectionString = process.env.DATABASE_URL!
const client = postgres(connectionString)
export const db = drizzle(client);```

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/adapter/drizzle

### PR DESCRIPTION
**Pull request by devdatkumar**
fixes #8406

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
Maybe it's my lack of experience with Drizzle, but it seems to be the example `schema.ts` in the docs is also missing that `db` export, right? 

Should we add something like this to the bottom of the `schema.ts` variants?

```ts
...

const sql = postgres(connectionString, { max: 1 })
export const schema = { users, accounts, sessions, verificationTokens }

export const db = drizzle(sql, {
  schema,
})
```

**Comment by devdatkumar** [comment]
I find this as a more optimum solution. [scroll to the very botton, and look at the index.ts file](https://orm.drizzle.team/kit-docs/quick),  I have tested this solution, and it effectively migrates data to the database. However, there seems to be a compatibility issue with the Drizzle adapter, likely due to an error in the `DrizzleAdapter`. However
code below seems to be the right solution for the `index.ts` file.

```
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

const connectionString = process.env.DATABASE_URL;
const sql = postgres(connectionString!, { max: 1 });
export const db = drizzle(sql);

await migrate(db, { migrationsFolder: "drizzle" });

await sql.end();
```

**Comment by devdatkumar** [comment]
> I find this as a more optimum solution. [scroll to the very botton, and look at the index.ts file](https://orm.drizzle.team/kit-docs/quick), I have tested this solution, and it effectively migrates data to the database. However, there seems to be a compatibility issue with the Drizzle adapter, likely due to an error in the `DrizzleAdapter`. However code below seems to be the right solution for the `index.ts` file.
> 
> ```
> import { drizzle } from "drizzle-orm/postgres-js";
> import { migrate } from "drizzle-orm/postgres-js/migrator";
> import postgres from "postgres";
> 
> const connectionString = process.env.DATABASE_URL;
> const sql = postgres(connectionString!, { max: 1 });
> export const db = drizzle(sql);
> 
> await migrate(db, { migrationsFolder: "drizzle" });
> 
> await sql.end();
> ```

I will also commit this code to the docs, please review and let me know.

**Comment by ndom91** [comment]
Thanks for your interest, but since the Drizzle adapter is being rewritten, we're going to just take the docs from in that PR (which match the new code, etc.). See https://github.com/nextauthjs/next-auth/pull/10479/files#diff-9a268be1c786115f6a6c31bc783cb0739546c8c2e81f9e92b923f7c2380c0067

Thanks!

**Pull request closed without merging**
