### PR TITLE
fix(adapters): use built-in `is()` to identify db type

### LINKED ISSUE #8339: DrizzleAdapter with Vercel Postgres not supported yet?
### Question 💬

Trying the new DrizzleAdapter with 
vercel
 postgres gives me:
``` Error: Unsupported database type in Auth.js Drizzle adapter.```

I tried different ways to initialize the db but to no success.

Am I doing something wrong or is it actually not supported yet?

### How to reproduce ☕️

Use drizzle + sveltekit + vercel postgres. Try using the adapter: DrizzleAdapter(drizzleDb) in a hooks.ts file

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

### PR DESCRIPTION
**Pull request by balazsorban44**
Closes #8339

### CODE REVIEW

**Comment by SSardorf** [comment]
Yes! Let's get this merged ASAP - HMR fixes such as the following also causes NextAuth to complain. I believe your PR fixes that too
```ts
import * as schema from './schema'
import { PostgresJsDatabase, drizzle } from 'drizzle-orm/postgres-js'
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import postgres from 'postgres'
export * from 'drizzle-orm'
export * from './schema'

if (!process.env.DATABASE_URL) {
  throw new Error('Missing DATABASE_URL')
}

let db: PostgresJsDatabase<typeof schema>
if (process.env.NODE_ENV === 'development') {
  db = singleton('db', () => {
    if (!process.env.DATABASE_URL) {
      throw new Error('Missing DATABASE_URL')
    }
    const migrationClient = postgres(process.env.DATABASE_URL, { max: 1 })
    migrate(drizzle(migrationClient), {
      migrationsFolder: 'app/db/migrations',
    })
    const queryClient = postgres(process.env.DATABASE_URL)
    return drizzle(queryClient, { schema })
  })
}
if (process.env.NODE_ENV === 'production') {
  const queryClient = postgres(process.env.DATABASE_URL)
  db = drizzle(queryClient, { schema })
}
// Borrowed/modified from https://github.com/jenseng/abuse-the-platform/blob/2993a7e846c95ace693ce61626fa072174c8d9c7/app/utils/singleton.ts

export function singleton<Value>(name: string, value: () => Value): Value {
  const yolo = global as any
  yolo.__singletons ??= {}
  yolo.__singletons[name] ??= value()
  return yolo.__singletons[name]
}

export { db }

//export const db = drizzle(queryClient, { schema })
```

**Comment by balazsorban44** [comment]
@SSardorf I released `@auth/drizzle-adapter@0.0.0-manual.acabcfb4` could you test it? In case you use Vercel Postgres, can you check if this also fixes that? :pray:

**Comment by SSardorf** [comment]
@balazsorban44 
getting the following error, even though I don't use mysql
```
../../node_modules/.pnpm/@auth+drizzle-adapter@0.0.0-manual.acabcfb4_nodemailer@6.9.4/node_modules/@auth/drizzle-adapter/index.js:18:0
Module not found: Package path ./mysql-core/index.js is not exported from package /Users/ssardorf/dev/12s12m/verk/node_modules/.pnpm/node_modules/drizzle-orm (see exports field in /Users/ssardorf/dev/12s12m/verk/node_modules/.pnpm/node_modules/drizzle-orm/package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./lib/auth.tsx
./app/api/auth/[...nextauth]/route.tsx
```

**Comment by balazsorban44** [comment]
Sorry about that, published a new release `@auth/drizzle-adapter@0.0.0-manual.ab481298`

**Comment by SSardorf** [comment]
> @auth/drizzle-adapter@0.0.0-manual.ab481298

Yep! This one doesn't throw the error - Works fine for me

**Comment by SSardorf** [comment]
Note: I do not use Postgres Vercel - So I cannot confirm that this one fixes that. But based on my assumptions and understanding of the error, I would assume it does indeed fix it

**Pull request merged**
