### PR TITLE
chore(docs): Run `pnpm format:write`

### PR DESCRIPTION
**Pull request by k-taro56**
## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
Hmm how is this happening so often lately? I know you improved the application of our prettier rules, maybe we need to tie that in with a pre-commit hook or something? 

Well either way, thanks for staying on top of it 🙏

**Review by ndom91 — APPROVED** [review]

**Comment by k-taro56** [comment]
@ndom91 
The only Prettier rules you changed are the Tailwind (and Svelte) ones, so I don't think it matters much 🤔
I think they simply don't know what formatting should be applied
In the meantime, let's install a pre-commit hook

**Comment by ndom91** [comment]
> @ndom91 
> The only Prettier rules you changed are the Tailwind (and Svelte) ones, so I don't think it matters much 🤔
> I think they simply don't know what formatting should be applied
> In the meantime, let's install a pre-commit hook

Yeah no I meant the change you made so that it actually checks prettier now in general, you know what I mean? 

But yeah a hook sounds good 👍 

I've been using `simple-git-hooks` for my projects for the last year or two, I really like it. It's nice n simple and lightweight and doesn't fuck your `.git/hooks` like Husky does 😂

**Comment by k-taro56** [comment]
> > @ndom91
> > The only Prettier rules you changed are the Tailwind (and Svelte) ones, so I don't think it matters much 🤔
> > I think they simply don't know what formatting should be applied
> > In the meantime, let's install a pre-commit hook
> 
> Yeah no I meant the change you made so that it actually checks prettier now in general, you know what I mean?
> 
> But yeah a hook sounds good 👍
> 
> I've been using `simple-git-hooks` for my projects for the last year or two, I really like it. It's nice n simple and lightweight and doesn't fuck your `.git/hooks` like Husky does 😂

Have I made such a change?👀

Also I've created a pr with lefthook which is modern and can run commands only for the staged files, is it nicer to replace it with simple-git-hook?

**Comment by ndom91** [comment]
@k-taro56 haha i meant this [enable prettier plugins](https://github.com/nextauthjs/next-auth/pull/11623) one. 

But yeah lets please go with [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks), it seems to be a bit more simple and straight forward and the config can be put into a `package.json` key as well :pray:

**Pull request merged**
