### PR TITLE
fix(prisma): replace select with include for user relation query

### PR DESCRIPTION
**Pull request by mcorbelli**
This PR fixes an issue where Prisma's `select` statement was incorrectly used to query the `user` relation in the `Account` model. Since `select` is only applicable for scalar fields, this caused Prisma to throw an error:  
`Unknown field 'user' for select statement on model 'Account'`. 

The fix replaces `select: { user: true }` with `include: { user: true }`, which correctly fetches the `user` relation and resolves the issue.

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Hmm yeah that's definitely not right. I guess we didn't require the result of that function for anything critical 😅 

Tests pass, so LGTM 🙏

**Comment by mcorbelli** [comment]
When will it be included in the npm release? Is there a date yet?

**Comment by mcorbelli** [comment]
When will it be included in the npm release? Is there a date yet? @ndom91

**Comment by ndom91** [comment]
I don't have a date or even a guesstimate unfortunately. All I can say is that it'll be a part of the next release 😅

**Comment by mcorbelli** [comment]
@balazsorban44 Are there any updates regarding the upcoming release with this fix?

**Comment by mcorbelli** [comment]
news?

**Pull request merged**
