### PR TITLE
Included new BattleNet OAuth endpoints

### PR DESCRIPTION
**Pull request by JoeyKanaly**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Blizzard has added support for new OAuth endpoints that do not require the region for US, EU, TW, and KR.
[Blizzard Documentation](https://develop.battle.net/documentation/guides/using-oauth)

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
I couldn't find any info in their docs, but do you know if their `/userinfo` endpoint returns the `email` address? I see we set it to `null` in the provider here, but we'd like to always have a full user profile (id, name, email, image) returned.

**Comment by JoeyKanaly** [comment]
No it only returns sub, id, and battletag

**Comment by ThangHuuVu** [comment]
@JoeyKanaly could you update the PR by rebasing? we no longer use the .md files anymore

**Comment by JoeyKanaly** [comment]
> @JoeyKanaly could you update the PR by rebasing? we no longer use the .md files anymore

All done

**Comment by ndom91** [comment]
@JoeyKanaly could you fix the merge conflict and remove the change to `packages/next-auth`? That's the `v4` release which we aren't shipping updates like this to anymore. Thanks!

**Pull request merged**
