### PR TITLE
fix(react): initialize session without loading state

### PR DESCRIPTION
**Pull request by hboylan**
New `SessionProvider` accepts a session from the server without calling `getSession`, but is still initialized as "loading".

## Reasoning 💡

Session is already set so it should not be in the loading state.

## Checklist 🧢

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
Nice catch! Thank you for the additional tests! (We do plan to add them soon for the client together with @lluia in the near future though)

**Comment by hboylan** [comment]
No problem! Happy to help out.

Could you help release v4.0.0-next.14 for this? 😄

**Comment by balazsorban44** [comment]
:grimacing: Should have been a squash merge... Will try to release manually

**Comment by hboylan** [comment]
Ah, that's my bad. I formatted the PR name, but not the commit. 🤦🏻

**Comment by balazsorban44** [comment]
`v4.0.0-next.14`  is out

**Comment by hboylan** [comment]
Looks like something went wrong with the build. 😞 
```
Unable to resolve path to module 'next-auth/react'.
```

**Pull request merged**
