### PR TITLE
fix(drizzle): update schemas & refactor

### PR DESCRIPTION
**Pull request by realmikesolo**
I have updated schemas and types with `email` being nullable in `users` table. Also, I have bumped Drizzle ORM & Drizzle Kit versions and refactored tests.

## ☕️ Reasoning

As already discussed in [discord channel](https://discord.com/channels/1200116961590399008/1231534836859146241), `email` column should be nullable.

### CODE REVIEW

**Comment by realmikesolo** [comment]
I have added `id` to `fixtures` because NextAuth always pass value for `id`, so I think it should be in `fixtures` to provide correct test cases.

**Comment by ndom91** [comment]
@realmikesolo why are there so many changes? :thinking:  That can't all be from the `pnpm-lock.yaml`, right?

**Comment by realmikesolo** [comment]
Hello @ndom91! I have fixed `pnpm-lock.yaml`

**Comment by ndom91** [comment]
Nice, looks much better! 

Out of curiosity, do the non-PK columns really all need that `isPrimaryKey: false`? 🤔

**Comment by realmikesolo** [comment]
Hey @ndom91. I have updated type, so if we don't need `isPrimaryKey: false` for non-PK columns. But I have faced this issue `Cannot find module '@auth/core/adapters' or its corresponding type declarations` and it is a bit strange for me because I didn't change any dependencies related to `auth/core`. Could you please check it?

**Comment by ndom91** [comment]
> Hey @ndom91. I have updated type, so if we don't need `isPrimaryKey: false` for non-PK columns. But I have faced this issue `Cannot find module '@auth/core/adapters' or its corresponding type declarations` and it is a bit strange for me because I didn't change any dependencies related to `auth/core`. Could you please check it?

Yeah I don't have time today, but this weekend I can definitely take a closer look and hopefully get this merged. The lock file definitely looks much better!

**Comment by ndom91** [comment]
> Hey @ndom91. I have updated type, so if we don't need `isPrimaryKey: false` for non-PK columns. But I have faced this issue `Cannot find module '@auth/core/adapters' or its corresponding type declarations` and it is a bit strange for me because I didn't change any dependencies related to `auth/core`. Could you please check it?

Where are you running into this? I was abel to run all the tests successfully still

**Comment by realmikesolo** [comment]
> > Hey @ndom91. I have updated type, so if we don't need `isPrimaryKey: false` for non-PK columns. But I have faced this issue `Cannot find module '@auth/core/adapters' or its corresponding type declarations` and it is a bit strange for me because I didn't change any dependencies related to `auth/core`. Could you please check it?
> 
> Where are you running into this `@auth/core/adapters` issue? I was abel to run all the tests successfully still

I was facing this issue during the build. It might be problem on my local setup then. Thank you for your time

**Pull request merged**
