### PR TITLE
feat(provider): Add Azure Active Directory B2C

### PR DESCRIPTION
**Pull request by vladimir-e**
Adds a provider for authenticating with Azure OAuth 2.0 API.

Update: 
[How to Configure Azure AD B2C Authentication with Next.js](https://benjaminwfox.com/blog/tech/how-to-configure-azure-b2c-with-nextjs)

### CODE REVIEW

**Comment by balazsorban44** [comment]
Hi @vladimir-e, and thanks for this PR.
Isn't the official name for this `Azure B2C` or `Azure Active Directory B2C`?
It would probably be easier for people to find this provider if we rename it. Do you agree?

**Comment by vladimir-e** [comment]
> Hi @vladimir-e, and thanks for this PR.
> Isn't the official name for this `Azure B2C` or `Azure Active Directory B2C`?
> It would probably be easier for people to find this provider if we rename it. Do you agree?

Hi @balazsorban44 . I agree. I can push the change.

How about we name it "Azure Active Directory B2C" and use short `AzureAD` and `azure-ad` in the code and file names?

**Comment by balazsorban44** [comment]
@vladimir-e I think we should call it `azure-b2c` or `azure-ad-b2c`

Referring to the [blog post](https://benjaminwfox.com/blog/tech/how-to-configure-azure-b2c-with-nextjs) you linked to:
> Please note that Azure AD B2C is not the same thing as Azure AD. Azure AD B2C (also referred to here as Azure B2C) is an identity & access management solution specifically for customer facing applications.

**Comment by ndom91** [comment]
Hey thanks for the addition @vladimir-e!  

Also consider adding your blog post to our list of tutorials [here](https://github.com/nextauthjs/next-auth/blob/canary/www/docs/tutorials.md) :tada:

**Comment by vladimir-e** [comment]
> Hey thanks for the addition @vladimir-e!
> 
> Also consider adding your blog post to our list of tutorials [here](https://github.com/nextauthjs/next-auth/blob/canary/www/docs/tutorials.md) 🎉

Hey @ndom91, I actually found that blogpost there, under the "Other tutorials and explainers" section.

**Comment by ndom91** [comment]
Ah okay, I should have actually read the document I suggest you edit fully :rofl:

**Comment by vladimir-e** [comment]
Hey @balazsorban44 , I renamed the provider and verified that it still works. Thanks for the suggestion.

I don't really like the long text:

Screen Shot 2020-12-06 at 3 18 10 PM

But I think it's fine, since it can be configured:
```
  const azure = Providers.AzureADB2C({
    name: 'Azure AD',
    // ...
  });
```

**Comment by balazsorban44** [comment]
So sorry @vladimir-e, I merged this to the wrong branch. I have to revert it. could you open another PR to `canary`? I'll merge it immediatelly

**Pull request merged**
