### PR TITLE
Added tutorial on testing pages with authentication by setting next-a…

### PR DESCRIPTION
**Pull request by joostvanwollingen**
**What**:
This PR adds a tutorial page about testing pages with authentication by setting a session-token cookie.

**Why**:
The current docs/tutorials only mention testing with https://www.npmjs.com/package/cypress-social-logins, which doesn't support all authentication providers supported by NextAuth.js yet, and, in my experience, makes test scenario's unnecessarily slow/long. I'm not sure if this is the best way to go about it, but in my workflow the approach of seeding a session-token to the DB and setting that in Cypress before visiting any page worked faster and circumvented setting up credentials with an authentication provider. For tests that are not focused on the authentication flow itself, this allows for writing focused functional tests.

If this doesn't belong here, or is not in-line with the vision of the project, feel free to close the PR, just figured I'd share my approach.

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
@iaincollins is working on the built-in tests, so I assume he has some thoughts around this.

**Comment by djejaquino** [comment]
I am very interested in the ability to set the session token using from my IDP's  `/connect/token` response `access_token`. Is that doable already? Because I tried that and NextAuth just clears it during load.

**Comment by timohermans** [comment]
> I am very interested in the ability to set the session token using from my IDP's `/connect/token` response `access_token`. Is that doable already? Because I tried that and NextAuth just clears it during load.

The reason for this is that you must set a authorization flow token. You cannot, say, put a token you receive from a grant_type password token.

I'm actually curious how to get a token programmatically that enables testing. @joostvanwollingen do you have an example for this?

**Comment by balazsorban44** [comment]
Why can't you just mock out the `/api/auth/session` request with something like [`Mock Service Worker`](https://mswjs.io/)? That is the endpoint that functions like `useSession` and `getSession` contacting to get a valid session from the backend.

**Pull request closed without merging**
