### PR TITLE
adding support for Okta as a provider

### PR DESCRIPTION
**Pull request by mdemin914**
Hey, I am digging this package! We need support for Okta for our purposes. I think this should do it. Fairly small and simple addition. Hope it helps!

### CODE REVIEW

**Comment by LoriKarikari** [comment]
Thanks @mdemin914!

**Comment by iaincollins** [comment]
Oh fantastic! Thank you @mdemin914 !

**Comment by LoriKarikari** [comment]
I also like that you added the Okta domains into the options. I'm going to change this for Auth0 too.

**Comment by iaincollins** [comment]
Just wanted to let folks know this is now live, published as `next-auth@2.0.0-beta.62`

**Pull request merged**
