### PR TITLE
docs: add codesandbox custom signin page examples

### LINKED ISSUE #3837: Interactive Examples
### Description 📓

Add interactive examples to pages docs

https://sandpack.codesandbox.io/

### How to reproduce ☕️

Add examples

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

### PR DESCRIPTION
**Pull request by ndom91**
## Reasoning 💡

Added interactive codesandbox embeds for the custom page examples.

Unfortunately I couldn't get their new fancy `Sandpack` embed working yet (See issue: https://github.com/codesandbox/sandpack/issues/359), however I got a normal `iframe` based embed working for all 3 signin page types (OAuth, Credential, Email).

Here are the codesandboxes themselves:

- https://codesandbox.io/s/next-auth-example-credential-signin-pcc6k
- https://codesandbox.io/s/next-auth-example-oauth-signin-2h6ej
- https://codesandbox.io/s/next-auth-example-email-signin-pyce6

The email one doesn't work 100% yet, cause it needs an adapter to even show the signin page. I was thinking about adding a little dummy `sqlite` adapter, but we don't seem to have one of those anymore :shrug:

Each codesandbox opens to the appropriate custom signin page (`oauth-sign.jsx`, `credential-signin.jsx`, etc.) as well as a second tab with `[...nextauth].js` open. 

**EDIT**: It seems like every few times, even the working examples throw some random error. These _should_ work though. Maybe its just because I've been reloading them so often from different origins, etc. Obviously OAuth signin with the example providers won't fully execute because theres no `clientId` / `clientSecret` provided here, but the signin page at least loads so that the user can play with it.

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

@balazsorban44 should we hide / remove the original code example panel? Maybe we can put it under a small `<summary> <detail /> </summary>` fold out.

image

More screenshots:

image

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
The CodeSandbox examples should only include the bare minimum code necessary to showcase a custom page. Remove any files that are unnecessary (eg components, layouts, pages). This will also make it easier to keep it up to date. (I would use `"next-auth": "latest"` in `package.json`)

Let's add the Credentials Provider to the custom page. Actually, I think the sandbox could simply use the code from https://github.com/nextauthjs/next-auth/tree/main/packages/next-auth/src/core/pages

Let's use TypeScript

**Comment by balazsorban44** [comment]
Could we put the "Sign In" and "Sign Out" theming examples next to each other under https://next-auth-git-ndom91-pagessandpack-interactive-demos-nextauthjs.vercel.app/configuration/pages#theming

**Comment by ndom91** [comment]
@balazsorban44 what do you mean by

> "Let's add the Credentials Provider to the custom page. Actually, I think the sandbox could simply use the code from https://github.com/nextauthjs/next-auth/tree/main/packages/next-auth/src/core/pages"

The credentials provider to which custom page?

And the second part of that, you linked to our built-in basic pages, but aren't these codesandbox examples supposed to be about showing the custom pages? Or do you want to have another codesandbox showing our built-in pages and how the user can play around with the `theme` settings, for example?

**Comment by ndom91** [comment]
Closing in favor of https://github.com/nextauthjs/next-auth/pull/4169

**Pull request closed without merging**
