### PR TITLE
chore(docs): clean up missing `npm2yarn` and other formatting

### PR DESCRIPTION
**Pull request by maxproske**
## ☕️ Reasoning

Adds some missing `npm2yarn`, `import type` annotations, and other mostly harmless consistency issues in the docs (eg. Documentation/Docs/docs -> documentation).

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [X] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
@maxproske thanks for this, this is great!

There's a small issue though that's preventing it from building. Can you see the Vercel build logs in their comment above? Or is that not publically visible? I dont remember

Anyway, the first one is:

```
`npm-to-yarn` package can convert only npm commands to all package managers. Found: npx @edgedb/generate edgeql-js
```

So in the `docs/pages/getting-started/adapters/edgedb.mdx` file.

That `npm2yarn` plugin is very picky I've found. It'll only accept a few inputs for conversion.

Anyway, no big deal, lets get those squared away and we can merge this! :pray:

**Comment by maxproske** [comment]
Thanks, @ndom91! Reverted the change, that should fix the issue. Your remediation instructions were super helpful, since I can't access the Vercel build logs.

**Comment by ndom91** [comment]
Well in that case, here's the second build issue 😅 

Looks like `NextResponse` is actually used as a value in `app/api/cron/route.ts`, so you can't import it as a type.

**Comment by maxproske** [comment]
Thanks @ndom91, running `pnpm build:docs` did the trick. 

Thank you for the extra humour and making contributing fun!

**Review by ndom91 — APPROVED** [review]
Awesome, looks good now! Thanks :heart:

**Pull request merged**
