### PR TITLE
Branding and docs

### PR DESCRIPTION
**Pull request by iaincollins**
I thought I'd add a logo and tweak the CSS a little.

I'm not sure how to add meta tags to pages with docusaurs v2, I wanted to add Facebook and Twitter images for when people share links to the site, but seems to be influx. Any tips on how to do that appreciated!

### CODE REVIEW

**Comment by ndom91** [comment]
So I found a a place in the docs to add a meta image ([source](https://v2.docusaurus.io/docs/theme-classic/#meta-image)).

There's also a `@docusaurus/head` component which is basically just a wrapper around `react-helmet`. I added an `Seo` component and put a basic description in there, you can expand it with whatever other `og:` meta tags you want.

**Comment by ndom91** [comment]
Also I edited the formatting of the serverless function example on the homepage to avoid the horizontal scrollbar.

**Review by ndom91 — APPROVED** [review]

**Review by LoriKarikari — APPROVED** [review]

**Comment by iaincollins** [comment]
> Also I edited the formatting of the serverless function example on the homepage to avoid the horizontal scrollbar.

:D

Oh that you for the above and for that, that was bugging me too and kept meaning bto get to it!

**Comment by iaincollins** [comment]
@ndom91 Love how you split the SEO stuff out, thank you!

**Pull request merged**
