### PR TITLE
fix(signin.tsx): set type of built-in email sign-in input to "email" and add "required" attribute for browser validation

### PR DESCRIPTION
**Pull request by raulmarindev**
## Reasoning 💡

Currently, the built-in sign-in page has the wrong type (text) for the input for emails when using
the magic link provider. Because of this, a user can enter whatever value they want in that input and click on the "Sign in with Email". By switching the type to be "email" we can make use of the browser-provided validation and users will be
forced to use properly formed emails addresses in order to sign in.

image

image

Additionally, the built-in sign-in page doesn't have the required attribute for the input for emails when using the magic link provider. Because of this, a user is able to submit the form without entering a value. By adding the "required" attribute we can make use of the browser-provided validation and users will be forced to provide a value in order to sign in.
## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Good catch, yeah, I think we can also make it required. 👍

**Review by 0ubbe — APPROVED** [review]
Good catch 💚

**Comment by lluia** [comment]
@raulmarindev lets make it `required` also as per @balazsorban44 hint 👍🏽

**Comment by raulmarindev** [comment]
@lluia Thank you both, I've added the required attribute

**Review by 0ubbe — APPROVED** [review]
Nice 💯

**Pull request merged**
