### PR TITLE
add /api/auth/tokens endpoint to return oauth tokens

### PR DESCRIPTION
**Pull request by tomvoss**
A method to retrieve OAuth tokens from the database was needed in order to use them with third-party APIs as Bearer tokens.

As @iaincollins requested in the [original pull request](https://github.com/nextauthjs/next-auth/pull/425#issuecomment-665584387), I have opened a new pull request against `main` on the official organization account for next-auth.

### CODE REVIEW

**Comment by iaincollins** [comment]
Thanks @tomvoss! I'm not quite sure what has gone on all with the commit history in the meantime but am happy to sort that out by rebasing / merging to another branch first :-)

Will follow on this in the next view days. Much appreciated!

**Comment by eatrocks** [comment]
I hope it's okay if I request a status update on token refreshing? Feel free to tell me "where to go" ;) if appropriate. Thanks in advance.

**Comment by tgandrews** [comment]
@iaincollins is there anything I can do to help getting this merged?

**Comment by balazsorban44** [comment]
Hi @tomvoss! I am goint through PRs and trying to get them merged. There are some conflicts with this one. Could you please look at them and fix, so we can get this out on our new `canary` branch?

**Comment by tomvoss** [comment]
I'll try to find some time to look at this, but it might not happen for some time. If someone else could jump in and help out it would be much appreciated.

**Comment by balazsorban44** [comment]
Hi there @tomvoss! I incorporated your changes to #951. Do you want me to keep this open , in case you change your mind or find some time to finish this? Feel free to check out my approach in the other PR, and give feedback if you want. (it's a work in progress as well)

**Pull request closed without merging**
