### PR TITLE
Add auth0

### PR DESCRIPTION
**Pull request by LoriKarikari**
updated some wrong copy paste stuff in docs

### CODE REVIEW

**Comment by ndom91** [comment]
Whoops sorry, did I pull the trigger a bit too quick on that last one as well? Haha

**Comment by iaincollins** [comment]
I just wanted to come back and say is epic BTW!

**Comment by LoriKarikari** [comment]
The docs or the Auth0 provider? 😂

**Comment by iaincollins** [comment]
Both! 😁

I don't think it actually registered with me you'd added Auth0, I was tired and just parsed it as oAuth!

**Pull request merged**
