### PR TITLE
Allow SvelteKit 2 as peer dependency

### PR DESCRIPTION
**Pull request by jjonescz**
## ☕️ Reasoning

SvelteKit 2 was released: https://svelte.dev/blog/sveltekit-2

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by smart** [comment]
Do you know if this is working with sveltekit2? I'm getting this error when I attempt to build 

Error: Cannot read values from $env/dynamic/private while prerendering (attempted to read env.AUTH_SECRET). Use $env/static/private instead

**Comment by notramo** [comment]
@smart
It helps if you are checking `building` from '$app/environment' and if it's `true`, then don't call `SvelteKitAuth()`, e.g.:

```javascript
export const handle = building ? undefined : SvelteKitAuth({ /* ... */});
```

It can be fixed by disallowing any access while building - short circuit the `SvelteKitAuth()` function, to not access `env.AUTH_SECRET`. I don't know how it would affect prerendering the built-in UI pages (or if those should be prerendered at all).

**Comment by smart** [comment]
I just found a workaround for myself. Setting both the AUTH_SECRET and AUTH_TRUST_DOMAIN  options in the SvelteKitAuth() in hooks. When they aren't explicitly set there, the library falls back and uses $env/dynamic/private

**Comment by iammoonman** [comment]
I haven't had any issues between this and SK2, building or otherwise.

**Review by ThangHuuVu — APPROVED** [review]
LGTM, thanks! one test is failing but it's unrelated, I'll look into it later.

**Comment by tamutus** [comment]
Looks like the version number also needs changing for it to be registered by npm

**Pull request merged**
