### PR TITLE
docs(callbacks): don't use `signIn` for redirects

### PR DESCRIPTION
**Pull request by nicholaschiang**
Updates the callback documentation to specify that you shouldn't use the `signIn` callback for arbitrary redirects. Instead, use the `callbackUrl` option or the redirect callback.

## Reasoning 💡

I was previously using the `signIn` callback to redirect to a relative path (as mentioned [here](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl)). I didn't realize that doing so canceled the current sign in and that I should instead use [the redirect callback](https://next-auth.js.org/configuration/callbacks#redirect-callback).

## Checklist 🧢

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]
I guess it could have been more clear from the get-go. Thanks for the PR!

**Comment by nicholaschiang** [comment]
@balazsorban44 Is there a way that I can decide where to redirect the user (after a successful sign-in) based on their profile data? For example, I might want to redirect users with a certain email address domain name to a specific page.

**Comment by balazsorban44** [comment]
in case if it's OAuth, you could redirect them to a page or api route like /dashboard or /api/user. 

then use useSession or getSession respectively to redirect them to your profile specific url?

For email or credentials:

https://next-auth.js.org/getting-started/client#using-the-redirect-false-option

then do `router.push` to wherever you want.

**Comment by nicholaschiang** [comment]
@balazsorban44 Yeah, that's the current workaround (just redirect to the `/feed` page and then in the `/feed` page, detect if the user has any subscriptions selected, and if not, redirect to `/subscriptions`). I was wondering if there was a more performant fix that avoids the double redirect (i.e. redirect directly to `/subscriptions` from the `pages/api/auth/[...nextauth].ts` route).

**Comment by balazsorban44** [comment]
we don't have the user info before the OAuth flow is executed, so I'm not even sure how or what a good way should be. feel free to open a feature request, possibly with a suggested solution and the intent of helping to implement it.

**Pull request merged**
