### PR TITLE
Update typescript.md

### PR DESCRIPTION
**Pull request by mongolyy**
Remove unused import statement.

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

None

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Not sure if this was a bug in earlier TS versions, but when I wrote that documentation, the augmentation only worked with those imports. 🤔 Can you verify it's not the case anymore?

**Comment by mongolyy** [comment]
@balazsorban44 
Thank you for your comment.

> Can you verify it's not the case anymore?

I'm trying to verify with [this example](https://github.com/nextauthjs/next-auth/tree/main/apps/example-nextjs).
It seems that the behavior of requiring/not requiring import is different from my other project, perhaps due to different transpile options in TypeScript.
I will look into this a bit more.

**Comment by balazsorban44** [comment]
Closing as seems to be stale. Happy to re-open if it's justified.

**Comment by mongolyy** [comment]
Thanks for the close.
I tried using the example and could not find a situation where import would not be needed.

TypeScript documentation also describes import, so I think we should leave the current description as it is.
https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Pull request closed without merging**
