### PR TITLE
Volatile MongoDB Adapter

### LINKED ISSUE #8411: MongoDB Adapter with non-persistent connections
### Description 📓

Please add an option that instead of accepting a `clientPromise` will accept a function generating a `clientPromise` - each handler should create its own client and close it at the end.

Many lambda/cloud-functions environments don't handle the persistent connections very well (i.e Vercel).

### How to reproduce ☕️

https://github.com/orgs/vercel/discussions/1211

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

### PR DESCRIPTION
**Pull request by oren-z0**
## ☕️ Reasoning

A MongoDB adapter with dynamic creation & close functions, for environments that don't support long living connections to databases (lambdas, cloud-functions, etc.).

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/8411

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Let's add an option to the exisiting MongoDB adapter, instead of creating a new one.

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Let's add an option to the existing MongoDB adapter, instead of creating a new one.

**Comment by simonecervini** [comment]
@balazsorban44 I agree that it would be better to integrate this into the existing adapter. What about this diff?

I can also open a separate PR if it can help to land this faster.

```diff
diff --git a/packages/adapter-mongodb/src/index.ts b/packages/adapter-mongodb/src/index.ts
index 28909723..e7d46964 100644
--- a/packages/adapter-mongodb/src/index.ts
+++ b/packages/adapter-mongodb/src/index.ts
@@ -40,6 +40,10 @@ export interface MongoDBAdapterOptions {
    * The name you want to give to the MongoDB database
    */
   databaseName?: string
+  /**
+   * TODO: Add description
+   */
+  onClose?: (client: MongoClient) => Promise<void>
 }
 
 export const defaultCollections: Required<
@@ -144,126 +148,189 @@ export function _id(hex?: string) {
  * ```
  **/
 export function MongoDBAdapter(
-  client: Promise<MongoClient>,
+  client: Promise<MongoClient> | (() => Promise<MongoClient>),
   options: MongoDBAdapterOptions = {}
 ): Adapter {
   const { collections } = options
   const { from, to } = format
 
-  const db = (async () => {
-    const _db = (await client).db(options.databaseName)
+  const createDb = async () => {
+    const _client = await (typeof client === "function" ? client() : client)
+    const _db = _client.db(options.databaseName)
     const c = { ...defaultCollections, ...collections }
     return {
       U: _db.collection<AdapterUser>(c.Users),
       A: _db.collection<AdapterAccount>(c.Accounts),
       S: _db.collection<AdapterSession>(c.Sessions),
       V: _db.collection<VerificationToken>(c?.VerificationTokens),
+      onClose: async () => {
+        if (options.onClose) {
+          await options.onClose(_client)
+        }
+      },
     }
-  })()
+  }
 
   return {
     async createUser(data) {
       const user = to<AdapterUser>(data)
-      await (await db).U.insertOne(user)
-      return from<AdapterUser>(user)
+      const db = await createDb()
+      try {
+        await db.U.insertOne(user)
+        return from<AdapterUser>(user)
+      } finally {
+        await db.onClose()
+      }
     },
     async getUser(id) {
-      const user = await (await db).U.findOne({ _id: _id(id) })
-      if (!user) return null
-      return from<AdapterUser>(user)
+      const db = await createDb()
+      try {
+        const user = await db.U.findOne({ _id: _id(id) })
+        if (!user) return null
+        return from<AdapterUser>(user)
+      } finally {
+        await db.onClose()
+      }
     },
     async getUserByEmail(email) {
-      const user = await (await db).U.findOne({ email })
-      if (!user) return null
-      return from<AdapterUser>(user)
+      const db = await createDb()
+      try {
+        const user = await db.U.findOne({ email })
+        if (!user) return null
+        return from<AdapterUser>(user)
+      } finally {
+        await db.onClose()
+      }
     },
     async getUserByAccount(provider_providerAccountId) {
-      const account = await (await db).A.findOne(provider_providerAccountId)
-      if (!account) return null
-      const user = await (
-        await db
-      ).U.findOne({ _id: new ObjectId(account.userId) })
-      if (!user) return null
-      return from<AdapterUser>(user)
+      const db = await createDb()
+      try {
+        const account = await db.A.findOne(provider_providerAccountId)
+        if (!account) return null
+        const user = await db.U.findOne({ _id: new ObjectId(account.userId) })
+        if (!user) return null
+        return from<AdapterUser>(user)
+      } finally {
+        await db.onClose()
+      }
     },
     async updateUser(data) {
       const { _id, ...user } = to<AdapterUser>(data)
+      const db = await createDb()
+      try {
+        const result = await db.U.findOneAndUpdate(
+          { _id },
+          { $set: user },
+          { returnDocument: "after" }
+        )
 
-      const result = await (
-        await db
-      ).U.findOneAndUpdate({ _id }, { $set: user }, { returnDocument: "after" })
-
-      return from<AdapterUser>(result!)
+        return from<AdapterUser>(result!)
+      } finally {
+        await db.onClose()
+      }
     },
     async deleteUser(id) {
       const userId = _id(id)
-      const m = await db
-      await Promise.all([
-        m.A.deleteMany({ userId: userId as any }),
-        m.S.deleteMany({ userId: userId as any }),
-        m.U.deleteOne({ _id: userId }),
-      ])
+      const db = await createDb()
+      try {
+        await Promise.all([
+          db.A.deleteMany({ userId: userId as any }),
+          db.S.deleteMany({ userId: userId as any }),
+          db.U.deleteOne({ _id: userId }),
+        ])
+      } finally {
+        await db.onClose()
+      }
     },
     linkAccount: async (data) => {
       const account = to<AdapterAccount>(data)
-      await (await db).A.insertOne(account)
-      return account
+      const db = await createDb()
+      try {
+        await db.A.insertOne(account)
+        return account
+      } finally {
+        await db.onClose()
+      }
     },
     async unlinkAccount(provider_providerAccountId) {
-      const account = await (
-        await db
-      ).A.findOneAndDelete(provider_providerAccountId)
-      return from<AdapterAccount>(account!)
+      const db = await createDb()
+      try {
+        const account = await db.A.findOneAndDelete(provider_providerAccountId)
+        return from<AdapterAccount>(account!)
+      } finally {
+        await db.onClose()
+      }
     },
     async getSessionAndUser(sessionToken) {
-      const session = await (await db).S.findOne({ sessionToken })
-      if (!session) return null
-      const user = await (
-        await db
-      ).U.findOne({ _id: new ObjectId(session.userId) })
-      if (!user) return null
-      return {
-        user: from<AdapterUser>(user),
-        session: from<AdapterSession>(session),
+      const db = await createDb()
+      try {
+        const session = await db.S.findOne({ sessionToken })
+        if (!session) return null
+        const user = await db.U.findOne({ _id: new ObjectId(session.userId) })
+        if (!user) return null
+        return {
+          user: from<AdapterUser>(user),
+          session: from<AdapterSession>(session),
+        }
+      } finally {
+        await db.onClose()
       }
     },
     async createSession(data) {
       const session = to<AdapterSession>(data)
-      await (await db).S.insertOne(session)
-      return from<AdapterSession>(session)
+      const db = await createDb()
+      try {
+        await db.S.insertOne(session)
+        return from<AdapterSession>(session)
+      } finally {
+        await db.onClose()
+      }
     },
     async updateSession(data) {
       const { _id, ...session } = to<AdapterSession>(data)
-
-      const updatedSession = await (
-        await db
-      ).S.findOneAndUpdate(
-        { sessionToken: session.sessionToken },
-        { $set: session },
-        { returnDocument: "after" }
-      )
-      return from<AdapterSession>(updatedSession!)
+      const db = await createDb()
+      try {
+        const updatedSession = await db.S.findOneAndUpdate(
+          { sessionToken: session.sessionToken },
+          { $set: session },
+          { returnDocument: "after" }
+        )
+        return from<AdapterSession>(updatedSession!)
+      } finally {
+        await db.onClose()
+      }
     },
     async deleteSession(sessionToken) {
-      const session = await (
-        await db
-      ).S.findOneAndDelete({
-        sessionToken,
-      })
-      return from<AdapterSession>(session!)
+      const db = await createDb()
+      try {
+        const session = await db.S.findOneAndDelete({
+          sessionToken,
+        })
+        return from<AdapterSession>(session!)
+      } finally {
+        await db.onClose()
+      }
     },
     async createVerificationToken(data) {
-      await (await db).V.insertOne(to(data))
-      return data
+      const db = await createDb()
+      try {
+        await db.V.insertOne(to(data))
+        return data
+      } finally {
+        await db.onClose()
+      }
     },
     async useVerificationToken(identifier_token) {
-      const verificationToken = await (
-        await db
-      ).V.findOneAndDelete(identifier_token)
+      const db = await createDb()
+      try {
+        const verificationToken = await db.V.findOneAndDelete(identifier_token)
 
-      if (!verificationToken) return null
-      const { _id, ...rest } = verificationToken
-      return rest
+        if (!verificationToken) return null
+        const { _id, ...rest } = verificationToken
+        return rest
+      } finally {
+        await db.onClose()
+      }
     },
   }
 }

```

**Comment by ndom91** [comment]
@simonecervini yes please open a new PR 😊

**Pull request closed without merging**
