### PR TITLE
fix(surrealdb): bump minimum `surrealdb.js` version

### LINKED ISSUE #9701: adapter surrealdb broken with new version
### Adapter type

Custom adapter

### Environment

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 80.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 17.2.1
  npmPackages:
    @auth/core: ^0.22.0 => 0.22.0 
    @auth/surrealdb-adapter: ^0.2.10 => 0.2.10 
    next: 14.1.0 => 14.1.0 
    next-auth: 5.0.0-beta.5 => 5.0.0-beta.5 
    react: ^18 => 18.2.0 
    surrealdb.js: ^0.11.0 => 0.11.0 

### Reproduction URL

https://github.com/ManAnRuck/next-auth-example

### Describe the issue

current version does not work (tested in this repository also with updated SurrealDB.js version)

btw: surreal is missing in the list of adapters in this issue template

### How to reproduce

read reproduction instructions from readme in reproduction url reposiory

### Expected behavior

new SurrealDB.js version should work (pass tests)

### PR DESCRIPTION
**Pull request by ManAnRuck**
## ☕️ Reasoning

[**surrealdb.js**](https://github.com/surrealdb/surrealdb.js) library has multiple ([0.10.0](https://github.com/surrealdb/surrealdb.js/releases/tag/v0.10.0), [0.11.0](https://github.com/surrealdb/surrealdb.js/releases/tag/v0.11.0)) braking changes to version 0.11.0 since current used version 0.9.1.

make adjustments to use current version (0.11.0) of SurrealDB.js

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

 
Fixes: https://github.com/nextauthjs/next-auth/issues/9701

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks, I dropped the version section. we should do this consistently for all adapters if we decide to have this info. the adapter is still below v1 though, so for now it's not that helpful info. your package manager will warn you anyway.

could you fix the lock file merge conflict? 🙏

**Comment by ManAnRuck** [comment]
> Thanks, I dropped the version section. we should do this consistently for all adapters if we decide to have this info. the adapter is still below v1 though, so for now it's not that helpful info. your package manager will warn you anyway.
> 
> could you fix the lock file merge conflict? 🙏

@balazsorban44 All right, thank you very much! 
Sounds logical to me, as many things can still change quickly with this package under v1.

The merge conflicts are also solved now.

**Comment by ruohki** [comment]
Great and i thought iam stupid for not beeing able to get it working. Ofc when i want to tryout things they are broken xD

**Comment by ManAnRuck** [comment]
> Great and i thought iam stupid for not beeing able to get it working. Ofc when i want to tryout things they are broken xD

if you don't want to clone this repo locally and link local I published a test package
`pnpm/yarn/npm install @mananruck/surrealdb-adapter@0.4.0-alpha.1 --registry=https://npm.pkg.github.com`

**Comment by ManAnRuck** [comment]
@balazsorban44 anything else todo for me to merge this pr?

**Comment by ndom91** [comment]
All tests are passing, looks good to me

**Review by martinschaer — APPROVED** [review]

**Pull request merged**
