### PR TITLE
chore(docs): update `azure-ad.md`

### PR DESCRIPTION
**Pull request by Xorlent**
Added required API Permissions grant step for Azure AD/Entra SSO setup.

## ☕️ Reasoning

Azure AD/Entra SSO provider setup was missing the API Permissions granting step.

## 🧢 Checklist

- [X] Documentation
- [X ] Tests
- [X ] Ready to be merged

## 🎫 Affected issues

N/A Discovered omission during deployment.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
LGTM :+1:

**Comment by ndom91** [comment]
Ah sorry, was a bit too quick. Can you make this change against the `main` branch. Not `v4`? 

Thanks!

**Comment by Xorlent** [comment]
> Ah sorry, was a bit too quick. Can you make this change against the `main` branch. Not `v4`?
> 
> Thanks!

Guess I was in the wrong branch - yes, will do.  Thanks Nico!

**Comment by Xorlent** [comment]
Okay, it looks like these help docs are missing from main.  I'm not sure how to proceed.

**Comment by ndom91** [comment]
@Xorlent yeah the document is embedded in the `ts` file, you can find it here: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/azure-ad.ts

**Pull request closed without merging**
