### PR TITLE
feat(adapters): add redis adapter

### LINKED ISSUE #8285: Support for generic Redis adapter
### Description 📓

Hi team! Great project! I'm curious if there's any interest in developing an adapter for generic Redis connections that could work with Redis or Google Memory Store. I was able to adapt the Upstash Redis adapter into a custom Redis using "ioredis" as the Node.js client but it seems like an adapter that could benefit the Auth.js community. I have used https://github.com/tj/connect-redis extensively before for Node.js sessions and this could fit a similar use case.

### How to reproduce ☕️

References:
 - https://authjs.dev/reference/adapter/upstash-redis
 - https://ably.com/blog/migrating-from-node-redis-to-ioredis
 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

### PR DESCRIPTION
**Pull request by nbifrye**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

This adds redis adapter that is independent of upstash.
This adapter requires the RedisJSON module.

You can see [differences](https://github.com/nextauthjs/next-auth/pull/9431/commits/33529227aa76079d77df9089f5fec5a941c6c9ef) with the existing upstash-redis-adapter.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/8285

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
We're debating replacing a lot of these KV storage adapters with 1 that targets [unstorage](https://unstorage.unjs.io/) as it has drivers for all popular KV stores. Instead of separate ones for Upstash, Redis, Cloudflare KV, etc. etc..

See: https://github.com/nextauthjs/next-auth/pull/8805

**Comment by nbifrye** [comment]
@ndom91 Using unstorage to add support for various KV storage is a great idea for me!
This [small change](https://github.com/nbifrye/next-auth/pull/1/commits/0f483c3197b578af7dde7e59a64a843cba040d4d) worked to replace upstash redis adapter with unstorage. Support for RedisJSON module may also be possible using `getItemRaw/setItemRaw` of unstorage custom adaper.

**Comment by ndom91** [comment]
@nbifrye okay great, you mind if we close this PR then and we can all collaborate on the unstorage one in the PR i linked?

**Comment by nbifrye** [comment]
Yes, let's do that.

**Pull request closed without merging**
