### PR TITLE
#540 custom adapter initialization options

### PR DESCRIPTION
**Pull request by D10221**
Build custom adapter with the same mechanics as as the 'default' adapter
Provide 'backwards' compatibility with current implementation

Not sure about the testing strategy here, made a demo I'll try to attach it

sorry about the wrong reference , I meant #540  not #544 .... 
I renamed the branch  but git picked it up anyway :)

### CODE REVIEW

**Comment by D10221** [comment]
Test-case/demo : https://github.com/D10221/nextauth_custom_adapter_initialization

**Comment by D10221** [comment]
Small update to the demo, I realized I labeled them backwards, 
... no my day :(

**Comment by iaincollins** [comment]
Hi there,

Following discussion in #540 I'm still not convinced of the need for this change or that it's something we want to do.

As it says in the [options documentation](https://next-auth.js.org/configuration/options#adapter), the 'database' option is an alternative to specifying an adapter and should only be used instead (not as well as) an adapter. This is very much by design to steer users in the right direction and avoid confusion.

Not all adapters can even use a connection string - the built in Prisma adapter, for example, only takes an object - but all adapters can take an object and may have 0 or more arguments. Even some people using the default adapter will be using an object and not the database prop, as it's the only way to pass some more advanced options through to TypeORM.

[As per the default adapter documentation](https://next-auth.js.org/schemas/adapters#typeorm-adapter), the default adapter is the TypeORM adapter, the following configuration options are exactly equivalent:

```js
database: {
  type: 'sqlite',
  database: ':memory:',
  synchronize: true
}
```

```
adapter: Adapters.Default({
  type: 'sqlite',
  database: ':memory:',
  synchronize: true
})
```

```js
adapter: Adapters.TypeORM.Adapter({
  type: 'sqlite',
  database: ':memory:',
  synchronize: true
})
```

If you can support all these forms, it's possible to support any adapter. There is nothing special about the default adapter, the database option is just a shortcut. An adapter should take all the arguments it needs that are specific to it as arguments when it is constructed. These arguments can accessed when `getAdapter()` is invoked (which is why it they are designed this way).

Anything that is possible with the default adapter is possible with a custom adapter.

If you want to share a configuration object, you can easily place it in a file and pass it to the Adapter when it is initialised.

**Comment by D10221** [comment]
Thanks!

I just thought o would be nice to instantiate the current 'default' adapter with different parameters at different times.
Depending on how it is build, and when, 
it could open many opportunities, 
And with this small change, it was very clean IMMO.

But I  do understand, and You don't have to agree :) 
Its all good if you don't like it, 
Or think doesn't align with the current vision

Thanks again

**Comment by iaincollins** [comment]
Thanks for being understanding!

I don't hate this and appreciate it's a small change, I'm just a bit reluctant to introduce complexity and another way of doing something (given it how it already feels like there are a lot of moving pieces in NextAuth.js) without exploring possibilities a bit more and really having a grasp on what unique behaviour it enables or if it's something that could be handled by taking different approach with the exiting functionality.

I'll try reading #540 again in a bit and looking at the example to see if I get it.

(I feel this would be a lot easier to discuss and understand in room a whiteboard! :-)

**Comment by D10221** [comment]
Hi, 
I think we can close this.
Found a solution that doesn't require any change from your side.
Not that pretty, ... but it seems to work. :) 

Thank you for your time and attention !

_If you are curious, it can be found [here](https://github.com/D10221/next-auth-cli/blob/master/next-auth-cli/test/next-auth-external-adapter.js), it goes away with customizing the models/initializing/re-initializing/and being swapable, without retyping the original adapter, as I said not that pretty :)  _

**Pull request closed without merging**
