### PR TITLE
add(db): Add support for Fauna DB

### PR DESCRIPTION
**Pull request by Joev-**
Adds support for [FaunaDB](https://fauna.com/) as a database adapter.

I have attempted to mimic the existing adapter implementations, whilst still keeping to the Fauna style where possible. Fauna refs are used to reference related data, although I have opted for storing just the 'id' rather than a ref object. All timestamps are stored as Time objects in UTC (not sure if this will cause any problems down the line?).

I am not very experienced with Fauna and FQL, so if anyone does have suggestions, I am all ears :-) 

There is some initial setup required by the user to create collections and indexes, although I was not sure if this could be fit into the `syncrhonize` option somehow. 

```
CreateCollection({name: 'account'});
CreateCollection({name: 'session'});
CreateCollection({name: 'user'});
CreateCollection({name: 'verification_reset'});

CreateIndex({
    name: 'account_by_provider_account_id',
    source: Collection('account'),
    unie: true,
    terms: [
        { field: ['data', 'providerId'] },
        { field: ['data', 'providerAccountId'] }
    ]
});

CreateIndex({
    name: 'session_by_token',
    source: Collection('session'),
    unie: true,
    terms: [
        { field: ['data', 'sessionToken'] }
    ]
});

CreateIndex({
    name: 'user_by_email',
    source: Collection('user'),
    unie: true,
    terms: [
        { field: ['data', 'email'] }
    ]
});

CreateIndex({
    name: 'verification_reset_by_token',
    source: Collection('verification_reset'),
    unie: true,
    terms: [
        { field: ['data', 'token'] }
    ]
});

```

### CODE REVIEW

**Comment by waptik** [comment]
Hi! I'd like to know what's the difference between this PR and [that](https://github.com/nextauthjs/next-auth/pull/686)?
Also, do you have a working example? Because, i tried the one i linked before but as there were few instructions how to set things up, i found my way around but its session doesn't correlate with that of nextauth's.

**Comment by Joev-** [comment]
Hi @waptik, I hadn't seen that other PR until after submitting this one unfortunately. It looks very similar, but I cannot speak of its implementation as I have not tested it.

I don't have a working example, but am using this in one of my apps. My [...nextauth].js file contains the following configuration

```
const faunaClient = new faunadb.Client({
  secret: process.env.FAUNADB_SECRET_KEY,
});

const options = {
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      scope: "user:email"
    })
  ],

  adapter: Adapters.Fauna.Adapter({faunaClient}),
}
```

**Comment by waptik** [comment]
> Hi @waptik, I hadn't seen that other PR until after submitting this one unfortunately. It looks very similar, but I cannot speak of its implementation as I have not tested it.
> 
> I don't have a working example, but am using this in one of my apps. My [...nextauth].js file contains the following configuration
> 
> ```
> const faunaClient = new faunadb.Client({
>   secret: process.env.FAUNADB_SECRET_KEY,
> });
> 
> const options = {
>   providers: [
>     Providers.GitHub({
>       clientId: process.env.GITHUB_ID,
>       clientSecret: process.env.GITHUB_SECRET,
>       scope: "user:email"
>     })
>   ],
> 
>   adapter: Adapters.Fauna.Adapter({faunaClient}),
> }
> ```

Ah i see. The only difference in the implementation so far as i can see is that it already calls faunaClient instead of having it as a parameter.
Your  [...nextauth].js looks similar to mine.
I tried it and it works.

**Comment by Rashmi-278** [comment]
Hello , 
When can we expect the support for faunaDB to be added ?

**Comment by Joev-** [comment]
@iaincollins I've added some integration tests to the style of the existing ones, please let me know if you'd like me to change anything, as I am not up to scratch with testing patterns in javascript.

It uses a [fauna docker](https://docs.fauna.com/fauna/current/integrations/dev) instance. I am a bit wary of it however, as it seems quite memory hungry. 

Happy to hear your thoughts on the implementation and hope it's useful

**Comment by nawok** [comment]
Hello, @iaincollins, are there any estimations when this can be merged?

**Comment by perkinsjr** [comment]
What is the ETA on merging the Fauna support? I am happy to dig in for code review if needed.

**Review by perkinsjr — COMMENTED** [review]
I've reviewed the changes here. 

All look in the same style as other adapters and FaunaDB code looks great.

**Comment by ndom91** [comment]
Hi guys, this looks good to me! 

We've changed up the structure a bit and are working on putting new PR's like this into a `canary` branch first. As you've added tests and @perkinsjr and others have vouched for it, I'm going to tentatively merge this to `canary`.

You can install specific branches via npm from github as well, so we'd be happy if any of you would be willing to install the canary branch after this merge and report back if the fauna support is working as expected. i.e. `npm install git://github.com/nextauthjs/next-auth.git#canary --save`

**Comment by perkinsjr** [comment]
@ndom91 when installing the latest canary I get Error: Cannot find module './dist/client' which is obviously because the dist folder does not exist. 

Is there a command to run after the fact, I attempted to build but there is no source folder that babel is looking for.

**Comment by balazsorban44** [comment]
you can actually cd into node_modules/next-auth, run npm install, and then nom build.

**Comment by perkinsjr** [comment]
Oh derp forgot to install

On December 6, 2020, GitHub <notifications@github.com> wrote:
> you can actually cd into node_modules/next-auth, run npm install, and

> then nom build.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nextauthjs/next-auth/pull/708#issuecomment-
739579067>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AK2ONN4OL2DQ4MK5H5N6YODSTQDR7ANCNFSM4RXS5LLA>.

**Comment by perkinsjr** [comment]
Hmm I still get the same error after install. I think this is on my end so I will dig in

**Comment by ndom91** [comment]
So I tried it myself, and I'm not positive what exactly npm is doing on install as the `node_modules/next-auth` folder after install looks a lot different from the repo itself. There is no `src` directory or `dist` so I can't tell if it built it on its own or not yet.

Anyway, I tried just cloning the repo (canary branch) into `node_modules` manually, installing, and building. And that seemed to do the trick. I was able to get my application(s) using next-auth to run successfully with the `canary` branch. Unfortunately I don't know much about Fauna or have a fauna account so I couldn't test this, but hopefully that'll get you on the right path too.

**Comment by csanz** [comment]
Hey everyone, I managed to install the latest canary branch into my `node_modules` folder.  
I created a [script](https://gist.github.com/csanz/6db671e05e78f00da096adf4deb2e4c3 ) to do this faster 
Basically: 

```
cd ./node_modules
rm -rf ./next-auth 
git clone -b canary git://github.com/nextauthjs/next-auth.git
cd ./next-auth
npm install
npm run build
npx browserslist@latest --update-db
ls -1 ./dist/adapters/
```

I run the above inside an `update.sh` script.  
I also do this after I run `npm install `

This is what my `package.json` looks like

```
{
  "name": "test-app-1",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "faunadb": "^4.0.0",
    "next": "^10.0.3",
    "next-auth": "^3.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }
}

```
I do see the new version inside the `node_module` folder with the faunadb adapter. 
I run the [example script](https://gist.github.com/csanz/5dab64318e3d764220662b1bf64966c2) above 
After all of this I'm still getting the following [error](https://gist.github.com/csanz/7474a029e66a17b970580d5f0aa3fb18) 

> event - compiled successfully
> app.pageProps: { statusCode: 404 }
> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

I tried to debug, but haven't had good luck! thank you in advance if you have already figured this out and you are willing to help out :)

**Comment by balazsorban44** [comment]
Hi there @csanz. It's something with React, unfortunately. You could try this: https://github.com/nextauthjs/next-auth/blob/canary/CONTRIBUTING.md#setting-up-local-environment

We hope to get a `canary` release soon (this month), so hopefully, these methods won't be necessary.

**Comment by csanz** [comment]
Thank you sir 🙇🏻‍♂️

**Comment by n44ps** [comment]
I come here a bit late but is it possible to put the collection & index names in variables ? Maybe in the options of the Adapter ? So it can be used in any kind of Fauna Database. 
Thanks !

**Comment by waptik** [comment]
> I come here a bit late but is it possible to put the collection & index names in variables ? Maybe in the options of the Adapter ? So it can be used in any kind of Fauna Database.
> Thanks !

Oh! you mean something like:
```js
...
const collections = {
account: 'something',
user: 'something',
session: 'something',
vr: 'something',
}

const indexes= {
account: 'something',
user: 'something',
session: 'something',
vr: 'something',
}
...
const options = {
...

adapter: Adapters.Fauna.Adapter({collections, indexes})
...
};
...
```

I think this initial version of the adapter is targeted to those who want to use a fresh faunadb database with nextauth. Because based on the source code, when using collections and indexes, their names are hardcoded.
So if you can code, you can write a new version of the fauna adapter codebase by doing the following:
 - Make it so that the adapter `Adapters.Fauna.Adapter` accepts two objects(`collections, indexes`) and these two objects have the same object keys(eg: `account, user, session, vr`)
 - Replace each instance of hardcoded collections and indexes with the object key from the Apdater's function.

@s-kris did a similar thing over at https://gist.github.com/s-kris/fbb9e5d7ba5e9bb3a5f7bd11f3c42b96 where he declared the collections and indexes as variables then use theses variables wherever needed.

**Comment by Joev-** [comment]
Sorry for my delay in responding to this, it's been a hectic few months. Happy to see this is merged, thank you :-) 
I've tested this against the canary branch locally using the npm linking functionality, everything works great. 

> 
> I come here a bit late but is it possible to put the collection & index names in variables ? Maybe in the options of the Adapter ? So it can be used in any kind of Fauna Database.
> Thanks !

That would be ideal, I tried to keep this as similar as possible to the existing adapters. I imagine it would be a welcome change to all of them.

@ndom91 I will try and look at getting some docs adjustments to you over the holidays.

Thanks again!

**Comment by ndom91** [comment]
Great stuff, thanks a lot guys!

**Comment by n44ps** [comment]
> > I come here a bit late but is it possible to put the collection & index names in variables ? Maybe in the options of the Adapter ? So it can be used in any kind of Fauna Database.
> > Thanks !
> 
> Oh! you mean something like:
> 
> ```js
> ...
> const collections = {
> account: 'something',
> user: 'something',
> session: 'something',
> vr: 'something',
> }
> 
> const indexes= {
> account: 'something',
> user: 'something',
> session: 'something',
> vr: 'something',
> }
> ...
> const options = {
> ...
> 
> adapter: Adapters.Fauna.Adapter({collections, indexes})
> ...
> };
> ...
> ```
> 
> I think this initial version of the adapter is targeted to those who want to use a fresh faunadb database with nextauth. Because based on the source code, when using collections and indexes, their names are hardcoded.
> So if you can code, you can write a new version of the fauna adapter codebase by doing the following:
> 
> * Make it so that the adapter `Adapters.Fauna.Adapter` accepts two objects(`collections, indexes`) and these two objects have the same object keys(eg: `account, user, session, vr`)
> * Replace each instance of hardcoded collections and indexes with the object key from the Apdater's function.
> 
> @s-kris did a similar thing over at https://gist.github.com/s-kris/fbb9e5d7ba5e9bb3a5f7bd11f3c42b96 where he declared the collections and indexes as variables then use theses variables wherever needed.



> > I come here a bit late but is it possible to put the collection & index names in variables ? Maybe in the options of the Adapter ? So it can be used in any kind of Fauna Database.
> > Thanks !
> 
> Oh! you mean something like:
> 
> ```js
> ...
> const collections = {
> account: 'something',
> user: 'something',
> session: 'something',
> vr: 'something',
> }
> 
> const indexes= {
> account: 'something',
> user: 'something',
> session: 'something',
> vr: 'something',
> }
> ...
> const options = {
> ...
> 
> adapter: Adapters.Fauna.Adapter({collections, indexes})
> ...
> };
> ...
> ```
> 
> I think this initial version of the adapter is targeted to those who want to use a fresh faunadb database with nextauth. Because based on the source code, when using collections and indexes, their names are hardcoded.
> So if you can code, you can write a new version of the fauna adapter codebase by doing the following:
> 
> * Make it so that the adapter `Adapters.Fauna.Adapter` accepts two objects(`collections, indexes`) and these two objects have the same object keys(eg: `account, user, session, vr`)
> * Replace each instance of hardcoded collections and indexes with the object key from the Apdater's function.
> 
> @s-kris did a similar thing over at https://gist.github.com/s-kris/fbb9e5d7ba5e9bb3a5f7bd11f3c42b96 where he declared the collections and indexes as variables then use theses variables wherever needed.

This is definitly something I can do. Should I create a new merge request with the changes ?

**Comment by ndom91** [comment]
@n44ps yeah a new PR would be great!

**Comment by taylorhlabs** [comment]
Just getting started with Next.js, Next Auth, and Fauna DB. I am trying to get the [Next Auth example](https://github.com/nextauthjs/next-auth-example) working with Fauna. From a configuration standpoint, what are the necessary steps? It looks like the Fauna adapter was added recently, but how do I use it? I've reviewed a bunch of docs, but don't see a precise path.

I _think_ the steps involve just a change to the [...nextauth].js file and .env.local file. Is this correct?

It appears I need to add this to my [...nextauth].js file:


> Hi @waptik, I hadn't seen that other PR until after submitting this one unfortunately. It looks very similar, but I cannot speak of its implementation as I have not tested it.
> 
> I don't have a working example, but am using this in one of my apps. My [...nextauth].js file contains the following configuration
> 
> ```
> const faunaClient = new faunadb.Client({
>   secret: process.env.FAUNADB_SECRET_KEY,
> });
> 
> const options = {
>   providers: [
>     Providers.GitHub({
>       clientId: process.env.GITHUB_ID,
>       clientSecret: process.env.GITHUB_SECRET,
>       scope: "user:email"
>     })
>   ],
> 
>   adapter: Adapters.Fauna.Adapter({faunaClient}),
> }
> ```

And then I know I need to update the variables (like FAUNADB_SECRET_KEY) in my .env.local file.

I'm hoping someone can provide precise details on which values need to be configured in the .env.local file? And precise changes to [...nextauth].js file? And any other changes? Thanks so much! Noob here 🙄

**Comment by waptik** [comment]
> Just getting started with Next.js, Next Auth, and Fauna DB. I am trying to get the [Next Auth example](https://github.com/nextauthjs/next-auth-example) working with Fauna. From a configuration standpoint, what are the necessary steps? It looks like the Fauna adapter was added recently, but how do I use it? I've reviewed a bunch of docs, but don't see a precise path.
> 
> I _think_ the steps involve just a change to the [...nextauth].js file and .env.local file. Is this correct?
> 
> It appears I need to add this to my [...nextauth].js file:
> 
> > Hi @waptik, I hadn't seen that other PR until after submitting this one unfortunately. It looks very similar, but I cannot speak of its implementation as I have not tested it.
> > I don't have a working example, but am using this in one of my apps. My [...nextauth].js file contains the following configuration
> > ```
> > const faunaClient = new faunadb.Client({
> >   secret: process.env.FAUNADB_SECRET_KEY,
> > });
> > 
> > const options = {
> >   providers: [
> >     Providers.GitHub({
> >       clientId: process.env.GITHUB_ID,
> >       clientSecret: process.env.GITHUB_SECRET,
> >       scope: "user:email"
> >     })
> >   ],
> > 
> >   adapter: Adapters.Fauna.Adapter({faunaClient}),
> > }
> > ```
> 
> And then I know I need to update the variables (like FAUNADB_SECRET_KEY) in my .env.local file. Not sure where to put the exact config for database URL and what is it for Fauna?
> 
> I'm hoping someone can provide precise details on which values need to be configured in the .env.local file? And precise changes to [...nextauth].js file? And any other changes? Thanks so much! Noob here 🙄

Using the next-auth example, you neeed to:

1. first, create a database
2. second, copy [the code snippet](https://github.com/nextauthjs/next-auth/pull/708#issue-492079866), delete any `q.`. Go to your database's shell and paste the modified code inside the console then run the query.
3. After running the query and your collections and indexes created, goto the Security tab. Create a new key with following details: Database -> database you want to use, Role-> Server, Name -> any name of your choice and `Save`. Copy the generated secret you see and save it elsewhere, you'll need it soon.
4. Now back to the project code, open `.env.local` and add the following `FAUNADB_SECRET_KEY=YOUR_FAUNA_SERVER_SECRET`. Replace `YOUR_FAUNA_SERVER_SECRET` with the generated key you copied in the previous step.
5. Open `[...nextauth].js` and follow what you see here https://github.com/nextauthjs/next-auth/pull/708#issuecomment-699540954
6. Install the packages if you haven't done so already with `npm install` or `yarn`
7. update next-auth to the latest canary version by running `npm i next-auth@canary` or `yarn add next-auth@canary`
8. Run the project using `npm run dev` or `yarn dev`

**Comment by taylorhlabs** [comment]
Thanks @waptik for the details. I didn't have latest canary version installed. I was confused where to set the URL for a Fauna DB but I see now it's specified in the "faunadb" module included in latest canary version of next-auth. Thanks again for the assist!

**Comment by waptik** [comment]
> Thanks @waptik for the details. I didn't have latest canary version installed. I was confused where to set the URL for a Fauna DB but I see now it's specified in the "faunadb" module included in latest canary version of next-auth. Thanks again for the assist!

Yeah sure, no problem. Glad i could be of any assist

**Comment by taylorhlabs** [comment]
I have the adapter _mostly_ working with my Fauna database. It seems I can write to the database (verification requests are saving to the verifiation_request collection for email verfication) but I'm getting read errors in the terminal (GET_SESSION_ERROR and GET_VERIFICATION_REQUEST_ERROR) which is preventing me from any successful log in. Anyone else run into this?

**Comment by waptik** [comment]
> I have the adapter _mostly_ working with my Fauna database. It seems I can write to the database (verification requests are saving to the verifiation_request collection for email verification) but I'm getting read errors in the terminal (GET_SESSION_ERROR and GET_VERIFICATION_REQUEST_ERROR) which is preventing me from any successful log in. Anyone else run into this?
> 
> Update: There is a typo in the database setup script [here](https://github.com/nextauthjs/next-auth/pull/708#issue-492079866).
> name: 'vertification_request_by_token', -> should be -> name: 'verification_request_by_token', (remove "t" in "verification_)
> 
> This resolved the GET_VERIFICATION_REQUEST_ERROR for me. Still looking into the GET_SESSION_ERROR.

Try clearing emptying the collections and indexes to see if it'll work

**Comment by taylorhlabs** [comment]
Created a brand new DB on Fauna and set it up. Verification Requests collection is populating but still getting GET_SESSION_ERROR when using the Log In link in email. Have you used the Fauna adapter with Email provider? That's all I'm using for now and I have it working with Prisma/MySql but not Fauna.

**Comment by balazsorban44** [comment]
Could you please move this to a discussion @taylorhlabs? In addition of  being it a better place for such conversations than a closed PR, it may be more easily accessible for people in the future with similar problems. Thanks!

**Comment by taylorhlabs** [comment]
Yes, moved it to this [discussion](https://github.com/nextauthjs/next-auth/discussions/1018). Was thinking this was not the right place... Thanks!

**Pull request merged**
