### PR TITLE
feat(provider): add netlify

### PR DESCRIPTION
**Pull request by styxlab**

### CODE REVIEW

**Comment by styxlab** [comment]
The details link gives me a 404 error, so I don't know why the Vercel pipeline failed. Please let me know the issue, so I can go correct it.

**Comment by iaincollins** [comment]
@styxlab Thanks for the PR (and for providing docs).

This is super weird and I don't think it's anything in the PR but will check it out locally.

Retrying doesn't help it's possible it's a transient issue with Vercel.

Will try again later.

```
10:40:29.161 | Cloning github.com/nextauthjs/next-auth (Branch: main, Commit: 518619e)
-- | --
10:40:30.917 | Cloning completed in 1756ms
10:40:30.919 | Analyzing source code...
10:40:35.491 | Installing build runtime...
10:40:52.063 | Error: Exited with 1
10:40:52.063 | at ChildProcess.<anonymous> (/var/task/sandbox-worker.js:21953:21)
10:40:52.063 | at ChildProcess.emit (events.js:310:20)
10:40:52.063 | at ChildProcess.EventEmitter.emit (domain.js:482:12)
10:40:52.063 | at maybeClose (internal/child_process.js:1021:16)
10:40:52.063 | at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
10:40:56.392 | Done with "package.json"
```

**Comment by iaincollins** [comment]
Whatever was wrong has fixed itself :-)

**Review by iaincollins — CHANGES_REQUESTED** [review]
This looks great, thank you! The work on the documentation pages is much appreciated.

No issues with the pull request, just putting merging on hold briefly while we sort out the release process (so we don't merge things live on the website before we have actually released them).

Working hard to get this unblocked so we can get this rolled out!

**Comment by styxlab** [comment]
Thanks again for this awesome project, am happy if I could help!

**Comment by styxlab** [comment]
:+1: Thanks!

**Pull request merged**
