### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by iaincollins**
# Version 3.0 Release Notes

## Summary

The focus of this release has been to improve security and configuration.

Version 3.0 addresses issues in version 2.0 that were only possible to resolve by making breaking changes in some cases. 

The refactoring required to upgrade from 2.0 should be relatively minor and should be eased by the new documentation.

### Added

* The OAuth 2.0 state object is now verified if supported (RFC 6749).
  Can be disabled for a provider with `state: false` provider option if not supported by a provider.
* Added Prisma Adapter as alterantive to the TypeORM Adapter.
* Added MySQL and Postgres SQL schemas to documentation and fixtures.
* Added support for JWE/JWA/JWK.

### Changed

* Replaced `site` and `baseUrl` configuration options with the `NEXTAUTH_URL` environment variable.
  Allows for application wide site and base URL configuration in a single option.
* All sign in flows now use HTTP POST with CSRF tokens throughout.
* Pages option now uses camelCase for all options.
* Events option now uses camelCase for all options.
* Callbacks option now uses camelCase for all options.
* New options now passed to Sign In, Session and JWT callbacks to allow for more flexibility.
* Sign In and Credentials Authorize callbacks can now return Promise.reject() with an Error object or URLs.
* All timestamps columns in MySQL now use TIMESTAMP(6) consistantly.
* JSON Web Tokens are signed by default but not encrypted by default (improving interoperability and reducing overhead, making more space avalible for use). Encryption can still be enabled by setting encryption: true.
* Now use claims in JSON Web Tokens with smaller default payload.
* Removed getJwt() helper and replaced it with more sophisticated getToken() helper.
* No longer relies on Dynamic Import, which should resolve some compatibility problems with some configurations.
* Some sign in error messages are now displayed in line on the sign in page.

### Added
* Added `keepAlive` option to keep sessions alive when idle.
* Session state is updated when a window loses or gains focus.
* Open tabs/windows now sync session state when it changes.

### Changed
* Refactored `clientMaxAge` behaviour to be more efficient.
* Reduced network load and improved memory footprint.
* Client methods now use camelCase.
* Misc. bug fixes and enhancement to client methods.

## Credits

Thanks to everyone who has contributed to this release, with fixes, bug reports, new providers, tutorials and other changes.

@ndom91 @Fumler @tsaiDavid @tmayr @tylangesmith @timomeh @drborges @BenjaminWFox @nyedidikeke

* Thanks to Mark Lawlor for raising the issue with CSRF token and OAuth State support. 
* Thanks to @Fumler for creating the Prisma adapter.

Apologies to anyone I have missed!

### CODE REVIEW

**Comment by iaincollins** [comment]
@ndom91 RE: Marquee

I was playing around trying to resolve a CSS clipping issue and got a bit carried away... I added some new icons and tried seeing what it would look like in a more prominent place on the page, what do you about https://next-auth-docs-git-v3.iaincollins.vercel.app ?

(Appreciate my CSS is horrible tech debt, but happy to look at cleaning that up after we are done wrangling it. :-)

**Comment by iaincollins** [comment]
@Fumler Really looking forward to trying out Prisma adapter!

I've been working on the docs - doing stuff like turning some of the docs into separate tutorial pages, etc.

If you have any time to review the current docs for Prisma would appreciate it, in case anything I've written is wrong:

https://next-auth-docs-git-v3.iaincollins.vercel.app/schemas/adapters#prisma-adapter

**Comment by ndom91** [comment]
> @ndom91 RE: Marquee
> 
> I was playing around trying to resolve a CSS clipping issue and got a bit carried away... I added some new icons and tried seeing what it would look like in a more prominent place on the page, what do you about https://next-auth-docs-git-v3.iaincollins.vercel.app ?
> 
> (Appreciate my CSS is horrible tech debt, but happy to look at cleaning that up after we are done wrangling it. :-)

This looks great! Love what you did there!

**Comment by Fumler** [comment]
> @Fumler Really looking forward to trying out Prisma adapter!
> 
> I've been working on the docs - doing stuff like turning some of the docs into separate tutorial pages, etc.
> 
> If you have any time to review the current docs for Prisma would appreciate it, in case anything I've written is wrong:
> 
> https://next-auth-docs-git-v3.iaincollins.vercel.app/schemas/adapters#prisma-adapter

LGTM.

Maybe write something about what was [mentioned in the original PR](https://github.com/iaincollins/next-auth/pull/302#issuecomment-654058430). E.g. in the usage example instead of just `const prisma = new PrismaClient()` do:
```javascript
let prisma

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }

  prisma = global.prisma
}
```

Might be a bit complex for a simple example, but that should at least remove issues people might run into with running out of db connections when using e.g. postgres. I haven't personally had the issue though, but I seldom log in locally.

**Comment by tsaiDavid** [comment]
I'm not really sure where to ask this question, but in trying 3.0 Beta so far, @dmi3y and I are bumping into the problem of not being able to have `account` in scope in any of those callbacks. We are using `auth0` as our provider, and can successfully signin/signout without issue. We are asking because `account` contains `accessToken` which we need to pass on for calls to our GraphQL API.

**Comment by iaincollins** [comment]
@tsaiDavid It sounds like it's appropriate to raise a feature request or bug report with details if how to replicate depending on if you are getting an error or just not something that's supported yet.

**Comment by Fumler** [comment]
image

The navbar with dark theme has a bit too low contrast, can be hard to read for some people.

**Comment by iaincollins** [comment]
> The navbar with dark theme has a bit too low contrast, can be hard to read for some people.

Thanks! Will fix that.

**Pull request merged**
