### PR TITLE
fix(sveltekit): support custom base path

### LINKED ISSUE #8230: SvelteKit base path not used in client side signIn/signOut
### Environment

Node: 18.17.0
OS: Ubuntu 22.04
"@auth/core": "^0.10.0",
"@auth/sveltekit": "^0.3.6",
provider: Auth0

### Reproduction URL

https://github.com/jonek/next-auth/commits/example-fix-base-path/apps/examples/sveltekit

### Describe the issue

Client side `signIn` and `signOut` functions fail in a SvelteKit app using @auth/sveltekit if the `svelte.config.js` contains a base path configuration as documented by https://kit.svelte.dev/docs/configuration#paths

### How to reproduce

1. Add a `kit.paths.base` value to your `svelte.config.js` like this:
```
// ...
const config = {
  // ...
  kit: {
    // ...
    paths: {
      base: '/foo',
    },
  },
}

export default config
```
2. Start your development example app (in my case using an Auth0 provider) and trigger the signIn.
3. In the browser console you will see something like:
```
GET http://localhost:5173/auth/csrf 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected token 'T', "The server"... is not valid JSON
```
with a stack trace like:
```
window.fetch @ fetcher.js?v=5e3e0935:54
signIn @ client.js:19
login @ +page.svelte:7
```
4. The error is caused by `http://localhost:5173/auth/csrf` returning `The server is configured with a public base URL of /foo - did you mean to visit <a href="/foo/auth/csrf">/foo/auth/csrf</a> instead?` which is not valid JSON and causes the crash.

### Expected behavior

When the client side `signIn` is executed, the implementation should take the SvelteKit configuration into account to call the `/auth/csrf` and later the `/auth/signin/auth0` endpoints under the base path specified by `config.kit.paths.base`.
I.e. the URL to call should be `http://localhost:5173/foo/auth/csrf` and `http://localhost:5173/foo/auth/signin/auth0` in my example described above.

### PR DESCRIPTION
**Pull request by jonek**
## ☕️ Reasoning

SvelteKit allows to set a base path in `...paths.base` in it's config.
auth.js however does not adhere to that base path out of the box.

This fix takes the SvelteKit configuration directly into account when creating the URLs called by the client side `signIn` and `signOut` functions.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/8230

### CODE REVIEW

**Comment by nathanbrizzee-cdcr** [comment]
Can we get this approved soon please?  I have the exact same problem with my applications. I copied the two functions locally into my applications to get it to work. My solution is nearly identical to this.  I spent over two days trying to figure this one out.  The docs mention that setting the "prefix" in the config could/should make this work, but it didn't. 
 https://authjs.dev/reference/sveltekit#prefix .  I host my apps on-prem via Docker and on a sub-path for nginx routing purposes.  I suspect this affects the NextJS version of the functions as well, but I cannot confirm that.  Thanks.

**Comment by jonek** [comment]
@ThangHuuVu I think you were somehow automatically assigned as a reviewer for this PR. Should this be assigned to somebody else instead to get a review? Is there something I can improve on this PR to get it reviewed and merged?

**Comment by claraisrael** [comment]
Hi admins, can we get this PR approved pls?

**Review by ThangHuuVu — APPROVED** [review]
LGTM, thanks for the PR @jonek

**Comment by ThangHuuVu** [comment]
PS I added another commit to apply the change on the server side as well

**Comment by aakash14goplani** [comment]
@jonek - did the latest release solved your problem? I am in similar situation now and adding `prefix` did not fixed problem for me. I am still seeing 404 for csrf request!

```ts
const config: SvelteKitAuthConfig = {
  providers: [...],
  prefix: '/hello',
}
```
```
Request URL: http://localhost:4200/hello/auth/csrf
Request Method: GET
Status Code: 404 Not Found
```

cc: @ThangHuuVu

**Comment by jonek** [comment]
@aakash14goplani I did not try yet, because I used another workaround.

You could use the "Reproduction URL" from my [bug report](https://github.com/nextauthjs/next-auth/issues/8230), try to reproduce it, then update to the version containing the fix of this PR, and see if it is solved.

**Pull request merged**
