### PR TITLE
feat(core/providers): add wechat provider

### LINKED ISSUE #7960: Support wechat login
### Description 📓

This is a very important way to open the Chinese market.

Hope to support. 🤓

### How to reproduce ☕️

This is WeChat documentation：

https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

### PR DESCRIPTION
**Pull request by KaygNas**
## ☕️ Reasoning

Support WeChat Login

FYI: Getting a `WECHAT_APP_ID` and `WECHAT_APP_SCRECT` is a bit difficult because audition is required for every application. However there are TEST ACCOUNT provided, follow the instruction below would help to do that:

### 0. Apply a WeChat Account

Download [WeChat](https://www.wechat.com/) and apply an account.

### 1. Apply a test account

Open the [WeChat Official Account Test Account](https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login) and scan the QRCode with WeChat on your phone.

image

### 2. Copy the `APP_ID` and `APP_SCRET` to the `.env.local` file

Once you login the website, the `APP_ID` and `APP_ACCOUNT` would generated automatically, just copy them to the `.env.local` file.

image

### 3. Set the `redirect_uri` with your local IP

Make sure your `redirct_uri` is set correctly

image

### 4. Download WeChat Dev Tool 

The login can be only done in the environment of WeChat Browser, therefore it would be convenient to development using the WeChat Dev Tool. Accurately, it's not really convenient 🥲. 

Download [WeChat Dev Tool](https://developers.weixin.qq.com/miniprogram/en/dev/devtools/download.html), select the stable version.

image

### 5. Access Your Localhost by the IP Using the Dev Tool

Click the Official Account Tab, 

image

Start the `app/examples/nextjs` project, and input your localhost IP and click Sign In button

image

Click Sign In With WeChat

image

### 6. Sign In Succeed

image

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

 

Fixes: https://github.com/nextauthjs/next-auth/issues/7960

## 📌 Resources

- [WeChat Official Account](https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Overview.html)
- [WeChat Official Account - Webpage Authorization](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html)
- [Using Test Account to Authorize](https://cloud.tencent.com/developer/article/1703167))  
- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by KaygNas** [comment]
> Hey @balazsorban44, noticed many WeChat PRs got staled earlier on. Mind giving this one a look? Thanks for the help!

@tonyabracadabra Hi there, you may adopt the provider into your app by yourself, have a look at [this](https://github.com/KaygNas/nextjs-auth-wechat/tree/main) repo, and follow the step below:

1. Copy the [`wechat.ts`](https://github.com/KaygNas/nextjs-auth-wechat/blob/main/wechat.ts) file into your project
2. Import the `WeChatProvider` into your [`auth.ts`](https://github.com/KaygNas/nextjs-auth-wechat/blob/main/auth.ts#L139) file
3. Copy the `.env.local.example` into your project and rename to `.env.local`, also fill the [`Auth_WECHAT_APP_ID` and `AUTH_WECHAT_APP_SECRET`](https://github.com/KaygNas/nextjs-auth-wechat/blob/main/.env.local.example#L19).

After all there done, start your app and it should be work.😉

**Comment by Yidadaa** [comment]
@balazsorban44 @ndom91 @ThangHuuVu 

WeChat has 1.36 billion users worldwide, and I believe integrating this provider into NextAuth would benefit a lot of people. It would also enhance the usability of NextAuth. I hope you'll consider merging this PR.

**Comment by swingislee** [comment]
Hello, I am a pure beginner. I have implemented username and email login in my project. Now I am trying to use the file you provided to complete the third-party login of WeChat, but after I put the wechat.ts file  in to the root directory of my project, the following error occurred:

Object literal may only specify known properties, and 'options' does not exist in type 'OAuth2Config<P>'.ts(2353)
(property) options: OAuthUserConfig<P> & {
    platformType: 'OfficialAccount' | 'WebsiteApp';
}

image

Please tell me if there is any step that I forgot to complete. I would be very grateful if I could get your guidance.

**Comment by KaygNas** [comment]
> Hello, I am a pure beginner. I have implemented username and email login in my project. Now I am trying to use the file you provided to complete the third-party login of WeChat, but after I put the wechat.ts file in to the root directory of my project, the following error occurred:
> 
> Object literal may only specify known properties, and 'options' does not exist in type 'OAuth2Config
> 
> '.ts(2353) (property) options: OAuthUserConfig
> 
> & { platformType: 'OfficialAccount' | 'WebsiteApp'; }
> 
> image
> 
> Please tell me if there is any step that I forgot to complete. I would be very grateful if I could get your guidance.

@swingislee It can be a problem caused by your dependencies, please make sure `next-auth@5.0.0-beta.15` is correctly installed.  Otherwise, try clone this repo [nextjs-auth-wechat](https://github.com/KaygNas/nextjs-auth-wechat/tree/main) and make comparison to figure out where the problem is?

**Comment by swingislee** [comment]
> @swingislee It can be a problem caused by your dependencies, please make sure `next-auth@5.0.0-beta.15` is correctly installed. Otherwise, try clone this repo [nextjs-auth-wechat](https://github.com/KaygNas/nextjs-auth-wechat/tree/main) and make comparison to figure out where the problem is?

@KaygNas When I cloned your project and tried to run it on my local windows PC, I got the same error. I checked that my version was indeed next-auth@5.0.0-beta.15. 

 Being a pure beginner,  I did some simple tests. If I create a new project in the @auth/core directory, an error will appear for the option value. If I copy your wechat code intact to other ts documents in the same directory, the error will  disappear, so I am guessing whether it is because a new oauth policy has been added, but auth.v5 also needs to update settings in some places that I don't know to make this policy take effect?

**Comment by KaygNas** [comment]
@swingislee It turns out [`options` is documented as `@internal`](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/oauth.ts#L229) so that TS [wouldn't compile it into the output types](https://www.typescriptlang.org/tsconfig#stripInternal) because [the `stripInternal` config is `true`](https://github.com/nextauthjs/next-auth/blob/main/packages/utils/tsconfig.json#L17). So the simplest solution is to cheat TS by annotate the type as any, check out this [commit](https://github.com/KaygNas/nextjs-auth-wechat/commit/859c08f5448aabc0a5567ca8abd53f6826ab4c5e).

**Comment by MarvinXu** [comment]
> there was a few eslint issues in the original code and I've fixed them and compiled a new version you can try that out
> 
> ```ts
> import type { OAuthConfig, OAuthUserConfig } from "next-auth/providers";
> import { env } from "~/env";
> 
> export interface WeChatProfile {
>   openid: string;
>   nickname: string;
>   sex: number;
>   province: string;
>   city: string;
>   country: string;
>   headimgurl: string;
>   privilege: string[];
>   unionid: string;
>   [claim: string]: unknown;
> }
> 
> interface WeChatTokenResponse {
>   access_token: string;
>   expires_in: number;
>   refresh_token: string;
>   openid: string;
>   scope: string;
>   unionid: string;
> }
> 
> export default function WeChat<P extends WeChatProfile>(
>   options: OAuthUserConfig<P> & {
>     platformType: "OfficialAccount" | "WebsiteApp";
>   },
> ): OAuthConfig<P> {
>   const {
>     clientId = env.WECHAT_APP_ID,
>     clientSecret = env.WECHAT_APP_SECRET,
>     platformType,
>   } = options;
> 
>   if (platformType !== "OfficialAccount" && platformType !== "WebsiteApp") {
>     throw new Error("Invalid plaformType");
>   }
> 
>   const authorizationEndpointUrl =
>     platformType === "OfficialAccount"
>       ? "https://open.weixin.qq.com/connect/oauth2/authorize"
>       : "https://open.weixin.qq.com/connect/qrconnect";
>   const authorizationScope =
>     platformType === "OfficialAccount" ? "snsapi_userinfo" : "snsapi_login";
>   const authorization = {
>     url: authorizationEndpointUrl,
>     params: {
>       appid: clientId,
>       response_type: "code",
>       scope: authorizationScope,
>       state: Math.random().toString(),
>     },
>   };
> 
>   const tokenEndpointUrl = "https://api.weixin.qq.com/sns/oauth2/access_token";
>   const token = {
>     url: tokenEndpointUrl,
>     params: {
>       appid: clientId,
>       secret: clientSecret,
>       code: "CODE",
>       grant_type: "authorization_code",
>     },
>     conform: async (response: Response) => {
>       const data = (await response.json()) as WeChatTokenResponse;
>       const conformedResponse = new Response(
>         JSON.stringify({
>           ...data,
>           token_type: "bearer",
>         }),
>         response,
>       );
>       return conformedResponse;
>     },
>   };
> 
>   const userinfo = {
>     url: "https://api.weixin.qq.com/sns/userinfo",
>     request: async ({
>       tokens,
>       provider,
>     }: {
>       tokens: { access_token: string; openid: string };
>       provider: { userinfo?: { url?: string } };
>     }) => {
>       const url = new URL(provider.userinfo?.url ?? "");
>       url.searchParams.set("access_token", tokens.access_token);
>       url.searchParams.set("openid", String(tokens.openid));
>       url.searchParams.set("lang", "zh_CN");
>       const response = await fetch(url);
>       return response.json() as Promise<P>;
>     },
>   };
> 
>   const profile = (profile: WeChatProfile) => {
>     return {
>       id: profile.unionid,
>       name: profile.nickname,
>       email: null,
>       image: profile.headimgurl,
>     };
>   };
> 
>   return {
>     id: "wechat",
>     name: "WeChat",
>     type: "oauth",
>     style: { logo: "/wechat.svg", bg: "#fff", text: "#000" },
>     checks: ["pkce", "state"],
>     clientId,
>     clientSecret,
>     authorization,
>     token,
>     userinfo,
>     profile,
>     options,
>   } as OAuthConfig<P>;
> }
> ```

I still have type errors. Do you have a working repo?

**Comment by WendaoLee** [comment]
Nice pr.😘It helps me a lot.

**Review by balazsorban44 — APPROVED** [review]

**Review by falcowinkler — APPROVED** [review]

**Comment by UncleBu1728** [comment]
I’m encountering an `Oops! Something went wrong` error during the OAuth flow when trying to authenticate using the WeChat provider with NextAuth.js. The authorization URL is being generated, but when I visit it, the page shows this error message instead of proceeding to the login screen.

 I have double-checked the following:
- The clientId and clientSecret are correct.
- The redirect_uri matches the one set in the WeChat Developer Console.
- The state parameter is being generated and passed correctly in the request.

Any insights or suggestions would be greatly appreciated!

**Comment by WendaoLee** [comment]
> I’m encountering an `Oops! Something went wrong` error during the OAuth flow when trying to authenticate using the WeChat provider with NextAuth.js. The authorization URL is being generated, but when I visit it, the page shows this error message instead of proceeding to the login screen.
> 
> I have double-checked the following:
> 
> * The clientId and clientSecret are correct.
> * The redirect_uri matches the one set in the WeChat Developer Console.
> * The state parameter is being generated and passed correctly in the request.
> 
> Any insights or suggestions would be greatly appreciated!

You can refer to the error code for your redirect page.

Also,you can debug for your provider's `profile()` or nextauth's `signin()` callback for inspecting where the error occurs.

**Comment by C-L-STARK** [comment]
image

**Comment by peihuanhuan** [comment]
> 图像

I'm also having this problem.

**Comment by victor56349Wan** [comment]
> I’m encountering an `Oops! Something went wrong` error during the OAuth flow when trying to authenticate using the WeChat provider with NextAuth.js. The authorization URL is being generated, but when I visit it, the page shows this error message instead of proceeding to the login screen.
> 
> I have double-checked the following:
> 
> * The clientId and clientSecret are correct.
> * The redirect_uri matches the one set in the WeChat Developer Console.
> * The state parameter is being generated and passed correctly in the request.
> 
> Any insights or suggestions would be greatly appreciated!

Hi there, not sure if you have fixed this. I met the same but the issue gone if logging in from my mobile wechat app.

**Pull request merged**
