### PR TITLE
isDate() returns true for non dates in edge cases that make use of delimiters '#' or '-'

### LINKED ISSUE #7571: isDate() returns true for non dates in edge cases that make use of delimiters '#' or '-' (possibly more).
### Adapter type

@next-auth/supabase-adapter

### Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 18.21 GB / 31.42 GB
  Binaries:
    Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1

  npmPackages:
    @next-auth/supabase-adapter: ^0.2.1 => 0.2.1

### Reproduction URL

https://github.com/nerkmind1337/modmaster/blob/main/src/lib/auth.ts

### Describe the issue

The official Supabase adapter for NextAuth has a bug in the isDate function, which incorrectly formats usernames containing hashtags as dates. This causes unexpected behavior when usernames are processed, resulting in incorrect date representations and subsequent issues in user management.

### How to reproduce

Steps to Reproduce

clone repo linked, go to file I linked in the URL, remove this "stupid fix" block 
  ```
  //heres the stupid extra call i reffed in stupidFix.ts
                let sf = await stupidFix(user.id)
                if (sf) {
                    session.user.id = sf.id
                    session.user.name = sf.name
                }
```

Note: im calling my fix stupid (because it is), not anyone else :P 
 now simply log out what "Session.user" or even "user" returns.
 
 Assuming you have data in your table, you'll get a name returned as a date string.  IF, the name contains a '#' EG. nerkmind#1337

Im also pretty sure this will happen with other delimiters. I also tested '-' .
 
 Make sure you seed your supabase DB with the nextauth seed. I just used the default one from the docs. 

***proposed change***

isDate should work like this instead. 

```
function isDate(str: string): boolean {
  const date = new Date(str);
  return !isNaN(date.getTime()) && date.toString() !== 'Invalid Date';
}
```
In this version, we use getTime() to obtain the numeric value representing the date from the Date object. We then check if the obtained value is not NaN and the string representation of the date is not 'Invalid Date'.

I have tested this, but may have missed some edge cases. I'll submit a PR with my fix and see what you all think :)

### Expected behavior

Expected Behavior

The isDate function should correctly identify whether a given input is a valid date string and avoid formatting usernames containing hashtags as dates.

### PR DESCRIPTION
**Pull request by nerkmind1337**
## ☕️ Reasoning
there is a bug in the isDate function, which incorrectly formats usernames containing hashtags as dates.
 

isDate should work like this instead. 
```
function isDate(testDate: string | number | Date): boolean {
  const date = new Date(testDate);
  return !isNaN(date.getTime()) && date.toString() !== 'Invalid Date';
}
```
In this version, we use getTime() to obtain the numeric value representing the date from the Date object. We then check if the obtained value is not NaN and the string representation of the date is not 'Invalid Date'.

I have tested this, but may have missed some edge cases. I'll submit a PR with my fix and see what you all think :)

## 🧢 Checklist

- [x] Documentation - unsure where, if there is any, the documentation for this moving part lives. 
- [x] Tests 
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: [isDate() returns true for non dates in edge cases that make use of delimiters '#' or '-'](https://github.com/nextauthjs/next-auth/issues/7571)

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by nerkmind1337** [comment]
Did anyone get the chance to look at this? it's been blocking me for months.

**Comment by nerkmind1337** [comment]
guys?

**Comment by nerkmind1337** [comment]
Its been 6 months and this is still broken, please merge my fix.

**Comment by nerkmind1337** [comment]
bumping @balazsorban44 its been almost a year.

**Comment by ndom91** [comment]
@nerkmind1337 this is impossible to merge, it includes a ton of unrelated changes.

Please update your PR to only include the relevant changes. 

Might be easier to just take your changes and open a new PR from a fresh branch :pray:

**Comment by ndom91** [comment]
Also regarding your issue, did I understand it correctly that username's like `Username#123` (like Discord users) get misinterpreted?

I was able to reproduce the issue with the pre-existing `isDate` function in the Supabase adapter. I.e. this one:

```js
function isDate(date) {
  return (
    new Date(date).toString() !== "Invalid Date" && !isNaN(Date.parse(date))
  )
}
```

However, your suggested `isDate` replacement seems to suffer from the same issue:

```js
function isDate2(testDate) {
  const date = new Date(testDate);
  return !isNaN(date.getTime()) && date.toString() !== 'Invalid Date';
}
```
```js
isDate2('Username#123')
// true
```

**Comment by balazsorban44** [comment]
Closing as this has a ton of merge conflicts.

I also just tested https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/adapters.ts/#L445-L451

which seems to handle this well.

**Pull request closed without merging**
