### PR TITLE
refactor: strict types

### LINKED ISSUE #2709: Comply with TypeScript strict mode
#2552 introduced TypeScript to the core. A long-time wish from the community, and the maintainers.

For an easier migration, I decided to go with `"strict": false`, and we still allow ".js" files.

As an improvement, we should make set `"strict": true` in our `tsconfig.json` and fix the remaining issues, and convert the rest of the files to TypeScript as well.

### PR DESCRIPTION
**Pull request by Thisen**
## Reasoning 💡

Comply with TS strict typing. Very much WIP.

## Checklist 🧢

- [X] Documentation - N/A
- [X] Tests - N/A
- [X] Ready to be merged - N/A

## Affected issues 🎟

Partially fixes #2709. TypeScript conversion should be done in a new PR, to keep this PR more concise.

### CODE REVIEW

**Comment by Thisen** [comment]
@balazsorban44, I've got good progress, however there are two outstanding issues, where I'm unsure what to do:
- in `client-legacy.ts`, where some `get` methods from `oauth1Client` are being promisfied. I think the intent was to replace the `callback`, but that's not what happening.
- in `src/providers/oauth.ts`, this line (`export type { OAuthProviderType } from "./oauth-types"`), but `oauth-types` doesn't exist.

**Comment by balazsorban44** [comment]
1. oauth1Client has  a callback based api, while we want to use a Promise based one. I don't think there is a graceful way of typing that part, I would just set any where necessary. Man shrugging
2. that is generated by `npm run generate-providers`

**Comment by Thisen** [comment]
@balazsorban44, feel free to review. :)

**Comment by Thisen** [comment]
@balazsorban44, it's done. I think the converting the providers to TS should be a different PR, this one is already rather large.

**Comment by Thisen** [comment]
@balazsorban44, will this be merged?

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
