### PR TITLE
feat(adapters): add Cloudflare Workers KV adapter

### PR DESCRIPTION
**Pull request by tdack**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Cloudflare Workers KV adapter. Based completely on the Upstash-Redis adapter.

Requires KV Namespace binding in Cloudflare Pages/Workers dashboard to populate process.env at run time. See https://developers.cloudflare.com/kv/learning/kv-bindings/

I have tested this in local and remote with AuthJS Sveltekit framework using miniflare in local development.

In the end this didn't require a great deal of effort on my part because of the work of others. I'm not sure I'd have the knowledge to keep it updated, though happy to contribute something to get others started.

## 🧢 Checklist

- [X] Documentation
- [X] Tests
- [X] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Discussion #7930 Adapter for Cloudflare KV

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by snilan** [comment]
I was thinking of doing a KV adapter so thanks! 👍 

But I was wondering, since this and the Upstash provider are basically the same, as would it any other KV store, I wonder if it would make more sense to refactor it to target Unstorage. https://unstorage.unjs.io/

**Comment by ndom91** [comment]
@snilan that makes a lot of sense to me. Reduces maintenance burden here as well. Would you be interested in modifying this PR (if the author is also interested) or creating a new one?

**Comment by tdack** [comment]
@ndom91 I'm happy for this to be used to target Unstorage. I'll have a look and see if I can work it out, otherwise I don't have any problem with someone else having a go.

**Comment by nbifrye** [comment]
@ndom91 @tdack 
Thanks to you and @snilan for the great idea! I worked on adding an unstorage adapter.
Would you mind taking a look at my PR #9501 ? Sorry if this is hijack-like.

**Comment by ndom91** [comment]
@nbifrye no worries, thanks for the PR!

**Comment by ndom91** [comment]
Regarding this PR for the cloudflare adapter, i think it's kind of superfluous now. @tdack what do you think?

**Comment by tdack** [comment]
@ndom91 concur. The unstash adapter in PR #9501 appears to add the same functionality in a way that allows many KV back ends to be used with ease.

**Pull request closed without merging**
