### PR TITLE
feat(provider): add mastodon provider

### PR DESCRIPTION
**Pull request by nina-alin**
## ☕️ Reasoning

Added Mastodon Provider.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

#5669 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by balazsorban44** [comment]
Duplicate of #5739. Keep in mind, there has been some noteworthy discussion there.

**Comment by jibla** [comment]
I have published an article about Auth.js, showing how it can be used outside its supported frameworks, purely with Node & Express. I show this with Mastodon OAuth example. If anyone is interested you can check it here: https://medium.com/@jibla/auth-js-exploration-1b6c27cf076f

**Comment by ndom91** [comment]
This has gotten very out of date unfortunately. @nina-alin if you're still interested in getting this merged, could you update to latest `main` as the basefor your PR? 

Might be easier to just create a new branch / PR with your changes :pray:

**Comment by balazsorban44** [comment]
https://authjs.dev/getting-started/providers/mastodon

We have a Mastodon provider now

**Comment by nina-alin** [comment]
Sorry, didn't saw your comment @ndom91. Great to see that this feature finally got merged :)

**Pull request closed without merging**
