### PR TITLE
chore(docs): update `redirectTo` param jsdoc desc in `next-auth`

### LINKED ISSUE #9592: Improve `redirectTo` documentation
### What is the improvement or update you wish to see?

It would be nice that the docs specified that the redirectTo param must be a relative path. I was passing the whole url (www.example.com/whatever) instead of the relativePath (/whatever) and couldn't make it work until I saw the code for the redirectCallback

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/nextjs#signin

### PR DESCRIPTION
**Pull request by lpbonomi**
## ☕️ Reasoning

It tells the user that the redirectTo param should be a relative path and not an absolute URL.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

 

Fixes https://github.com/nextauthjs/next-auth/issues/9592

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — DISMISSED** [review]
Technically this is not true. You *can* use full/external URLs if you also modify the `redirect()` callback.

Which by default only allows relative URLs, or full URLs on the same domain.

See: https://github.com/nextauthjs/next-auth/blob/b3c7a6c3107cdae7a7735e18776ca14c27c445e8/packages/core/src/lib/init.ts#L38-L42

Could this be reflected in the comments maybe? A warning might be in place that redirecting to external sources might be dangerous if you don't control that other domain.

**Review by ndom91 — APPROVED** [review]
LGTM, thanks!

**Comment by ndom91** [comment]
> Technically this is not true. You *can* use full/external URLs if you also modify the `redirect()` callback.
> 
> Which by default only allows relative URLs, or full URLs on the same domain.
> 
> See: https://github.com/nextauthjs/next-auth/blob/b3c7a6c3107cdae7a7735e18776ca14c27c445e8/packages/core/src/lib/init.ts#L38-L42
> 
> Could this be reflected in the comments maybe? A warning might be in place that redirecting to external sources might be dangerous if you don't control that other domain.

I feel like that's pretty convoluted. If someone is going through the trouble to modify this callback they probably understand this option as well. 

Simplifying the explanation of the default, like in this PR, is enough imo

**Comment by lpbonomi** [comment]
@ndom91 I can't merge the PR. If this looks complete, please just go ahead and merge it. If not, I can put some more work on it

**Review by ndom91 — APPROVED** [review]
LGTM

**Pull request merged**
