### PR TITLE
fix: pass options param to openid client instance

### PR DESCRIPTION
**Pull request by progeriof**
## ☕️ Reasoning

Currently it is not possible to pass `additionalAuthorizedParties` in the options argument, as it is required in some cases, e.g. when using hybrid applications and validating multiple audiences.

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

https://github.com/nextauthjs/next-auth/discussions/6966

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by DarkSmile92** [comment]
Much needed for Google SSO implementation with Flutter!

**Comment by ThangHuuVu** [comment]
thanks for the PR, would you be able to reopen the PR to our `v4` branch?

**Comment by balazsorban44** [comment]
Closing as per https://github.com/nextauthjs/next-auth/pull/8442#issuecomment-1710224737

**Comment by mbaquerizo** [comment]
I've opened up a PR to the `v4` branch here: https://github.com/nextauthjs/next-auth/pull/10949

**Pull request closed without merging**
