### PR TITLE
chore(docs): fix typo in `02-oauth-tutorial.mdx`

### PR DESCRIPTION
**Pull request by rosnerdev**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](../Security.md) to disclose the issue to us confidentially.

## ☕️ Reasoning
There is a typo in the docs

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Nice catch!

**Comment by ndom91** [comment]
We do need that first line of the file though, that indicates the start of the frontmatter section.

Can yuo please readd that and we can merge this? Thanks!

**Comment by rosnerdev** [comment]
> We do need that first line of the file though, that indicates the start of the frontmatter section.
> 
> Can yuo please readd that and we can merge this? Thanks!

Hi. That seems to be a bug, since I didn't delete that, but I'm about to readd it.

**Comment by ndom91** [comment]
No worries, thanks for the quick fix!

**Pull request merged**
