### PR TITLE
Add: testing with cypress docs

### PR DESCRIPTION
**Pull request by ndom91**
Added a documentation page to aid in setting up Cypress to login with NextAuth.js in peoples projects.

This setup is what worked for me, but if I missed anything or did something wrong, just let me know.

CC: @JeffersonBledsoe

### CODE REVIEW

**Review by iaincollins — COMMENTED** [review]
Nice work, thank you!

I've been thinking, I'd like to create a topic for Tutorials / Guides.

Do you think we should put this page under a topic like "Tutorials"?

I've got a few draft guides it would be great to place under that if we had it!

**Comment by ndom91** [comment]
Yeah good idea. I'm sure with time there will be more and more as well, and that could be a good place to put them all together.

**Review by iaincollins — APPROVED** [review]
Nice! :D

**Comment by iaincollins** [comment]
I am really happy if you want o merge this in and making it a living document and to update it accordingly if needed with v3 :-)

**Comment by ndom91** [comment]
Yeah no problem. Hopefully it saves others some time getting started testing their NextAuth implementation as well 👍

**Pull request merged**
