### PR TITLE
fix(docs): update Express provider import doc

### PR DESCRIPTION
**Pull request by asierbayon**
## ☕️ Reasoning

Correct providers package and the Github path for the Express documentation.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
@asierbayon the providers should be imported from `@auth/express`, is that not working for you?

**Comment by solo8116** [comment]
the github import is not working for me 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\@auth\express\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by asierbayon** [comment]
@ndom91 hey Nico, you're right, it is exposed from `@auth/express`, however the path is still wrong as it is exposed from the lib folder, just updated my PR.

@solo8116 try `import GitHub from "@auth/core/lib/providers/github"`

**Comment by solo8116** [comment]
still it is not working 

```Cannot find module '@auth/core/lib/providers/github' or its corresponding type declarations```

**Comment by asierbayon** [comment]
@solo8116 sorry, my brain cells are still on vacation-mode 
I meant the lib folder inside @auth/express

`import GitHub from "@auth/express/lib/providers/github"`

**Comment by ndom91** [comment]
Okay so we'd like to have this match the other providers and have the import work with `import GitHub from "@auth/express/providers/github"`, meaning we actually have to update the `exports` in the `framework-express/package.json` instead.

**Comment by solo8116** [comment]
I used ``` import GitHub from "@auth/express/lib/providers/github " ```
but that is also not working

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\@auth\express\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by ndom91** [comment]
Modifying the `exports` map to something like this should do it I think, can you test it?

```json
    "./providers": {
      "types": "./lib/providers/index.d.ts"
    },
    "./providers/*": {
      "types": "./lib/providers/*.d.ts",
      "import": "./lib/providers/*.js"
    },
```

**Comment by solo8116** [comment]
no its not working still the same error is showing
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\@auth\express\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by balazsorban44** [comment]
Fixed in #9564

**Comment by solo8116** [comment]
in the version ^0.1.2 the error is still there 

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\@auth\express\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by roonie007** [comment]
@balazsorban44 

```
Error: No "exports" main defined in platform/node_modules/@auth/express/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:299:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:13)
    at resolveExports (node:internal/modules/cjs/loader:621:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:711:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (platform/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (platform/node_modules/esbuild-register/dist/node.js:4799:36)
    at Function.d._resolveFilename (platform/node_modules/@modern-js/utils/dist/compiled/tsconfig-paths/index.js:1:7401)
    at Function.Module._load (node:internal/modules/cjs/loader:1038:27)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
```

**Pull request closed without merging**
