### PR TITLE
chore: export adapter types

### PR DESCRIPTION
**Pull request by Dwlad90**
## ☕️ Reasoning

What changes are being made? What feature/bug is being fixed here?
Export types for adapters were missing from the `exports` filed in `package.json` and are added by this PR.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
I'm curious about this change, do you have a setup where this is necessary?

`exports` is used for entry points, not for types: https://nodejs.org/api/packages.html#exports

**Comment by TxHawks** [comment]
@balazsorban44 TypeScript extends how `exports` is used in node to also include type info. See an example [here](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing).

While this example isn't the exact same as the use-case in this pull request, it does show that `exports` is also meant to be used for types.

Currently, there is no way for consumers to directly import the types defined in `adapters.ts. This PR enables users who need them in their code to explicitly import them without adding to the default public API surface. An alternative approach could be to add `export * from './adapters';` to `index.ts`, which would just make the types in `adapters.ts` part of the default public API of the library.

**Comment by TxHawks** [comment]
@balazsorban44 any chance to get this merged?

**Review by ThangHuuVu — COMMENTED** [review]
We have exported this in our new package `@auth/core` - do you consider switching? 
Otherwise, could you please open a new PR to v4 (or fix this one)? That is where we accept PRs to `next-auth`, moving forward. Sorry for the inconvenience 🙇‍♂️

**Comment by Dwlad90** [comment]
> We have exported this in our new package `@auth/core` - do you consider switching? Otherwise, could you please open a new PR to v4 (or fix this one)? That is where we accept PRs to `next-auth`, moving forward. Sorry for the inconvenience 🙇‍♂️

@ThangHuuVu 
We tried a new package `@auth/core` and it doesn't work in the our project because of the `module` type of the package.
I've updated this pull request and waiting it to be merged.

Thank you for the conversation!

**Comment by ThangHuuVu** [comment]
hey @Dwlad90 could you please reopen the PR against v4 branch? I'm closing this one, sorry for the inconvenience 🙏

**Pull request closed without merging**
