### PR TITLE
chore(ci): disable node cache to speed up ci

### PR DESCRIPTION
**Pull request by boredland**
## ☕️ Reasoning

in my experience restoring and storing cache costs so much time, that the (tiny if even) gain during install is gone. this tries to prove that for next-auth.

[before](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689): 

install: 1m 16s
post-setup: 1m 44s

[after](https://github.com/nextauthjs/next-auth/actions/runs/4409880568/jobs/7726722542):

install: 1m 11s
post-setup: 0s

... also yamllint complaint about redundant string indicators.

## 🧢 Checklist

- [ ] Documentation
- [x] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]
Interesting observation. We should have a deeper look into our CI at some point. We often have cache misses for the docs build as well.

We can merge this for now and see. Thanks!

**Comment by AlexErrant** [comment]
In your "[before](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689)", [the workflow file](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/workflow) says `cache: "pnpm"`, which is great, [but the run does _not_ use the cache](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689#step:4:19): "pnpm cache is not found". This is probably because the `package.json` or lockfile changed and no cache for that package.json/lock file exists. After this run however, [it does exist](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689#step:10:7), so it should be available for subsequent runs and may improve their runs. You may still be correct in that restoring from a cache isn't as fast as downloading from scratch, but your `before` does not demonstrate this.

In my own project (not a fork of NextAuth), caching is faster. Here's a screenshot of my own project showing how the cache improves overall `pnpm i` times (n=1):

image

[Left.](https://github.com/AlexErrant/Pentive/actions/runs/4758458558/jobs/8456543231#step:4:26) [Right.](https://github.com/AlexErrant/Pentive/actions/runs/4768601023/jobs/8478100794#step:4:21)

**Comment by SauravMaheshkar** [comment]
> In your "[before](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689)", the [workflow file](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/workflow) says `cache: "pnpm"`, which is great, but the run does _not_ use the cache: "[pnpm cache is not found](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689#step:4:19)". This is probably because the `package.json` or lockfile changed and no cache for that package.json/lock file exists. After this run however, [it does exist](https://github.com/nextauthjs/next-auth/actions/runs/4409775149/jobs/7726475689#step:10:7), so it should be available for subsequent runs and may improve their times. You may still be correct in that restoring from a cache isn't as fast as downloading from scratch, but your `before` does not demonstrate this.
> 
> In my own project (not a fork of NextAuth), caching is faster. Here's a screenshot of my own project showing how the cache improves overall `pnpm i` times (n=1):
> 
> image
> 
> [Left.](https://github.com/AlexErrant/Pentive/actions/runs/4758458558/jobs/8456543231#step:4:26) [Right.](https://github.com/AlexErrant/Pentive/actions/runs/4768601023/jobs/8478100794#step:4:21)

@balazsorban44 thoughts on this 👀 ?

**Comment by AlexErrant** [comment]
Gonna guess he doesn't care that much about a CI speedup. If you care, you could fork, run it in your own repo, and come back with empirical runtimes.

**Pull request merged**
