### PR TITLE
fix: MongoServerSelectionError: getaddrinfo ENOTFOUND

### PR DESCRIPTION
**Pull request by YuriGor**
**What**: Updated typeorm to patch v0.2.30 
**Why**: MongoServerSelectionError: getaddrinfo ENOTFOUND issue fixed in this patch version:
https://github.com/typeorm/typeorm/issues/7009
**How**: bump typeorm dep version to patch 30
**Checklist**:
- [ ] Documentation n/a
- [ ] Tests n/a
- [x] Ready to be merged

I guess it should be safe to merge since it's only patch vaersion change in dependency.

### CODE REVIEW

**Comment by YuriGor** [comment]
typeorm v0.2.30 is not published yet, so this PR is not correct until this will happen.

**Review by balazsorban44 — COMMENTED** [review]
@YuriGor this typeorm version is out now, shouldn't the package-lock.json file also be updated?

**Comment by YuriGor** [comment]
It would be easier to just take fresh canary and update typeorm to the latest rather then trying to resolve conflicts in package-lock.
Also I couldn't run tests locally, some issues with docker.

**Comment by YuriGor** [comment]
created new one #1145

**Pull request closed without merging**
