### PR TITLE
Add db uri support

### PR DESCRIPTION
**Pull request by iaincollins**
Can now specify a database as a URI / connection string!

Additional options can be passed as query parameters.

Examples:

```
database: 'mysql://username:password@127.0.0.1:3306/database_name?synchronize=true',
```

```
database: 'postgres://username:password@127.0.0.1:5432/database_name?synchronize=true',
```

```
database: 'mongodb://username:password@127.0.0.1:27017/database_name?synchronize=true',
```

This is not a breaking change as passing an object still works, this just makes database configuration much easier for most use cases.

This matches the behaviour in the documentation - I wanted to make it this simple from the outset (which is is how it's described in the documentation), but took a little while to get to this point.

@TODO Update documentation to include these examples (and update the example site to use this approach too).

### CODE REVIEW

**Comment by iaincollins** [comment]
Published as `next-auth@2.0.0-beta.49`

**Comment by LoriKarikari** [comment]
This already worked? I was connecting to Postgres with a string. Or did you break it 😂

**Comment by iaincollins** [comment]
LOL really? (!) It was supposed to work that way, but I wasn't able to get it to work.

I think it was maybe working by accident! 😂

I'd be interested to know what your config looked like!

**Comment by LoriKarikari** [comment]
It was a few versions ago I don't remember which one exactly. I started using SQLite for quick testing. It was the same as above but without `synchronize=true` and it worked perfectly lol.

**Comment by LoriKarikari** [comment]
That's also why I added it to the docs.

**Comment by iaincollins** [comment]
It is actually supposed to be a feature of TypeORM according to some docs, as are using environment variables, but I could get them to work either. 🤷‍♂️

It's possible I was looking at old docs though - ran into that quite a bit with TypeORM, especially when it came to adding MongoDB support.

**Pull request merged**
