### PR TITLE
fix(provider): modify response.name to response.nickname (Naver)

### LINKED ISSUE #5914: Bug in Naver Provider
### Provider type

Naver

### Environment

  Binaries:
    Node: 16.17.1 - ~\AppData\Local\Volta\tools\image\node\16.17.1\node.EXE
    Yarn: 3.3.0 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 8.15.0 - ~\AppData\Local\Volta\tools\image\node\16.17.1\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.3.1 => 12.3.1
    next-auth: ^4.17.0 => 4.17.0
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/jintak0401/timegambit-blog

### Describe the issue

Original naver provider's code here.

```ts
...
export default function Naver<P extends NaverProfile>(
  options: OAuthUserConfig<P>
): OAuthConfig<P> {
  return {
    id: "naver",
    name: "Naver",
    type: "oauth",
    authorization: "https://nid.naver.com/oauth2.0/authorize",
    token: "https://nid.naver.com/oauth2.0/token",
    userinfo: "https://openapi.naver.com/v1/nid/me",
    profile(profile) {
      return {
        id: profile.response.id,
        name: profile.response.name,
        email: profile.response.email,
        image: profile.response.profile_image,
      }
    },
    checks: ["state"],
    options,
  }
}
```

In this code `profile` function return object with `name: profile.response.name`. but arguments profile has no name but nickname.

```
// profile object
{
  resultcode: '00',
  message: 'success',
  response: {
    id: 'some-id',
    nickname: 'my nickname',
    profile_image: 'https://phinf.pstatic.net/contact/20221128_144/1669643453452gFEDI_PNG/image.png',
    email: 'mynickname@naver.com'
  }
}
```

So, when I use useSession().data.user, there is no name field. It need to be modified like this.

```ts
- name: profile.response.name
+ name: profile.response.nickname
```

### How to reproduce

Just implement naver login with [this docs](https://next-auth.js.org/providers/naver)

### Expected behavior

```js
const { data: session } = useSession();
```
session.user.name has specific value.

### PR DESCRIPTION
**Pull request by jintak0401**
## ☕️ Reasoning

```js
const { data: session } = useSession();
```

`session.user.name` is undefined. Because `profile.response`(naver.ts) has nickname not name. 

Here is profile object.
```js
// profile object
{
  resultcode: '00',
  message: 'success',
  response: {
    id: 'some-id',
    nickname: 'my nickname',
    profile_image: 'https://phinf.pstatic.net/contact/20221128_144/1669643453452gFEDI_PNG/image.png',
    email: 'mynickname@naver.com'
  }
}
```

So I modify from

```ts
name: profile.response.name
```

to

```ts
name: profile.response.nickname
```

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: [Bug in Naver Provider](https://github.com/nextauthjs/next-auth/issues/5914)

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by ThangHuuVu — APPROVED** [review]
Thanks @jintak0401. Could you add a screenshot of the result as proof of completion for this PR? 🙌

**Comment by jintak0401** [comment]
Of course! Here are before and after screenshot.

## before
image

## after
image

**Comment by jintak0401** [comment]
@ThangHuuVu 

I checked @Jtree03 comment, he is right. I checked [this documents](https://developers.naver.com/docs/login/profile/profile.md), it seems my mistake. There are both fields name and nickname. (And I only set nickname in Naver developer settings) I think Naver providers need to give both fields, or be selectable according to need like @Jtree03 suggestion.

**Comment by Jtree03** [comment]
The API already existed.

You can change name column with next code.

```typescript
NaverProvider({
  clientId: process.env.NAVER_ID!,
  clientSecret: process.env.NAVER_SECRET!,
  profile: (profile) => ({
    id: profile.response.id,
    name: profile.response.name,
    email: profile.response.email,
    image: profile.response.profile_image,
  }),
}),
```

**Pull request merged**
