### PR TITLE
fix(providers): correct authorization url for Atlassian

### PR DESCRIPTION
**Pull request by hckhanh**
## Checklist 🧢

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## Affected issues 🎟

#2987

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]

**Comment by balazsorban44** [comment]
Gentle push here @hckhanh. We are planning to release v4 stable soon. It would be nice to get this fixed before that. :slightly_smiling_face:

**Comment by lluia** [comment]
I was trying the changes from @hckhanh locally 🕵🏽‍♂️ , and also got an error when pointing the provider to:
```
https://auth.atlassian.com/.well-known/openid-configuration
```
Here's the proof:

Screenshot 2021-11-17 at 09 08 06

After clicking `Sign in with Atlassian` we're re-directed to Atlassian correctly with the right credentials, Atlassian does a set of redirects `302s,303` to end in this URL:

```
https://api.atlassian.com/oauth2/authorize/consent
```

Screenshot 2021-11-17 at 09 08 24

Which gives back a 404 🤷🏽‍♂️ . Everything seems well configured on my side on the Atlassian console, I'm using the **clientId** and **secret** for my app and setting up the callback URL to `https://localhost:3000/api/auth/callback/atlassian` 🤔 . The protocol type is `OAuth 2.0 (3LO)` 

Here's a video reproducing the issue:

atlassian

I noticed in the docs, [in the example call to `https://auth.atlassian.com/authorize`](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/#implementing-oauth-2-0--3lo-), the request has an extra param `prompt=consent` which we don't include in our **NextAuth** request.

**Comment by lluia** [comment]
I tried with this config as well:
```ts
{
    id: "atlassian",
    name: "Atlassian",
    type: "oauth",
    wellKnown: "https://auth.atlassian.com/.well-known/openid-configuration",
    authorization: {
      params: {
        audience: "api.atlassian.com",
        prompt: "consent",
      },
    },
    profile(profile) {
      return {
        id: profile.account_id,
        name: profile.name,
        email: profile.email,
        image: profile.picture,
      }
    },
    options,
  }
 }
 ```
 which appends `prompt=consent` to the request:
```
https://auth.atlassian.com/authorize?client_id=foo&scope=openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fatlassian&audience=api.atlassian.com&prompt=consent&state=bar'
```
 but still no luck 😕

**Comment by balazsorban44** [comment]
Not sure if a typo in https://github.com/nextauthjs/next-auth/pull/2999#issuecomment-971343134, but you wrote `https://localhost:3000/api/auth/callback/atlassian`, should be `http://localhost:3000/api/auth/callback/atlassian`, drop the s

**Comment by hckhanh** [comment]
@lluia the current configurations that will for me:

```ts
    AtlassianProvider({
      clientId: env.get("ATLASSIAN_CLIENT_ID").required().asString(),
      clientSecret: env.get("ATLASSIAN_CLIENT_SECRET").required().asString(),
      authorization: {
        url: "https://auth.atlassian.com/authorize",
        params: {
          scope: "offline_access read:me",
        },
      },
    }),
```

Currently I am using next-auth `4.0.0-beta.6` and @next-auth/prisma-adapter `0.5.2-next.19`. I only override the url and scope compare to the default settings from the package

**Comment by balazsorban44** [comment]
even `url` override should not be necessary, as we deep merge your config with the built-in one.

**Comment by balazsorban44** [comment]
will pair on this with @lluia and try to figure out a way to use `wellKnown`. it's safer, more future-proof.

**Comment by lluia** [comment]
@balazsorban44 yep my typo, in the **Atlassian console** though I had the callback URL well set (with `http`)  👍🏽 
@hckhanh I'm going to have a go with your config 🤞🏽

**Comment by lluia** [comment]
Interesting, as @hckhanh pointed out, I got it working with the old config, but supplying the scopes, which I wasn't doing before...
```ts
authorization: {
  params: {
    scope: "offline_access read:me",
  },
},
```
Here's the proof of the sign in:

altlassian-working

Probably there's something not connecting well with the [well-known config](https://auth.atlassian.com/.well-known/openid-configuration) 🤔 (I tried again with it but supplying scopes this time and still no luck 🥲).

@balazsorban44 I suggest merging this with the old config, and opening an issue/spike to try to make it work with **well-know** post **v4** 🎻

**Comment by balazsorban44** [comment]
@lluia could you address what we have talked about and get this merged? :pray:

**Pull request merged**
