### PR TITLE
Use secure cookie prefix in Vercel preview apps

### PR DESCRIPTION
**Pull request by cathykc**
**What**:

Use secure prefix for cookie name if application is a Vercel preview app.

**Why**:

For NextAuth to work in Vercel preview apps we need to leave `NEXTAUTH_URL` unset so we can fall back on `VERCEL_URL` - this changes for every preview deployment so we can't statically set it.

When `NEXTAUTH_URL` is unset, the previous logic would have `secureCookie = false` which results in an error when trying to decode the JWT in preview apps. This change fixes that.

**How**:

Updated the default value for `secureCookie` - no other changes.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [X] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
Couldn't you just call `getToken` like so?:

```js
getToken ({
  secureCookie: process.env.NEXTAUTH_URL?.startsWith('https://') ?? process.env.VERCEL_ENV === "preview"
  ... your own config here
})
```

I don't think we should optimize defaults for any services too much. (We already use VERCEL_URL as a fallback in some places, which honestly I don't really understand)

I might feel too strongly about this, but I think this is easy to fix in user-land and so I don't want to accept this PR. You could maybe open an issues/discussion, and if this gets traction, we could add it anyway, but I want to hear what other think.

**Comment by cathykc** [comment]
That's exactly what I did to get past this in my project but it took a while of digging to figure out that `secureCookie` parameter needed to be customized for preview apps and it seems from reading through issues and documentation that `next-auth` does make it easy to use with Vercel out of the box. @iaincollins talks about defaults and preview apps in Vercel here https://github.com/nextauthjs/next-auth/issues/497. 

Because there are already a lot of `VERCEL_URL` fallbacks in this library it makes sense to me to also have this default to a Vercel deployment environment but I'm happy to create an issue and see if there's interest! :)

**Comment by jonlow** [comment]
For anyone looking at this, I can confirm 

> Couldn't you just call `getToken` like so?:
> 
> ```js
> getToken ({
>   secureCookie: process.env.NEXTAUTH_URL?.startsWith('https://') ?? process.env.VERCEL_ENV === "preview"
>   ... your own config here
> })
> ```
> 
> I don't think we should optimize defaults for any services too much. (We already use VERCEL_URL as a fallback in some places, which honestly I don't really understand)
> 
> I might feel too strongly about this, but I think this is easy to fix in user-land and so I don't want to accept this PR. You could maybe open an issues/discussion, and if this gets traction, we could add it anyway, but I want to hear what others think.

I can confirm that I can use next-auth in vercel preview deploys using this  ☝️ and omitting  `VERCEL_URL` from previews

**Comment by aakash14goplani** [comment]
@jonlow - If possible, can you provide a working example of how have you integrated `getToken` in your code flow.
Context - I am using OAuth provider with NextAuth and things are breaking in Vercel preview environment due to mismatch in callback urls.

**Pull request closed without merging**
