### PR TITLE
feat(provider): SMS provider

### LINKED ISSUE #1562: Add an example/tutorial for passwordless with SMS?
**Summary of proposed feature**

I'd like to use NextAuth to add passwordless authentication to an app using SMS rather than email to deliver the tokens. It would look like:

1. overriding `generateVerificationToken` to create a shorter token that a user can feasibly type
2. override `sendVerificationRequest` to use Twilio or similar to send an SMS message with the token
3. create a page where the user can type the token, similar to entering a 2FA code

It would be good to have an official tutorial or example showing how to implement this securely. I might be able to contribute one in the future.

**Purpose of proposed feature**
Some groups of users, particularly those with poor digital skills, will find it easier to verify their identity with an SMS rather than an email.

Sometimes (for example, a community group of volunteers) an organiser may only have phone numbers for the users, rather than email addresses.

**Detail about proposed feature**
A detailed description of how the proposal might work (if you have one).

**Potential problems**
Not sure about the security impact of shortening the tokens.

**Describe any alternatives you've considered**
A clear and concise description of any alternative options you've considered.

**Additional context**
Related to these three issues:
https://github.com/nextauthjs/next-auth/issues/159
https://github.com/nextauthjs/next-auth/issues/709
https://github.com/nextauthjs/next-auth/issues/414

Particularly this response: https://github.com/nextauthjs/next-auth/issues/709#issuecomment-784077142

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes!

### PR DESCRIPTION
**Pull request by mahieyin-rahmun**
## Reasoning 💡
This PR attempts to add the functionality for a SMS provider as per #1562. An SMS provider will work almost the same way as Email provider. However, instead of sending the login link via email, it will make use of OTP and send it over to the provided phone number of the user.

In the current state, the actual implementation depends on the choice of SMS/Verification provider selected by the developer, such as MessageBird, Twilio or equivalent. The general principle is:

1. User initiates sign in flow by navigating to the app and entering his/her phone number.
2. An implementation for a `sendSmsVerificationRequest` function must be provided in the SMS Provider options which takes the user's provided phone number as input and calls the appropriate API (MessageBird, Twilio etc) to create a verification request object and send the OTP to user's phone. This function should return the `id` of the created verification request object.
3. Simultaneously, user is redirected to the `verify-request` page to enter the OTP. An `HttpOnly` cookie is set that contains the `id` returned in Step 2. This cookie should only be sent along with the submitted OTP to the `api/auth/callback` endpoint and it should be set to expire as soon as the OTP itself has become invalid.
4. An implementation for `verifySmsVerificationRequest` function must be provided in the SMS provided options, which will take a  verification request ID and the OTP entered by the user as parameters. Then, the appropriate API (MessageBird, Twilio) should be called to check if the verification ID and token pair are valid. If everything checks out, the user is now logged in using his/her phone.

Caveats:
1. Currently, this only works with JWT sessions. No data is persisted in the database.
2. No other provider so far has made use of phone numbers. As such, in order to be able to store e.g. phone number of the user in database, a change in the database schema is required.
3. Since user enters phone number instead of email, unless `jwt` and `session` callbacks are overridden manually, session object will end up being empty.
4. Dependency on 3rd party API to send SMS means certain customization options such as length of OTP, OTP expiry etc can only be done if the API in question supports it.

Interested to hear everyone's opinions regarding this implementation and possible ways to improve it further.

## Checklist 🧢

- [x] Documentation
- [x] Tests
- [ ] Ready to be merged

## Affected issues 🎟

Closes #1562. Related to #159, #709, #1465

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Very interested to see this when I have more time! Just some quick suggestions.

I think instead of focusing only on SMS, we should call this type of provider Token, or Passwordless instead. once the basics are laid out (most of it already is thanks to the Email provider), we could create multiple providers for multiple services you mentioned. In v4 I intend to separate provider imports for smaller bundle size to the end user. any additional dependencies could be optional peer dependencies.

I would like that this will be based on the `next` branch though, as most of the work on v3 is done from my part. aiming for v4 release this summer.

**Comment by mahieyin-rahmun** [comment]
> I think instead of focusing only on SMS, we should call this type of provider Token, or Passwordless instead. once the basics are laid out (most of it already is thanks to the Email provider), we could create multiple providers for multiple services you mentioned. 

Yeah, it is quite similar to the Email provider, so these type of providers could be very easily refactored under a single "Passwordless" type.

> I would like that this will be based on the `next` branch though, as most of the work on v3 is done from my part. aiming for v4 release this summer.

Great! Looking forward to v4, then. I will resume working on this once v4 is released. I also cannot wait to try out the features of v4 in my own projects :D

**Comment by mtt87** [comment]
👋  Just saw this PR and I think it's really interesting!

Completely agree with @balazsorban44 
> I think instead of focusing only on SMS, we should call this type of provider Token, or Passwordless instead

I was actually thinking a couple of weeks ago to build a prototype for this functionality as I wanted to see if it's possible to use it with our product.


Self promotion:  (but it's relevant to the subject) 😄 
@mahieyin-rahmun bear in mind that using SMS OTP is **very insecure**.
SMS can be easily hijacked and people can be victim of a SIM swap attack.
If you are curious we are building a better alternative which is not only **more secure** but it's also much **more user friendly**, and it takes care both of number verification and sim swap check to prevent these attacks. 

https://tru.id/

**Comment by followbl** [comment]
@mahieyin-rahmun awesome PR - really well documented. @balazsorban44 we would be super interested in this feature in a 4.0 release, let us know if there's anything we could help with to make this happen.

**Comment by mtt87** [comment]
Same here, would be happy to help make it token agnostic so that could work with our use case as well, not only with insecure 🔓  SMS ancient technology 😄

**Comment by balazsorban44** [comment]
have you all seen https://github.com/nextauthjs/next-auth/discussions/1465

**Comment by mtt87** [comment]
Nope! Thanks for sharing 😄

**Pull request closed without merging**
