### PR TITLE
chore(docs): add a dev.to blog post (Next.js/NextAuth.js/TypeScript/Microsoft Graph)

### PR DESCRIPTION
**Pull request by glaucia86**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes:  Not Asked

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by glaucia86** [comment]
Hi, @balazsorban44 and @ndom91!

I made a new contribution to the Auth.js documentation. Please, let me know if I need to include something more. And congratulations on the hard work for this incredible product!

**Comment by balazsorban44** [comment]
Thanks, but after reading the article, I don't think we would like to accept it on our docs page. Here is a list of things that were a blocker in my opinion:

- I'm not sure if the intermediate dev.to article is necessary, it adds an extra step to get to the actual article.
- Make sure the casing/spelling is correct and uniform (Next.js, not Next.Js, Node.js, not Node.Js, NextAuth.js, not NextAuth, etc.)
- Don't use all-caps (eg.: LINK HERE, HERE, etc.)
- Pages like https://microsoft.github.io/MicrosoftCloud/tutorials/docs/Authentication-App-With-NextJs-And-Microsoft-Graph/Configuring-Application-Azure-Active-Directory if using images, should have proper alt texts.
- Explain the use of scopes (eg.: What's "Presence.ReadWrite.All" doing?)
- Grammar check (eg.: "In this moment we are not going to use none UI framework").
- I would not put author comments in code snippets in an article you intend for people to copy-paste, feels bit invasive, and they'll likely remove it while copying anyway. Also, the file path might change (maybe the reader wants to put the file somewhere else) so that's also unnecessary.
- There seems to be some incorrect statements like:
> As we are using [TypeScript](https://www.typescriptlang.org/) in this application, we need to transpile the code

That's not why the transpilation is needed. Next.js takes the source code and - well, transpiles TS too - highly optimizes it for production. Besides, the build step is not necessary in dev, but the article suggests so

- There are typos (`[...nextauth]].ts` -> `[...nextauth].ts`)
- `NEXTAUTH_URL` is not needed in dev.

- Material UI is mentioned, but never used
- A Microsoft Graph client npm package is installed, but never used

Even though we are not adding this, I suggest addressing these points in your article.

**Comment by glaucia86** [comment]
Hi, @balazsorban44. English is not my first language. I am a Brazilian person trying to make some contributions here.
Thank you in advance.

And wish you all the best

**Comment by minsk-dev** [comment]
Absolutely unnecessary to [go on Twitter and attack the reviewer of this PR](https://twitter.com/glaucia_lemos86/status/1619529222799892482).

**Comment by glaucia86** [comment]
I made the changes you asked me. And thank you so much, @balazsorban44 for the feedback. I really appreciate.

And about the tweet that @minsk-dev mentioned, it was a frustration that I exposed in about to the way the PR was treated (I think there would be no need to have closed the PR. Simply keeping it open and I would make the necessary changes. But, I understand your approach here - this is my feedback that I would like for you). 
But, it's already removed. I didn't attack anyone and this it's pure disharmony construction to cause problems in an already resolved situation. Thank you in advance.

**Comment by balazsorban44** [comment]
Would have appreciated if any feedback was directed at me, I now cannot even see that tweet as it seems to be deleted.

I assume you also deleted a comment here about not being  a native-speaker, which is the case for most of us. My comment about using proper grammar wasn't directed at your person in any capacity. I make mistakes all the time, but when it comes to public documentation, I appreciate if it's pointed out to me in the name of professionalism. I apologize if you felt attacked by that comment, it was not the intention.

FWIW, another reason I don't think the article is a good fit, as it's highly complex and multi-page, which in my opinion might be hard to follow.

Our focus is on documentation improvements currently, and we would like to make sure that our guides cover most cases, so highly-specific examples can be maintained by the community outside the official docs.

With other words, I think the community resources section should be removed, as we have no control of the content and it can easily become outdated as we don't follow it up, so we are essentially advocating for not up-to-date recommendations, which is bad for our community.

If you felt that something was missing in the official documentation, we welcome opening an issue and we would like to address it.

I'm glad that you decided to take the feedback to fix up the article. 🙏💚

**Comment by glaucia86** [comment]
I totally understand you. And thank you very much for your notes. I have already made the correction, and it will be very welcome.

The "article" was written that way because it is intended to be used in universities as a workshop. Note that the other workshops are in this structure. It was an internal request.

And regarding the community part, yes. I agree with you. There are tutorials there that are outdated, and one there has a 500 error. I agree with you to remove it.

Of course. Any other issue requests and PR's I'll be sending in case they need to be improved. Thanks for your time, @balazsorban44 :😉

**Pull request closed without merging**
