### PR TITLE
Using Firebase Admin SDK

### PR DESCRIPTION
**Pull request by nhuethmayr**
**UPDATE**: This PR is closed - please visit https://github.com/nextauthjs/next-auth/pull/5628

New adapter that uses the Firebase Admin instead of the client-side SDK

## ☕️ Reasoning

The current implementation of firebase-adapter uses the client SDK. This has the severe drawback that the Firestore Rules need to be opened up. Instead of using the client-side SDK, we should be using the server-side one. That way we can keep the Firestore rules closed and still integrate nicely with FB

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

This PR solves an architectural problem with the firebase-adapter as descibed in discussion [5049](https://github.com/nextauthjs/next-auth/issues/5049)

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

## ❓ Questions 

- Do we want to release this code as an independent adapter? `firebase-admin-adapter`
- Do we want to replace the current implementation altogether?

### CODE REVIEW

**Comment by NorbertHuethmayr** [comment]
Cause it received no love 😢 from the package owners. I could, however, talk to them in the meantime and they said that they are looking into it.

**Comment by CR1AT0RS** [comment]
Sad, we appreciate your work to solve this security issue.

**Comment by NorbertHuethmayr** [comment]
Its coming 🆒

**Comment by bcthakre** [comment]
@NorbertHuethmayr . Do you know if you got any reply from maintiner on when they will be pushing it. Thanks for work. Its really important to not breach the security rules

**Comment by BossBele** [comment]
+1

**Comment by NorbertHuethmayr** [comment]
I've created a new PR which is up-to-date and addresses some more minor issues with the old one. Please give it your upvote 👍

**Comment by shriharip** [comment]
Could you let us know which is that PR. Thanks again for your efforts.

**Comment by Chibionos** [comment]
@NorbertHuethmayr I went ahead and checked you PR and upvoted it checking with the owners to see if we can push it through

**Comment by dorji-tshering** [comment]
+1

**Pull request closed without merging**
