### PR TITLE
Add app router docs for middleware

### PR DESCRIPTION
**Pull request by jacobhq**
## ☕️ Reasoning
Docs are currently unclear with regards to use of middleware w/ app router. This documents implementation in app router.

## 🧢 Checklist

- [x] Documentation
- [x] Tests - In prod at pong.jhqcat.com (https://github.com/jacobhq/pong/blob/main/web/middleware.ts)
- [ ] Ready to be merged - I think the description could be a bit more concise

## 🎫 Affected issues
https://stackoverflow.com/questions/74191340/next-auth-middleware-default-is-not-working
 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by jacobhq** [comment]
A couple of extras:
- I love this project, and use it all the time. Thanks y'all!
- Sorry I didn't create an issue - it seemed like a quick fix
- Does this need to be merged into v5 as well?

It's late in my time, but tomorrow I will improve the description a bit!

**Comment by ndom91** [comment]
Thanks for your interest! In general we're not updating the old docs anymore, but this might be an important one - I'll talk to the team.

Regarding your follow-up questions - this doesn't need to be updated in v5 docs as Middleware is imported completely differently and we've thankfully covered this in the [new docs already](https://authjs-nextra-docs.vercel.app/getting-started/session-management?tab=protecting#nextjs-middleware) :wink:

**Comment by ndom91** [comment]
Hey sorry after looking at it again, middleware is covered on that page already - and is the same between pages / app router - middleware doesn't necessarily have anything to do with app router :thinking: 

And the new docs cover a simliar example as well. Thanks for your interest, but Im going to close this PR :pray:

**Comment by jacobhq** [comment]
Thanks!

**Pull request closed without merging**
