### PR TITLE
Add support for Node 18

### LINKED ISSUE #5639: Node.js 18 Support
### Question 💬

Node.js 18 LTS is starting, but this repository restricts the use of Node.18 in the engine in package.json.
Bugs for Node.js 18 seem to be all closed, is there anything blocking support?

I opened a discussion before, but now that LTS has started, I'll post it here as well.
https://github.com/nextauthjs/next-auth/discussions/5329

### How to reproduce ☕️

----

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

### PR DESCRIPTION
**Pull request by ncmbch**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](../Security.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Add Support fo the current LTS Version of Node (v18)

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: [Node.js 18 Support](https://github.com/nextauthjs/next-auth/issues/5639)

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by rdgr** [comment]
Happy to see a PR to add Node 18 support! :)

**Comment by trevoro** [comment]
Anything I can do to help this one along?

**Review by ThangHuuVu — CHANGES_REQUESTED** [review]
Thanks for the PR @ncmbch 🙌
Please update the node engine in `packages/next-auth/package.json` too

**Review by ThangHuuVu — APPROVED** [review]
LGTM!

**Comment by ThangHuuVu** [comment]
On second thought, it may be better to follow `openid-client`'s supported engine strategy, since this is our main Node.js dependency.
See: https://github.com/panva/node-openid-client/commit/9aefba30dcf0e312051e6844b35b06bc457488d5
cc @balazsorban44

**Comment by balazsorban44** [comment]
We can land this now, upcoming changes will make the engines option obsolete.

**Pull request merged**
