### PR TITLE
fix(adapters): allow async sqlite client libs when using drizzle adapter

### LINKED ISSUE #8335: Support Async SQLite Clients with DrizzleORM
### Description 📓

Currently, Auth.js' DrizzleORM SQLite adapter does not support Async SQLite clients like the [Turso/LibSQL client](https://orm.drizzle.team/docs/installation-and-db-connection/sqlite/turso) or the [Cloudflare D1 client](https://orm.drizzle.team/docs/installation-and-db-connection/sqlite/d1). This is due to the queries returning promises, which are not properly dealt with

I would be happy to submit a PR to fix this, as most of the code would be almost exactly the same as with the synchronous SQLite client. However, I am not sure how to go about implementing it. Would it make the most sense to create an entirely separate "subadapter" like the ones for MySQL and Postgres, or is there a better way to implement this?

### How to reproduce ☕️

Simply create an Auth.js project with the Drizzle adapter and use an asynchronous SQLite driver (in my case, the Turso/LibSQL driver). Try logging in, logging out, and logging in again. The second time you should see Auth.js trying to create a duplicate OAuth account because the query in `getUserByAccount` returns a promise, which is not resolved.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

### PR DESCRIPTION
**Pull request by diegoquiroz**
## ☕️ Reasoning

Not all Drizzle clients are fully supported. This PR adds 'await' for the queries that return promises.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: #8335 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by AsyncBanana** [comment]
A lot of these additions are unnecessary; only functions like `linkAccount` and `getUserByAccount` that operate on the result require async/await. The rest are already handled correctly.

**Comment by gediminastub** [comment]
Maybe any news on this? Thanks!

**Comment by jasongitmail** [comment]
Can confirm this code works. I used [patch-package](https://www.npmjs.com/package/patch-package) to implement it locally until this is merged.

**Comment by jasongitmail** [comment]
I spoke too soon. The 1st signin works successfully using this code. But after signing out, signing in a 2nd time causes an error:

> [auth][error][OAuthAccountNotLinked]: Read more at https://errors.authjs.dev#oauthaccountnotlinked
> [auth][cause]: OAuthAccountNotLinked: Another account already exists with the same e-mail address

Given I only have one provider installed (Github OAuth), this implies it may be adapter related, potentially the `getUserByAccount()` method. [It seems others have this issue](https://github.com/nextauthjs/next-auth/issues/8377) too.

**Comment by MrCuriousGuy** [comment]
First of all, thank you for making this contribution!

I was wondering if it could be part of the scope of this PR to also add the drizzle-supported async database clients (currently libsql and cloudflare) to the accepted sqlite-based database client types in the [index.ts](https://github.com/nextauthjs/next-auth/blob/f02867851107725b155e34e197cb8842425ab842/packages/adapter-drizzle/src/index.ts#L262)? Currently, trying to initialize the adapter with a drizzle-client based on a libsql-client leads to type errors.

**Pull request closed without merging**
