### PR TITLE
docs: respect color scheme

### PR DESCRIPTION
**Pull request by saisrikardumpeti**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Please address the comment: https://auth-docs-git-fork-the-r3aper7-patch-color-authjs.vercel.app/#thread-id=UOnro

**Comment by the-r3aper7** [comment]
> Please address the comment: https://auth-docs-git-fork-the-r3aper7-patch-color-authjs.vercel.app/#thread-id=UOnro

I don't know what to do however i see login to comment but it is showing.
team_access

**Comment by balazsorban44** [comment]
My bad...
image

The color needs to support both dark/light mode

**Review by balazsorban44 — APPROVED** [review]
Thanks! Looks good in both light and dark! :tada:

Regarding local dev issues, check out https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md#setting-up-local-environment and if it does not help, you can open an issue with more details. :+1:

**Pull request merged**
