### PR TITLE
Add MSSQL support to TypeORM adapter

### PR DESCRIPTION
**Pull request by D10221**
+Add mssql support to default typeORM adapter

#489

### CODE REVIEW

**Comment by iaincollins** [comment]
I saw you ask about mssql support in #489 before I went to bed last night, as was going to leave some tips...

Then I woke up to this.

This is amazing, I'm stunned by how complete this is (including tests, fixtures and documentation!) and how it came out of nowhere. This is wonderful! Thank you so much. <3

If you have any recommendations for mssql cloud database providers I can use to try it out would be much appreciated. I have an Azure account, I guess I should spin one up on there...

**Comment by iaincollins** [comment]
> If you have any recommendations for mssql cloud database providers I can use to try it out would be much appreciated. I have an Azure account, I guess I should spin one up on there...

Oh wait, you even included a Docker image. Doh!

I did not know 'Microsoft SQL Server on Linux for Docker Engine' was a thing!

**Comment by D10221** [comment]
Thanks, 
yes... I think the docker image is better  suited for CI, and blends with the existing tests

**Comment by iaincollins** [comment]
@D10221 This works excellently, thank you! This is really excellent.

I'm going to merge it into an interim branch just so I can test it with a fix for 3.0.1 (which relates an issue with TypeORM adapter, not with the changes in this branch) and so that we can manage the release - as merging it into master will publish the docs site right away.

**Comment by D10221** [comment]
Glad you are happy, thanks to you  : )

**Pull request merged**
