### PR TITLE
Reddit Provider and Documentation

### LINKED ISSUE #856: How to implement Reddit [Possible Solution]
**Your question**

Do any of you know how to make [Reddit](https://www.reddit.com/dev/api/oauth) work?

**What are you trying to do**

I am trying to authenticate but once I authorize get_access_token fails and returns a 401 error

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

### PR DESCRIPTION
**Pull request by afoyer**
**What**: Updated Reddit Provider and Documentation

**Why**: More Providers!

**How**: Creating a new reddit.md and removing comments from reddit.js

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged
      

In the current canary version, I had to go through updating the index of the providers so that next-auth can recognize SignIn('reddit'). I can't seem to find it in the github page so let me know what needs to be done.

Fixes #856

### CODE REVIEW

**Comment by balazsorban44** [comment]
Are you talking about this file: https://www.github.com/nextauthjs/next-auth/tree/canary/src%2Fproviders%2Findex.js

**Comment by afoyer** [comment]
aha! alright will do. thanks

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Only https://github.com/nextauthjs/next-auth/blob/canary/www/docs/faq.md#what-authentication-services-does-nextauthjs-support remains (Please add Reddit to the providers there as well), and then it's good to go!

**Comment by afoyer** [comment]
Ok done! Thanks for guiding me through all of this.

**Review by balazsorban44 — APPROVED** [review]
Thanks!

**Pull request merged**
