### PR TITLE
Patch node modules  next  headers not found

### PR DESCRIPTION
**Pull request by OpenTextASOWSM**
## ☕️ Reasoning
This is the fix described in - 
https://github.com/nextauthjs/next-auth/issues/10282

seems a reasonable number of people are hitting this issue. 

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues
https://github.com/nextauthjs/next-auth/issues/10282
 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by OpenTextASOWSM** [comment]
Update - https://github.com/nextauthjs/next-auth/pull/10283 for describing issues in node_modules for nextauth

**Comment by OpenTextASOWSM** [comment]
Sorry - bug report - https://github.com/nextauthjs/next-auth/issues/10284

**Comment by balazsorban44** [comment]
Closing until this is resolved: https://github.com/nextauthjs/next-auth/issues/10284#issuecomment-1994489130

**Comment by OpenTextASOWSM** [comment]
Issue resubmitted with reproduction 
https://github.com/nextauthjs/next-auth/issues/10301 

reproduction: https://github.com/OpenTextASOWSM/authjs-nextauth-5beta-repro

**Comment by OpenTextASOWSM** [comment]
Merged my changes and did new pull request - https://github.com/nextauthjs/next-auth/pull/10304

**Pull request closed without merging**
