### PR TITLE
Update Neo4j Adapter docs in order to allow compatibility with Neo4j v5

### PR DESCRIPTION
**Pull request by pedsm**
## ☕️ Reasoning

Neo4j v5 has been out for a month now and from my limited testing, Next-Auth seems compatible with it. The only breaking change is the syntax used for constraints. This PR will update the docs so that users can use Neo4j v5 as their DB.

Neo4j v5 dropped support for the following syntax

```cypher
CREATE CONSTRAINT ON ... ASSERT ...
// Replaced by:
CREATE CONSTRAINT FOR ... REQUIRE ...
```

[Source](https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#_removed_features)

## 🧢 Checklist

- [x] Documentation
- Tests (Docs only)
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by pedsm** [comment]
@EarthlingDavey I saw in the other thread you are using this adapter in production. Any thoughts on this?

**Comment by EarthlingDavey** [comment]
@pedsm I appreciate the mention, and of course the update. I'm still on v4 in prod btw.

I haven't run the commands for v5 here, but they look good to me. If you've run them on your v5 db, and they work, then I have no probs with the merge 👍

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Should we add v5 to peer dependencies too?:

https://github.com/nextauthjs/next-auth/blob/54561a1231c3f9576b2a787f1ce4cf9d76ae179c/packages/adapter-neo4j/package.json#L36

I am fuzzy about what is breaking. Will the new syntax not work for v4 users? Can we have support for both v4 and v5, or do you think we should release a major and bump the peer dependency instead of adding v5 next to v4?

**Comment by pedsm** [comment]
@balazsorban44 you do have a good point, this is probably backwards compatible with v4 but I didn't test it, will give it a spin at some point this week.

**Comment by balazsorban44** [comment]
@pedsm were you able to figure out if this is backward compatible?

**Comment by balazsorban44** [comment]
Closing in favor of #7392

**Pull request closed without merging**
